### ISSUE TITLE
BGPPeerConnectivityProfile doesn't allow setting local AS back to none after having ASN set

### ISSUE THREAD

**Issue by jeremypng** [CiscoDevNet/terraform-provider-aci#1007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```shell
terraform -v
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.6.0
```

### APIC version and APIC Platform

* V 5.2.6e and on-prem

### Affected Resource(s)

* aci_bgp_peer_connectivity_profile

### Terraform Configuration Files
without local as defined
```json
{
   "aci_bgp_peer_connectivity_profile": {
      "bgp_peer1": {
        "//": {
          "metadata": {
            "path": "dc1/ASR-Temp_-N93180YC-BL1-BL2-10.255.254.33",
            "uniqueId": "ASRTempN93180YCBL1BL21025525433_EB6A7BB5"
          }
        },
        "addr": "10.255.255.50",
        "as_number": "65535",
        "parent_dn": "uni/tn-common/out-ASR-Temp__L3Out/lnodep-ASR-Temp_LNP/lifp-ASR-Temp_to_-N93180YC-BL1-BL2/rspathL3OutAtt-[topology/pod-1/paths-102/pathep-[eth1/48]]"
      }
}
```

with local as defined
```json
{
   "aci_bgp_peer_connectivity_profile": {
      "bgp_peer1": {
        "//": {
          "metadata": {
            "path": "dc1/ASR-Temp_-N93180YC-BL1-BL2-10.255.254.33",
            "uniqueId": "ASRTempN93180YCBL1BL21025525433_EB6A7BB5"
          }
        },
        "addr": "10.255.255.50",
        "as_number": "65535",
        "local_as": "555",
        "parent_dn": "uni/tn-common/out-ASR-Temp__L3Out/lnodep-ASR-Temp_LNP/lifp-ASR-Temp_to_-N93180YC-BL1-BL2/rspathL3OutAtt-[topology/pod-1/paths-102/pathep-[eth1/48]]"
      }
}
```

with local as defined as empty string
```json
{
   "aci_bgp_peer_connectivity_profile": {
      "bgp_peer1": {
        "//": {
          "metadata": {
            "path": "dc1/ASR-Temp_-N93180YC-BL1-BL2-10.255.254.33",
            "uniqueId": "ASRTempN93180YCBL1BL21025525433_EB6A7BB5"
          }
        },
        "addr": "10.255.255.50",
        "as_number": "65535",
        "local_as": "",
        "parent_dn": "uni/tn-common/out-ASR-Temp__L3Out/lnodep-ASR-Temp_LNP/lifp-ASR-Temp_to_-N93180YC-BL1-BL2/rspathL3OutAtt-[topology/pod-1/paths-102/pathep-[eth1/48]]"
      }
}
```

with local as defined as null:
```json
{
   "aci_bgp_peer_connectivity_profile": {
      "bgp_peer1": {
        "//": {
          "metadata": {
            "path": "dc1/ASR-Temp_-N93180YC-BL1-BL2-10.255.254.33",
            "uniqueId": "ASRTempN93180YCBL1BL21025525433_EB6A7BB5"
          }
        },
        "addr": "10.255.255.50",
        "as_number": "65535",
        "local_as": null,
        "parent_dn": "uni/tn-common/out-ASR-Temp__L3Out/lnodep-ASR-Temp_LNP/lifp-ASR-Temp_to_-N93180YC-BL1-BL2/rspathL3OutAtt-[topology/pod-1/paths-102/pathep-[eth1/48]]"
      }
}
```

### Actual Behavior

When using the BGPPeerConnectivityProfile two issues occur:
1. If the profile is initially created without a "local as" defined, defining one in Terraform creates an error on modification.
`
Error: configured object ((Dn0)) not found Dn0=uni/tn-common/out-ASR-Temp__L3Out/lnodep-ASR-Temp_LNP/lifp-ASR-Temp_to_-N93180YC-BL1-BL2/rspathL3OutAtt-[topology/pod-1/paths-102/pathep-[eth1/48]]/peerP-[10.255.255.50]/localasn, 
`
2. If the profile has a "local as" defined at creation, and you set it back to none or a zero length string, the following apply does not detect a change even though the state shows the local_as and the configured object does not have a configured local_as.

### Steps to Reproduce

1. Create a bgppeerconnectivity profile omitting the local_as
2. `terraform apply`
3. Add the local_as to the configuration
4.  `terraforma apply`

1. Create a bgppeerconnectivity profile including a local_as number
2. `terraform apply`
3. Remove the local_as number or set it to null
4. `terraform apply`

### Important Factoids

I'm using a JSON configuration for terraform instead of HCL.

### References

* #369 
* #412

**Comment by shrsr** [comment]
@jeremypng 1. The first anomaly reported in this issue is fixed.
2. Currently there is no conclusive fix available for the second reported issue due to limitation in the Terraform Plugin.
