### ISSUE TITLE
Unable to create cloud context profile with 2.6.0.

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-aci#1008]
### Versions

Terraform v1.2.2
Provider 2.6.0
CNC 25.1(1e) on Azure

### Affected Resource(s)

* aci_cloud_context_profile

### Terraform Configuration File

```hcl
resource "aci_cloud_context_profile" "ctx-vrf1" {
  tenant_dn                = data.aci_tenant.terraform_ten.id
  name                     = var.cxt_name
  primary_cidr             = var.cxt_cidr
  region                   = var.cxt_region
  cloud_vendor             = var.cloud_vendor
  relation_cloud_rs_to_ctx = aci_vrf.vrf1.id
  hub_network              = "uni/tn-infra/gwrouterp-${var.vnet_peering}" #VNet Peering is enabled by default
}
```

### Issue

Unable to create cloud context profile with 2.6.0. It works on previous versions. 

*Error: property cloudProviderId of uni/tn-devnet/ctxprofile-ctx-vrf1-uksouth/brownfield/idMapping-[] failed validation for value ''*

  *with aci_cloud_context_profile.ctx-vrf1,*
   *on main.tf line 14, in resource "aci_cloud_context_profile" "ctx-vrf1":*
   *14: resource "aci_cloud_context_profile" "ctx-vrf1" {*

### Debug

https://gist.github.com/marinalf/d0cbdc05201a555419a83398efc30504

**Comment by lhercot** [comment]
Closed by PR #1009
