### ISSUE TITLE
Unable to use shared subscription for cloud account resource

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-aci#1013]
### Versions

Terraform v1.2.2
Provider 2.6.1
CNC 25.1(1e) on Azure

### Affected Resource(s)

* aci_cloud_account

### Terraform Configuration

```hcl
resource "aci_tenant" "terraform_ten" {
  name        = var.tenant_name
  description = "This tenant has been created by Terraform"
}

resource "aci_cloud_account" "cloud_provider" {
  name        = "azure_cloud"
  tenant_dn   = aci_tenant.terraform_ten.id
  account_id  = var.subscription_id
  access_type = "managed"
  vendor      = "azure"
}

resource "aci_tenant_to_cloud_account" "cloud_acct_ten" {
  tenant_dn        = aci_tenant.terraform_ten.id
  cloud_account_dn = aci_cloud_account.cloud_provider.id
}
```

### Issue

The subscription is shared with the infra tenant. Per [example](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/examples/aci_cloud_account/azure/main.tf), the config is the same for new or shared subscription. No issues if using a new subscription. Unless this can be done using data sources, we would need an argument to specify "shared" under the resource. 

aci_cloud_account.cloud_provider: Creating...
╷
│ Error: Invalid Configuration : An account already exist with the same id, the account id must be unique: uni/tn-infra/act-[00dc6ffb-0db2-4ffa-a451-b1f0773a9326]-vendor-azure
│ 
│   with aci_cloud_account.cloud_provider,
│   on main.tf line 9, in resource "aci_cloud_account" "cloud_provider":
│    9: resource "aci_cloud_account" "cloud_provider" {

### References

* #912

**Comment by anvitha-jain** [comment]
Hi Marina, in the code mentioned above, resource is being used for aci_cloud_account, which means you are trying to create a new resource.

To add subscription to already existing aci_cloud_account you need to use data source.
Try using below modified example 

resource "aci_tenant" "terraform_ten" {
  name        = var.tenant_name
  description = "This tenant has been created by Terraform"
}

data "aci_cloud_account" "cloud_provider" {
  tenant_dn  = aci_cloud_account.<cloud_account that already exists >.tenant_dn
  account_id = aci_cloud_account.<cloud_account that already exists >.account_id
  vendor     = aci_cloud_account.<cloud_account that already exists >.vendor
}

data "aci_tenant_to_cloud_account" "cloud_acct_ten" {
  tenant_dn        = aci_tenant.<aci_tenant_to_cloud_account that already exists >.id
  cloud_account_dn = aci_cloud_account.<aci_tenant_to_cloud_account that already exists >.id
}

**Comment by marinalf** [comment]
Thanks, Anvitha. The new example with data source using the tn-infra works perfectly.
