### ISSUE TITLE
enhanced_lag_policy on aci_epg_to_domain not working

### ISSUE THREAD

**Issue by phand00** [CiscoDevNet/terraform-provider-aci#1014]
Hi,

running Terraform 1.3.4 with ACI Provider 2.5.2

When I try to add the enhanced_lag_policy property to an existing VMM domain (aci_epg_to_domain) nothing is really done in ACI. The apply complete successfully but the lag name is not applied to the VMM domain entry when I look in ACI apic and in VMware DVS properties.

If I taint the ressource for delete and recreate, it works and the lag is applied successfully and can confirm it's fine with ACI apic and in VMware DVS properties.

terraform❯aci-lab▶vnid▶1✎▶8⚑▶$▶ terraform -version
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.5.2

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* aci_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by shrsr** [comment]
@phand00 Can you please provide your "aci_epg_to_domain" terraform configuration?

**Comment by phand00** [comment]
yes for sure

It's a module but it's pretty simple

resource "aci_epg_to_domain" "THIS_VMM_DOM" {
  for_each = {
    for dom in var.doms : dom.tdn => dom if(length(regexall("uni\\/vmmp-", dom.tdn)) > 0)
  }
  application_epg_dn = aci_application_epg.THIS_EPG.id
  switching_mode     = coalesce(each.value.switching_mode, "native")

  tdn          = each.key
  encap_mode   = coalesce(each.value.encap_mode, "vlan")
  res_imedcy   = coalesce(each.value.res_imedcy, "immediate")
  instr_imedcy = coalesce(each.value.instr_imedcy, "immediate")
  encap        = "vlan-${coalesce(each.value.vlan, var.vlan)}"

  vmm_allow_promiscuous = coalesce(each.value.vmm_allow_promiscuous, "reject")
  vmm_forged_transmits  = coalesce(each.value.vmm_forged_transmits, "reject")
  vmm_mac_changes       = coalesce(each.value.vmm_mac_changes, "reject")

  enhanced_lag_policy = try("${each.value.tdn}/vswitchpolcont/enlacplagp-${each.value.lag}", "")
}

the result on the apply is:

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.epg["LAB_UCS_STIPUB_DMZ"].aci_epg_to_domain.THIS_VMM_DOM["uni/vmmp-VMware/dom-LAB_INFRA"] will be updated in-place
  ~ resource "aci_epg_to_domain" "THIS_VMM_DOM" {
      + enhanced_lag_policy   = "uni/vmmp-VMware/dom-LAB_INFRA/vswitchpolcont/enlacplagp-lag1"
        id                    = "uni/tn-LAB/ap-LAB_AP/epg-LAB_UCS_STIPUB_DMZ/rsdomAtt-[uni/vmmp-VMware/dom-LAB_INFRA]"
        # (23 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "prod"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.epg["LAB_UCS_STIPUB_DMZ"].aci_epg_to_domain.THIS_VMM_DOM["uni/vmmp-VMware/dom-LAB_INFRA"]: Modifying... [id=uni/tn-LAB/ap-LAB_AP/epg-LAB_UCS_STIPUB_DMZ/rsdomAtt-[uni/vmmp-VMware/dom-LAB_INFRA]]
module.epg["LAB_UCS_STIPUB_DMZ"].aci_epg_to_domain.THIS_VMM_DOM["uni/vmmp-VMware/dom-LAB_INFRA"]: Modifications complete after 0s [id=uni/tn-LAB/ap-LAB_AP/epg-LAB_UCS_STIPUB_DMZ/rsdomAtt-[uni/vmmp-VMware/dom-LAB_INFRA]]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

**Comment by phand00** [comment]
![image](https://user-images.githubusercontent.com/15458750/217556221-c51347b5-1644-4875-be9f-db4c99b613b9.png)

**Comment by shrsr** [comment]
I was not able to reproduce it at my end. However, I'm taking a deeper look and will keep you updated.

**Comment by shrsr** [comment]
I know what's going on here and I made a fix. However, it may take time for it to be incorporated and be released. I could share the binary with you to try it at your end.

**Comment by phand00** [comment]
Hi shrsr, 

yes. If you have the binary I may try it next week. Is the binary realeased for the same version I'm running or I'll need to upgrade?

Thanks
