### ISSUE TITLE
Security Domain Creation & Mapping

### ISSUE THREAD

**Issue by PhilipWhiteside** [CiscoDevNet/terraform-provider-aci#102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am trying to setup multiple accounts with dedicated Tenants with a mapping via the Security Domain. However, there is no SecDom option that I can find (the rest option does not clean up once I'm done with it). 

The goal is to setup isolate environment to enable members of my team to try automation tools freely within their own tenant space. In particular, to have them get more hands on experience with Terraform & ACI. I can create a Terraform user on APIC for each of them, as well as a Tenant, but I can't map the two together. 

The SecDom settings I'd like to end up with should enable:

- Full access to their tenant
- Read access to common for Contracts, L3Out, etc

### New or Affected Resource(s) + ACI Class(es):

```json
{
    "aaaDomain": {
        "attributes": {
            "dn": "uni/userext/domain-${local.username_prefix}${var.users[count.index]}${local.username_suffix}",
            "name": "${local.username_prefix}${var.users[count.index]}${local.username_suffix}",
            "rn": "domain-${local.username_prefix}${var.users[count.index]}${local.username_suffix}",
            "status": "created"
        },
        "children": []
    }
}
```

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.

**Comment by smoncada-ntt-bcn** [comment]
I'm very interested in this resolution , please update , cause I can't get ride with shell:domains, I even cannot associate users to RBACs... Thank you !

**Comment by nkatarmal-crest** [comment]
@smoncada-ntt-bcn I have already added resource for aaaDomain. If you need any other classes to be supported feel free to raise a new enhancement request.

**Comment by smoncada-ntt-bcn** [comment]
Thanks so much Nirav.

**Comment by PhilipWhiteside** [comment]
Thank you for the work so far. 

It's not possible to map the user or tenant into the domain. There is no `aaaUserDomain` argument on user or tenant resource.
