### ISSUE TITLE
Create a new resource and data-source for External EPG contracts - Classes: "fvRsProv" "fvRsCons"

### ISSUE THREAD

**Issue by cla-azzarello** [CiscoDevNet/terraform-provider-aci#1023]
**API Information:**
Class: "fvRsProv"
Distinguised Name: "uni/tn-${aci_tenant}/out-${aci_l3_outside}/instP-${aci_external_network_instance_profile}/rsprov-${aci_contract}"

Class: "fvRsCons"
Distinguised Name: "uni/tn-${aci_tenant}/out-${aci_l3_outside}/instP-${aci_external_network_instance_profile}/rscons-${aci_contract}"

**GUI Location:**
Tenants > {tenant} > Networking > L3Outs > {l3out} > External EPGs > {ext_epg}: Contracts

**Comment by lhercot** [comment]
Hi @cla-azzarello 

You can configure the contracts by using the relation_fv_rs_prov and relation_fv_rs_cons in https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/external_network_instance_profile
If you want a separate resource you can also use https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/epg_to_contract and pass the DN / id of the external EPG in the application_epg_dn attribute.

**Comment by cla-azzarello** [comment]
Hi @lhercot,

Thanks for your answer.

I had tried using the aci_epg_to_contract resource, but something went wrong.

After applying the configuration, if I ran a terraform plan without any changes, the contracts were removed.

I'm trying to reproduce the problem, but I can't. There was probably something wrong in my status file. It's strange, because I had also tried removing every file except the tf files and reinitializing the plan and the problem remained. I can't explain it.

Sorry for the trouble and thank you.

**Comment by lhercot** [comment]
Thanks for the response. I will be closing this issue as you mentioned it is solved.

**Comment by cla-azzarello** [comment]
Thank you @lhercot .

I just would suggest to mention this use case in the documentaion on Terraform Registry portal.

The aci_epg_to_contract resource and datasource are documented only in "Application Management" section and the Example Usage states:

`application_epg_dn = aci_application_epg.demo.id`

It is not clear that this is usable for external EPGs too.

No mention on it neither on the L3Out section.

**Comment by lhercot** [comment]
Good point. Let me reopen it and find a way to fix that documentation part.
