### ISSUE TITLE
associating a security domain to a tenant

### ISSUE THREAD

**Issue by nadeemkhawaja** [CiscoDevNet/terraform-provider-aci#1024]
Hi,
Trying to figure out how to add security domain while creating a tenant. right now i am using rest api call to do it in my TF code.

thanks
Nadeem

**Comment by nadeemkhawaja** [comment]
Thank you , this worked. I have to another question on using AEP to EPG. I couldnt see that option. What is the best way to get it working?

**Comment by lhercot** [comment]
Thanks for confirming. I will close this one as you opened another one for that question.
