### ISSUE TITLE
Associating interface profile to switch profile using terraform - relation_infra_rs_acc_card_p

### ISSUE THREAD

**Issue by MyUsernameIsTakenAgain** [CiscoDevNet/terraform-provider-aci#1038]
Dear,

I cannot associate the leaf_interface_profile into the switch profile using the relation_infra_rs_acc_card_p
the configuration is success, but in the ACI nothing happens.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.7.0

### APIC version and APIC Platform

Version: 5.2(3f)

### Affected Resource(s)

resource "aci_leaf_profile"

### Terraform Configuration Files

resource "aci_leaf_profile" "SwProf-leaf101" {
  name        = "SwProf-leaf101"
  description  = "From Terraform"
 #this part below has an issue
 relation_infra_rs_acc_card_p = [aci_leaf_interface_profile.IntProf-leaf101.id]
}

### Debug Output

it will always try to do the change below, still the association never happen even after I apply, and everytime i do terrafrom apply it will still keep applying the change, so the code never reach matching status between the infrastructure and the code.

Terraform will perform the following actions:

  # module.access-policies.aci_leaf_profile.SwProf-leaf101 will be updated in-place
  ~ resource "aci_leaf_profile" "SwProf-leaf101" {
        id                           = "uni/infra/nprof-SwProf-leaf101"
        name                         = "SwProf-leaf101"
      ~ relation_infra_rs_acc_card_p = [
          + "uni/infra/accportprof-IntProf-leaf101",
        ]
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

### Expected Behavior

the association shall happen as soon as I apply, 

### Actual Behavior

no matter how many times I apply the association never happen, and the code still think that there are changes to be implemented, i keep getting this output

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.access-policies.aci_leaf_profile.SwProf-leaf101 will be updated in-place
  ~ resource "aci_leaf_profile" "SwProf-leaf101" {
        id                           = "uni/infra/nprof-SwProf-leaf101"
        name                         = "SwProf-leaf101"
      ~ relation_infra_rs_acc_card_p = [
          + "uni/infra/accportprof-IntProf-leaf101",
        ]
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by shrsr** [comment]
Closing this issue because relation_infra_rs_acc_card_p was being used instead of relation_infra_rs_acc_port_p.
Discussion regarding this - #738
