### ISSUE TITLE
Unable to add CIDRs on secondary VRF using  aci_cloud_cidr_pool

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-aci#1050]
### Description

There is no option to associate new CIDRs in the Hub VNet to a secondary VRF using the aci_cloud_cidr_pool. 

### Terraform Version

Terraform v1.4.6

### Version 

* CNC 26.0(1c) on Azure

### Affected Resource(s)

* aci_cloud_cidr_pool
* aci_cloud_context_profile

### Terraform Configuration Files

```hcl
data "aci_cloud_context_profile" "hub_vnet" {
  tenant_dn  = data.aci_tenant.infra_tenant.id
  name       = "ct_ctxprofile_japaneast" # Hub VNet Cloud Context Profile (overlay-1)
}

resource "aci_cloud_cidr_pool" "fw_cidr" {
  cloud_context_profile_dn = data.aci_cloud_context_profile.hub_vnet.id
  addr                     = var.fw_cidr
  primary                  = "no"
}

resource "aci_cloud_subnet" "fw_subnets" {
  for_each           = var.fw_subnets
  cloud_cidr_pool_dn = aci_cloud_cidr_pool.fw_cidr.id
  name               = each.value.name
  ip                 = each.value.ip
}

```

### Debug Output

https://gist.github.com/marinalf/1994cb133e8a17faf66cbfb197d4a797

### References

* #1049

**Comment by marinalf** [comment]
It creates the secondary VRF, associate the new CIDR and subnets under the infra context profile, but it does not show the association under the VRF menu itself. This is causing only the CIDR to be pushed to Azure, and it is not pushing the subnets. 

```
resource "aci_vrf" "services_vrf" {
  tenant_dn = data.aci_tenant.infra_tenant.id # Secondary VRF to host new CIDRs within Hub VNet.
  name      = var.services_vrf
}

resource "aci_cloud_cidr_pool" "fw_cidr" {
  cloud_context_profile_dn = data.aci_cloud_context_profile.hub_vnet.id
  addr                     = var.fw_cidr
  primary                  = "no"
}

resource "aci_cloud_subnet" "fw_subnets" {
  for_each                        = var.fw_subnets
  cloud_cidr_pool_dn              = aci_cloud_cidr_pool.fw_cidr.id
  name                            = each.value.name
  ip                              = each.value.ip
  relation_cloud_rs_subnet_to_ctx = aci_vrf.services_vrf.id
}
```

<img width="1417" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/12536683/eed71bb1-f11d-46b3-bf08-d072a20e9650">

<img width="1022" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/12536683/8f459935-7789-48c3-9870-133d181df98b">

**Comment by shrsr** [comment]
@marinalf Can you please try adding the zone attribute to the cloud subnet resource as shown below:

```
resource "aci_cloud_subnet" "fw_subnets" {
  for_each                        = var.fw_subnets
  cloud_cidr_pool_dn              = aci_cloud_cidr_pool.fw_cidr.id
  name                            = each.value.name
  ip                              = each.value.ip
  relation_cloud_rs_subnet_to_ctx = aci_vrf.services_vrf.id
  zone = "uni/clouddomp/provp-azure/region-japaneast/zone-default"
}
```

**Comment by shrsr** [comment]
Based on an offline discussion with @marinalf, adding the attribute **zone** with the appropriate value overcomes the issue.
A slight change in the docs was made to accommodate this -> #1075
