### ISSUE TITLE
rtr_id_loop_back should accept both yes and true as values

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#106]
Resource `aci_logical_node_to_fabric_node` is marked for change when `rtr_id_loop_back` is set to `true`.
It should support both `true` and `yes` indifferently.

Nic

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.
