### ISSUE TITLE
aci_contract: provider crash when configuring filter + filter_entry

### ISSUE THREAD

**Issue by mlyngbol** [CiscoDevNet/terraform-provider-aci#1065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.1
on linux_amd64

terraform-provider-aci_v2.8.0

### APIC version and APIC Platform

* ACI 6.0(2h) on-prem

### Affected Resource(s)

* aci_contract

### Terraform Configuration Files

```hcl
resource "aci_tenant" "this" {
  name                  = var.tenant_name
  description           = var.tenant_description
}

resource "aci_vrf" "this" {
  tenant_dn             = aci_tenant.this.id
  name                  = var.vrf_name
}

resource "aci_contract" "this" {
  tenant_dn             = aci_tenant.this.id
  name                  = "CONT-VZANY-VRF-0001"
  description           = "vzAny permit any contract"
  scope                 = "context"
  filter {
    filter_name         = "FILTER-VZANY"
    description         = "vzAny filter"
    filter_entry {
      filter_entry_name = "ENTRY-1"
      description       = "Permit any"
      ether_t           = "ip"
    }
  }
}
```

### Debug Output

available upon request

### Panic Output

https://gist.githubusercontent.com/mlyngbol/4391a87a2b30c9c48187f829035d3972/raw/947a109f745e1bf826fdb0dbbdf47e7fbcd160e7/terraform-aci-provider-crash-output.txt

### Expected Behavior

provider to work and not crash

### Actual Behavior

provider crashed

### Steps to Reproduce

Due to this provider issue: https://github.com/CiscoDevNet/terraform-provider-aci/issues/1055, I've tried to create the filter + filter_entry via the aci_contract resource and via aci_filter and aci_filter_entry resources.

Hence .tf file used to include aci_filter + aci_filter_entry resources, but as said tried to move to filter via aci_contract.

One might need for flip back and forth between aci_filter + aci_filter_entry vs aci_contract+filter to trigger this issue.

terraform plan
terraform apply -auto-approve

crash ...

does not seem to happen in a clean setup where the above .tf is applied initially.

* #0000

**Comment by micronemo** [comment]
I don't understand this type of configuration since in no way does it also generate a relationship with the aci_contract_subject that binds filters to the contract. it is basically a non-functioning configuration
