### ISSUE TITLE
aci_configuration_export_policy not recognizing relationship to export_destination

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#1073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.9.0
+ provider registry.terraform.io/ciscodevnet/mso v0.10.0
+ provider registry.terraform.io/netascode/utils v0.2.5
```

### APIC version and APIC Platform

* V 6.0.2 and on-prem

### Affected Resource(s)

* aci_configuration_export_policy

### Terraform Configuration Files

```hcl
resource "aci_configuration_export_policy" "map" {
   id                                    = "uni/fabric/configexp-lnx1.rich.ciscolabs.com"
   name                                  = "lnx1.rich.ciscolabs.com"
   relation_config_rs_export_destination = "uni/fabric/path-lnx1.rich.ciscolabs.com"
```

### Debug Output

relationship to export_destination is not functioning

Each Plan/Apply shows adding the relationship 

```
resource "aci_configuration_export_policy" "map" {
        id                                    = "uni/fabric/configexp-lnx1.rich.ciscolabs.com"
        name                                  = "lnx1.rich.ciscolabs.com"
      + relation_config_rs_export_destination = "uni/fabric/path-lnx1.rich.ciscolabs.com"
```
### Expected Behavior

relationship should form
### Actual Behavior

the resource relationship to export_destination is not being saved to state.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by scotttyso** [comment]
If I perform the same task with the aci_rest module the above example works

```
  # module.system_settings["default"].aci_rest.bgp_instance["default"] will be created
  + resource "aci_rest" "bgp_instance" {
      + class_name = "bgpInstPol"
      + content    = {
          + "annotation" = "terraform:orchestrator"
        }
      + dn         = (known after apply)
      + id         = (known after apply)
      + path       = "/api/mo/uni/fabric/bgpInstP-default.json"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: main.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "main.plan"
tyscott@TYSCOTT-DESKTOP:~/terraform-cisco-modules/aci-test$ tfa
module.system_settings["default"].aci_rest.bgp_instance["default"]: Creating...
module.system_settings["default"].aci_rest.bgp_instance["default"]: Creation complete after 0s [id=uni/fabric/bgpInstP-default]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:
```

**Comment by scotttyso** [comment]
This can be closed.  I am looking at this and I mixed up two things.  This issue doesn't make sense.

related to the aci_configuration_export_policy 

I found that there was a new rss for it  "relation_config_rs_remote_path"

**Comment by lhercot** [comment]
FYI, we have added a deprecation warning and a note in the documentation in v2.10.1

**Comment by scotttyso** [comment]
@lhercot thanks
