### ISSUE TITLE
Resource aci_interface_config does not return PcPortDn

### ISSUE THREAD

**Issue by dirkf98** [CiscoDevNet/terraform-provider-aci#1080]
Hello,

I'd like to use Terraform to configure interfaces with the resource "aci_interface_config" and later configure a static port with "aci_bulk_epg_to_static_path".
However, for "aci_bulk_epg_to_static_path" I need the interface_dn for the specific ports and I'm not able to pull that from the state returned by "aci_interface_config".
When I check the object browser for the created "infraPortConfig" object the attribute "pcPortDn" seems to hold the appropriate value, but it is not part of the terraform state for this object.

Is it missing there (and can you add it) or am I missing something?

Dirk

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.9.0

### APIC version and APIC Platform

* V 5.2(7g) and on-prem

### Affected Resource(s)

* aci_interface_config
* aci_epg_to_static_path
* aci_bulk_epg_to_static_path

### Terraform Configuration Files

```hcl
locals {
  vpc_servers_helper_map = {
  "testserver_dialog_1" = {
    "admin_state" = "up"
    "description" = "testserver_dialog"
    "interface" = "1/2"
    "node" = 1101
    "policy_group" = "uni/infra/funcprof/accbundle-vpc_testserver1_ipg"
    "server" = "testserver_dialog_1"
  }
  "testserver_dialog_2" = {
    "admin_state" = "up"
    "description" = "testserver_dialog"
    "interface" = "1/2"
    "node" = 1102
    "policy_group" = "uni/infra/funcprof/accbundle-vpc_testserver1_ipg"
    "server" = "testserver_dialog_2"
  }
}

}
resource "aci_interface_config" "vpc_servers_intfs" {
  for_each = local.vpc_servers_helper_map
  node         = each.value.node
  interface    = each.value.interface
  policy_group = each.value.policy_group
  admin_state =  each.value.admin_state
}
```

### Expected Behavior

The attribute PcPortDn should be part of the state to be used later on by aci_bulk_epg_to_static_path

### Actual Behavior

attribute PcPortDn is not part of state. It is unclear to me how to use the create port in aci_bulk_epg_to_static_path

**Comment by dirkf98** [comment]
@shrsr,

thanks for the quick reply. I tried using the id and unfortunately it failed.
This is the output from creating the interfaces. I'm creating a VPC port-channel on 2 leaf switches.
```
my_port_list = {
  "testserver_dialog_1" = {
    "admin_state" = "up"
    "annotation" = "orchestrator:terraform"
    "breakout" = ""
    "description" = ""
    "id" = "uni/infra/portconfnode-1101-card-1-port-2-sub-0"
    "interface" = "1/2/0"
    "name_alias" = tostring(null)
    "node" = 1101
    "pc_member" = ""
    "policy_group" = "uni/infra/funcprof/accbundle-vpc_testserver1_ipg"
    "port_type" = "access"
    "role" = "leaf"
  }
  "testserver_dialog_2" = {
    "admin_state" = "up"
    "annotation" = "orchestrator:terraform"
    "breakout" = ""
    "description" = ""
    "id" = "uni/infra/portconfnode-1102-card-1-port-2-sub-0"
    "interface" = "1/2/0"
    "name_alias" = tostring(null)
    "node" = 1102
    "pc_member" = ""
    "policy_group" = "uni/infra/funcprof/accbundle-vpc_testserver1_ipg"
    "port_type" = "access"
    "role" = "leaf"
  }
}

```

Using the id when configuring a static_port I got this error message:

Terraform will perform the following actions:

```
  # aci_epg_to_static_path.test_port will be created
  + resource "aci_epg_to_static_path" "test_port" {
      + annotation         = "annotation"
      + application_epg_dn = "uni/tn-feld09-tf_ten/ap-back_ap/epg-port_test"
      + description        = (known after apply)
      + encap              = "vlan-18"
      + id                 = (known after apply)
      + instr_imedcy       = "lazy"
      + mode               = "regular"
      + primary_encap      = (known after apply)
      + tdn                = "uni/infra/portconfnode-1101-card-1-port-2-sub-0"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_epg_to_static_path.test_port: Creating...
╷
│ Error: Invalid target DN: uni/infra/portconfnode-1101-card-1-port-2-sub-0
│ 
│   with aci_epg_to_static_path.test_port,
│   on main.tf line 102, in resource "aci_epg_to_static_path" "test_port":
│  102: resource "aci_epg_to_static_path" "test_port" {
│ 
╵

```

Dirk

**Comment by shrsr** [comment]
From the error I can think of a few scenarios that may be causing this.
Question -> Was the resource "aci_interface_config" already created before trying to apply the above configuration?

It would also help me if you shared your terraform configuration leading up to "aci_epg_to_static_path".

**Comment by shrsr** [comment]
@dirkf98 My apologies. The id of interface_config won't work for what you're trying to configure. After discussion with @lhercot and digging deeper into the interface_config's resource/data source I saw that we don't expose PcPortDn to any attribute. 
I made a change to our resource and data source to expose PcPortDn to pc_port_dn. Once this change is reviewed and released you'll be able to use it along these lines ->
```
tdn = aci_interface_config.access_port_config_1001.pc_port_dn
```
I also saw a portDn in the browser so I exposed that value as well. Once the change has been merged and released, I'll touch base with you. Sorry for the inconvenience.

**Comment by dirkf98** [comment]
@shrsr ,

thanks for looking into this and the quick reply.

Dirk

**Comment by shrsr** [comment]
@dirkf98 The latest release of the provider has pc_port_dn attribute exposed in the resource and data source of aci_interface_config. This attribute will have the VPC path DN when two switches in a VPC pair have multiple ports that are in the same policy group (resource aci_vpc_explicit_protection_group can be used for this).
Please let me know if you have any questions.

**Comment by dirkf98** [comment]
Hello Shreyas,

thank you for looking into this and the quick fix.
I’ll let you know if anything else comes up.

Dirk
