### ISSUE TITLE
Cannot import aci_epg_to_contract resource

### ISSUE THREAD

**Issue by al-lac** [CiscoDevNet/terraform-provider-aci#1094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.2

### APIC version and APIC Platform

* V 4.2 and on-prem

### Affected Resource(s)

* aci_epg_to_contract

### Terraform Configuration Files

```hcl
data "aci_contract" "https" {
  tenant_dn = data.aci_tenant.common.id
  name      = "https"
}

resource "aci_epg_to_contract" "https" {
  application_epg_dn = aci_external_network_instance_profile.test.id
  contract_dn        = aci_contract.https.id
  contract_type      = "consumer"
  match_t            = "AtleastOne"
  prio               = "unspecified"
}
```

### Expected Behavior

Resource should be imported when using `terraform import` command.

### Actual Behavior

An error is thrown that says the following:
`Error: Contract Type: Value must be from [provider, consumer]`

Running terraform apply imports it into the state, but probably also touches something on the aci.

### Steps to Reproduce

1.`terraform import 'aci_epg_to_contract.https' 'uni/tn-common/out-default/instP-test/rscons-https'`

### References

* #0000

**Comment by shrsr** [comment]
@al-lac Just making sure,
Do you see the error `Error: Contract Type: Value must be from [provider, consumer]` after using `terraform import 'aci_epg_to_contract.https' 'uni/tn-common/out-default/instP-test/rscons-https'`

**Comment by al-lac** [comment]
@shrsr yes exactly

**Comment by al-lac** [comment]
Importing the `aci_epg_to_contract_interface` resource works just fine.
