### ISSUE TITLE
aci_bgp_peer_connectivity_profile shortened ipv6 address forces replacement

### ISSUE THREAD

**Issue by bardahlm** [CiscoDevNet/terraform-provider-aci#1098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### APIC version and APIC Platform

* V 5.2(6e) on-prem

### Affected Resource(s)

* aci_bgp_peer_connectivity_profile

### Terraform Configuration Files

```hcl
(simplified, not production)
resource "aci_bgp_peer_connectivity_profile" "bgp_peer_wan6" {
  addr = "2001:db8:1052:ffff:9a3e:abe2::1/127"
  as_number = var.as_number
  peer_ctrl = ["bfd"]
  parent_dn = var.parent_dn
}
```

### Expected Behavior

Nothing, this was already configured in previous apply.

### Actual Behavior

Provider compares state and configuration and finds they are different:

```
(shortened)
resource "aci_bgp_peer_connectivity_profile" "bgp_peer_wan6" {
      addr                         = "2001:db8:1052:ffff:9a3e:abe2:0:1/127" -> "2001:db8:1052:ffff:9a3e:abe2::1/127" # forces replacement
}
```

These IPv6 adresses are the same, one is shortened and the other is not.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by akinross** [comment]
Hi @bardahlm,

I see there is a slight difference in the input of addr which would indeed trigger the force replace:

"2001:db8:1052:ffff:9a3e:abe2:0:1/127"
"2001:db8:1052:ffff:9a3e:abe2::1/127"

Just to verify, did you provide the same input of "2001:db8:1052:ffff:9a3e:abe2::1/127" twice?

**Comment by bardahlm** [comment]
IPv6 adresses can be represented in different ways. "2001:db8:1052:ffff:9a3e:abe2:0:1/127" and
"2001:db8:1052:ffff:9a3e:abe2::1/127" are the same address. See https://en.wikipedia.org/wiki/IPv6_address#Representation for explanation.

The latter form was used when the resource was created but stored on the APIC in the first form.
So the next time terraform plan is run with unchanged code, the provider finds a mismatch and want to recreate the resource, even though there is no change.

**Comment by akinross** [comment]
HI @bardahlm,

I am aware of the difference in representation, just wanted to confirm that indeed you are providing "2001:db8:1052:ffff:9a3e:abe2::1/127" twice. Thus confirming my initial thought that APIC stores the value in a different representation. 

For now as a workaround the only option around this is to use the same representation as APIC.
