### ISSUE TITLE
Ability to add Endpoint Tags (both Mac and IP)

### ISSUE THREAD

**Issue by JockeW-DvL** [CiscoDevNet/terraform-provider-aci#1103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) + ACI Class(es):

* aci_XXXXX + fv:XXXX

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by akinross** [comment]
Hi @JockeW-DvL, thanks for raising this issue. We are aware it is not possible to currently create via resource, and will add to list of to do items. In case you want to to already configure this while resource is not created, you could leverage the aci_rest_managed resource for this.

**Comment by robvand** [comment]
Here is an aci_rest_managed example for a MAC Policy:

```
resource "aci_rest_managed" "fvEpMacTags" {
  dn         = "uni/tn-${your-tenant}/eptags/epmactag-00:51:56:A2:0A:90-[*]"
  class_name = "fvEpMacTag"
  content = {
    mac     = "00:51:56:A2:0A:90"
    ctxName = "vrf-01"
  }
  child {
    class_name = "tagTag"
    rn         = "tagKey-Apps"
    content = {
      key   = "Apps"
      value = "your-tag"
    }
  }
}
```
