### ISSUE TITLE
Better descriptive error when missing ACI url protocol

### ISSUE THREAD

**Issue by caesaralves** [CiscoDevNet/terraform-provider-aci#1105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When exporting the ACI environment variables for the ACI url, I forgot to put the protocol as it should be `export ACI_URL=https://<IP of ACI Simulator>`.

In my case I only placed the IP of the ACI and missed the `https`.

This little mistake led to a not so specific error. The terraform plan went fine but when I tried to do `terraform apply` I got the following errors

```
│ Error: Failed to connect to APIC. Verify that you are connecting to an APIC.
│ Error message: Post "/api/aaaLogin.json": unsupported protocol scheme ""
│ 
│   with module.aci.module.aci_pod_setup["2"].aci_rest_managed.fabricSetupP,
│   on .terraform/modules/aci.aci_pod_setup/main.tf line 1, in resource "aci_rest_managed" "fabricSetupP":
│    1: resource "aci_rest_managed" "fabricSetupP" {
│ 
╵
╷
│ Error: Failed to connect to APIC. Verify that you are connecting to an APIC.
│ Error message: Post "/api/aaaLogin.json": unsupported protocol scheme ""
│ 
│   with module.aci.module.aci_port_channel_member_policy["FAST"].aci_rest_managed.lacpIfPol,
│   on .terraform/modules/aci.aci_port_channel_member_policy/main.tf line 1, in resource "aci_rest_managed" "lacpIfPol":
│    1: resource "aci_rest_managed" "lacpIfPol" {
│ 
```

As you see it says that the scheme protocol is not valid
`│ Error: Failed to connect to APIC. Verify that you are connecting to an APIC.
│ Error message: Post "/api/aaaLogin.json": unsupported protocol scheme ""`.

A more descriptive error would save lots of time to future users that miss this little detail.
After adding the protocol, it all went smooth.

### New or Affected Resource(s) + ACI Class(es):

"aci_rest_managed" 

### APIC version and APIC Platform
 V 6.0(2h) On-prem, lab.

* #0000

**Comment by akinross** [comment]
@caesaralves, thanks for raising the issue we will take it into consideration and add I will label it as todo.
