### ISSUE TITLE
aci_rest_managed child panic

### ISSUE THREAD

**Issue by stlarsen-dk** [CiscoDevNet/terraform-provider-aci#1108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.6
on windows_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.10.1

Also tested with 1.6.0-beta3 - same result

### APIC version and APIC Platform

* Version 6.0(2h) ACI_SIM,  not tested on physical

### Affected Resource(s)

* aci_rest_managed

### Terraform Configuration Files

variable pod1_tep {
  type        = string
  default     = "10.0.0.0/16"
  description = "Tep pool ip for pod 1"
}
variable pod1_ext_tep {
  type        = string
  default     = "10.2.0.0/24"
  description = "external tep pool ip for pod 1"
}

resource "aci_rest_managed" "pod1_tep" {
  dn         = "uni/controller/setuppol/setupp-1"
  class_name = "fabricSetupP"
  content = {
    tepPool  = var.pod1_tep
    podId = 1
    annotation = "orchestrator:terraform"
  }
  child {
    rn         = "extrtpodsubnet-[${var.pod1_ext_tep}]"
    class_name = "fabricExtRoutablePodSubnet"
    content = {
      dn = "uni/controller/setuppol/setupp-1/extrtpodsubnet-[${var.pod1_ext_tep}]"
      pool = var.pod1_ext_tep
      annotation = "orchestrator:terraform"
    }
  }
}

### Panic Output

aci_rest_managed.pod1_tep: Modifying... [id=uni/controller/setuppol/setupp-1]
╷
│ Error: Plugin did not respond
│
│   with aci_rest_managed.pod1_tep,
│   on pod.tf line 1, in resource "aci_rest_managed" "pod1_tep":
│    1: resource "aci_rest_managed" "pod1_tep" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aci_v2.10.1.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 15 [running]:
github.com/terraform-providers/terraform-provider-aci/aci.getAciRestManaged(0xc000555fe0?, 0x1d1cae0?, 0x1)
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_rest_managed.go:157 +0x102a
github.com/terraform-providers/terraform-provider-aci/aci.resourceAciRestManagedReadHelper({0x1d6522d?, 0x20?}, 0xc0008cd800, {0x1d1cae0, 0xc00050a540}, 0x1)
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_rest_managed.go:190 +0x1d1
github.com/terraform-providers/terraform-provider-aci/aci.resourceAciRestManagedUpdate({0x1f05d68, 0xc0004d0a20}, 0xc0008cd800, {0x1d1cae0, 0xc00050a540})
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_rest_managed.go:220 +0x265
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0000cbdc0, {0x1f05da0, 0xc00094cc90}, 0xd?, {0x1d1cae0, 0xc00050a540})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000cbdc0, {0x1f05da0, 0xc00094cc90}, 0xc0004d3790, 0xc0008cd680, {0x1d1cae0, 0xc00050a540})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000d2280, {0x1f05da0?, 0xc0006abc50?}, 0xc0004e2770)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1ce3c20?, 0xc0000d2280}, {0x1f05da0, 0xc0006abc50}, 0xc0004e2700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f6000, {0x1f08d60, 0xc0006a8000}, 0xc00058b440, 0xc00060c330, 0x26dea20, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000f6000, {0x1f08d60, 0xc0006a8000}, 0xc00058b440, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-aci_v2.10.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior

Panic

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Resource run is able to run without the child block, to just create the pod

### References

* #0000

**Comment by akinross** [comment]
Hi @stlarsen-dk,

Thank you for raising the issue. I will label this as bug and add to the todo list, but we would need to determine if this is already fixed in currently made changes to the aci_rest_managed resource https://github.com/CiscoDevNet/terraform-provider-aci/pull/1100 which is merged to master but not yet released.

As a temporary workaround, could you try to configure the child as a separate resource?

Kind regards

**Comment by stlarsen-dk** [comment]
Hi @akinross 
Thanks for quick reply

When creating the object using the same method 
resource "aci_rest_managed" "pod1_child" {
  dn         = "uni/controller/setuppol/setupp-1/extrtpodsubnet-[${var.pod1_ext_tep}]"
  class_name = "fabricExtRoutablePodSubnet"
  content = {
    pool = var.pod1_ext_tep
    annotation = "orchestrator:terraform"
  }
}

the object is created without any problem

**Comment by akinross** [comment]
Ok good to hear, I suspect this will be fixed with that PR previously mentioned but we would need to test with new release to be sure.

**Comment by samiib** [comment]
This #1113 PR has enhancements that should fix the above issue. However, adding dn in child object isn't necessary.
