### ISSUE TITLE
ipDPLearning for fvSubnet missing

### ISSUE THREAD

**Issue by mfr-6** [CiscoDevNet/terraform-provider-aci#1109]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've noticed that aci_subnet does not have argument called "ipDPLearning". Thanks to that option we can control Data Plane Learning on a Subnet level. 

This can be configured using aci_rest, but it would be nice having this as a "native" argument under aci_subnet. APIC API itself support this under fvSubnet so it shouldn't be a really problem to implement this. 

```hcl
resource "aci_rest" "ip_learning" {
    path = "/api/node/mo/uni/tn-test-tenant/ap-test-app/epg-test-epg-0/subnet-[10.10.10.110/32].json"
    class_name = "fvSubnet"
    content = {
        "ipDPLearning": "disabled"
    }
    depends_on = [
        aci_subnet.epg_subnet
    ]
}
```

### Affected Resource(s) + ACI Class(es):

* aci_subnet - fv:Subnet

### APIC version and APIC Platform

* V 5.2(2f) - onprem

### Potential Terraform Configuration

```hcl
    resource "aci_subnet" "foosubnet" {
        parent_dn          = aci_bridge_domain.bd_for_subnet.id
        description        = "subnet"
        ip                 = "10.0.3.28/27"
        annotation         = "tag_subnet"
        ctrl               = ["querier", "nd"]
        name_alias         = "alias_subnet"
        preferred          = "no"
        scope              = ["private", "shared"]
        virtual            = "yes"
        dataplane_learning = "disabled" <----- new argument
    }
```
### References

* #0000

**Comment by mfr-6** [comment]
If there are no objection for implementing it, I can take care of this.

**Comment by lindie1337** [comment]
I really hope this can be implemented as soon as possible.
We are building a new medium-large sized fabric, and we've managed everything without any rest resource blocks so far. 
I'd just really like to keep it that way. 

If I remove the rest resource block as posed by user mfr-6, it destroys the whole subnet, rather than the content within.
I'd rather have the built-in way to set the learning  parameter, before we just decide to manage subnets entirely, with a rest resource block.

**Comment by mfr-6** [comment]
Hi @lindie1337 

Thank you for giving your feedback. I'm going to provide my updates to PR opened, so soon I hope we'll be able to release this (most of the things are now on me, projects I'm involved in are extremely time consuming, sorry for delays).

In regards to rest block you've mentioned - I'd suggest to keep this block always, no matter which DP Learning setting you set and treat it as integral part of subnet, but of course this will not be needed if this feature will be implemented.

**Comment by lindie1337** [comment]
Hey @mfr-6 
Thanks very much for replying!! :) 

I truly recognize the part about projects that are time-consuming!
I've chosen to keep the learning option set via the GUI, it is only 3 subnets on which I need it disabled on, and Terraform of course ignores it/sees no config drift.

Then, when the day arrives that the feature is available, through the provider, I will correct the configuration :) no sweat!
