### ISSUE TITLE
Documentation: Display resources in alphabetical order.

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#111]
Sort resources in alphabetical order in the documentation.

Nic

**Comment by pradeepnnv** [comment]
Is it enough to fix the order in this page? https://github.com/terraform-providers/terraform-provider-aci/blob/master/website/docs/index.html.markdown

Can I work on this issue?

**Comment by nkatarmal-crest** [comment]
@pradeepnnv I have fixed this issue in the latest version of provider. However you will need to arrange the ordering in the website/aci.erb file.

**Comment by pradeepnnv** [comment]
Thanks @nkatarmal-crest.
