### ISSUE TITLE
imported leaf aci_fabric_node_member can't be used

### ISSUE THREAD

**Issue by bardahlm** [CiscoDevNet/terraform-provider-aci#1116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.7

### APIC version and APIC Platform

* V 5.2(6e) on-prem

### Affected Resource(s)

* aci_fabric_node_member

### Terraform Configuration Files

```hcl
locals {
  switches = {
    leaf1301 = {
      serial        = "FDO123456"
      node_id       = 1301
      pod_id        = 1
      role          = "leaf"
      oob_ipv4_addr = "10.10.21.131/24"
      oob_ipv4_gw   = "10.10.21.1"
    }
  }
}

resource "aci_fabric_node_member" "fabricnodes" {
  for_each = local.switches
  name     = each.key
  serial   = each.value.serial
  node_id  = each.value.node_id
  pod_id   = each.value.pod_id
  role     = each.value.role
}

import {
  to       = aci_fabric_node_member.fabricnodes["leaf1301"]
  id       = "uni/controller/nodeidentpol/nodep-FDO123456"
  provider = aci
}

```

### Expected Behavior

Resource should be imported and no changes should be required

### Actual Behavior

Plan looks OK:

```
# aci_fabric_node_member.fabricnodes["leaf1301"] will be updated in-place
  # (imported from "uni/controller/nodeidentpol/nodep-FDO123456")
  ~ resource "aci_fabric_node_member" "fabricnodes" {
        ext_pool_id = "0"
        fabric_id   = "1"
        id          = "uni/controller/nodeidentpol/nodep-FDO123456"
        name        = "leaf1301"
        node_id     = "1301"
        node_type   = "unspecified"
        pod_id      = "1"
      ~ role        = "unspecified" -> "leaf"
        serial      = "FDO123456"
    }
```
Import succeeded but apply failed:
```
│ Error: Create-only and naming props cannot be modified after creation, class=fabricNodeIdentP, prop=role
│ 
│   with aci_fabric_node_member.fabricnodes["leaf1301"],
│   on main.tf line 224, in resource "aci_fabric_node_member" "fabricnodes":
│  224: resource "aci_fabric_node_member" "fabricnodes" {
```
Apparently "role" is "unspecified" even though "leaf" is selected in the GUI.

### Steps to Reproduce

1. Add leaf switch to fabric using GUI
2. Create code that imports and configures the switch

### References

* #0000

**Comment by bardahlm** [comment]
Workaround: Specify imported leaf switches with role = "unspecifed"

**Comment by akinross** [comment]
Hi @bardahlm,

Thank you for raising the issue, see you have already created a "workaround" for you desired behaviour. What is the output on the apic when you look at the model? Is this role set to "unspecified"?

Kind regards,

Akini

**Comment by akinross** [comment]
Hi @bardahlm,

The import function reads this role and set this to state, and thus when you specify the role as leaf it detects it as a change. So from the resource point of view this seems to be working as expected. How did you configure and what did you set in UI exactly? Do you have any more information on the process you followed?

Kind regards,

Akini

**Comment by bardahlm** [comment]
Switches was added to the fabric using the apic web GUI, specifying role as "leaf".

![image](https://github.com/CiscoDevNet/terraform-provider-aci/assets/20773444/98c92f80-c603-4c35-a9a4-4674f7c6adba)

So there is a mismatch between the GUI and the API model.

**Comment by akinross** [comment]
Ok thanks for sharing, I would need to further investigate will get to back to you when I find some more information.

**Comment by akinross** [comment]
Hi @bardahlm,

Considering your ACI version I suspect you are hitting the following UI bug: https://bst.cisco.com/bugsearch/bug/CSCwf10521.

**Comment by akinross** [comment]
Hi @bardahlm, 

I have created a PR to destroy the resource and recreate the resource when for those resources that hit the error: "Create-only and naming props cannot be modified after creation". This would allow to use the apply command, as if you are running a terraform destroy command followed by a terraform apply to create a object. This will not fix the UI issue, but would allow for the attributes to be changed via the terraform apply command.

**Comment by bardahlm** [comment]
Thank you for investigating. Will the destroy and recreate process cause downtime?

**Comment by akinross** [comment]
I assume it does, but would need to verify if this is indeed the case. Will get back to you when I know more.

**Comment by akinross** [comment]
Hi @bardahlm, I had a look at this and the destroy process is only allowed when the device is decommissioned. You should see an error message as follows when trying to remove fabricIdentP object that is commissioned:

```
"error": {
    "attributes": {
        "code": "107",
        "text": "Can't remove node identity policy - Node <NODE NAME> is already discovered. Please decommission first."
    }
} 
```
