### ISSUE TITLE
aci_interface_config is not useable in 5.2(6e)

### ISSUE THREAD

**Issue by JC1231231** [CiscoDevNet/terraform-provider-aci#1119]
Trying to understand what port type with value "access", "fabric" has impact to existing deployment. Tested a little bit on sandbox which is 6.x it works. Tried to import existing configuration in terraform seems like that it is not possible to use in 5.2(6e)
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/interface_config#port_type

The document says 
"Manages ACI Access and Fabric Ports is only supported for ACI 5.2(5)+"

I use object browser in 6.x, I see under uni/infra or uni/fabric there is "infraPortConfig"
do the same search in 5.2(6e) there is no such thing.

Wondering is it actually supported in 5.2(6e) 
I also used uni/fabric/portconfnode-{node-id}-card-{card-id}-port-{port-id}-sub-{sub-id} and uni/infra/portconfnode-{node-id}-card-{card-id}-port-{port-id}-sub-{sub-id} in the object browser. I got result in 6.x but not in 5.2(6e).

**Comment by JC1231231** [comment]
<img width="1004" alt="infraportconfig" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/119866686/bc8559a7-3628-45d4-a474-3142158a0038">
<img width="984" alt="infraportconfig2" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/119866686/b7057e47-38a4-4b47-a036-9499911919cf">

**Comment by akinross** [comment]
Hi @JC1231231,

Thank you for highlighting this. I had a quick look in a environment which I have running (5.2(7f)) and there I do see the infraPortConfig class. I would need to verify in which version it got introduced. Will get back to you when I have some additional information.

**Comment by akinross** [comment]
Hi @JC1231231,

I just had a look on a 5.2(5c) version and also there I see the class in the model docs, and am able to configure it and then it is visible in Visore also. Could you try configuring the class in your setup?

**Comment by JC1231231** [comment]
Hi @akinross,
Thanks for pointing it out. I happened to have a 5.2(7) in a test lab. I use GUI to verify. I noticed that this is a new way to configure port in the later versions. The following link says after 6.0. But seems 5.2(7) and 5.2(5c) has this new feature. But not int 5.2(6e). 
In 5.2(7) I configured access port from the old way. There is no such infraPortConfig object. However after I configured this with the new way (allow me to call it this way) the object showed up as you mentioned. 

We can surely test directly with terraform and use that resource, I believed we tried import first. There are objects created previously with the "old way". I am not sure this will work with terraform import?

https://learnduty.com/cisco-aci/cisco-aci-6-0-new-interface-configuration-explained-and-example/

<img width="763" alt="port526-new" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/119866686/9c39e59d-fbf4-4ae0-8102-51510d59c850">

<img width="799" alt="interface 527" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/119866686/4a6d8556-e49d-4fde-99fc-85df2b90cfe3">
<img width="1022" alt="new configuration way" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/119866686/ed341fcc-6217-4d9a-b67d-21e7e1f7940a">

I mean
Old way : via fabric-access policies
New way: via configure fabric-inventory

**Comment by akinross** [comment]
@JC1231231,

The objects would need to be migrated first when configured in the "old" way, see Migrating Interfaces From the Selector and Profile to Interface Configuration Using the GUI in the [configuration guide for 6.0](https://www.cisco.com/c/en/us/td/docs/dcn/aci/apic/6x/l2-configuration/cisco-apic-layer-2-networking-configuration-guide-60x/access-interfaces-60x.html)

For further reference and scenarios of 5.2.7 please also refer to the following configuration guide:

https://www.cisco.com/c/en/us/td/docs/dcn/aci/apic/5x/layer-2-configuration/cisco-apic-layer-2-networking-configuration-guide-52x/access-interfaces-52x.html

**Comment by JC1231231** [comment]
And the scary part is I configured Leaf interface profile in the "old way", then I configured the same port with the "new way". It override my previous configuration  by deleting the previous and create new. Not sure my observation is correct.
My previous configured L1101-LeafIP was deleted and a system-port-profile-node-1101 is created.  Correct me if I am wrong.

<img width="969" alt="delete" src="https://github.com/CiscoDevNet/terraform-provider-aci/assets/119866686/6aad013d-cf5c-4aa5-b8f3-f33d180b29ed">

**Comment by akinross** [comment]
@JC1231231,

In the configuration guide the following is mentioned:

If you configure an interface using the interface configuration option and you previously configured the interface with profiles and selectors, the Cisco APIC automatically removes the interface from the existing profiles and moves the interface to the system-generated profiles seamlessly. If the pre-existing switch and interface profiles contain other interfaces, the Cisco APIC does not delete them; you can keep using them in the traditional way. If the pre-existing profiles no longer contain any interfaces, the Cisco APIC automatically removes those profiles because they are no longer needed.

**Comment by JC1231231** [comment]
as per the documentation of 6.0, 
"The Cisco ACI 6.0(1) release adds the "per-port configuration" configuration option (also known as the "interface configuration" or infraPortConfig, which is the name of the object for this configuration) that simplifies the interface configuration. "

The question is this is a feature introduced in 6.0. Has it anything to say with aci_interface_config resource? I see a strong connection between this.
And when is this actually introduced? We at least see this in 5.2(7) but not 5.2(6e)
