### ISSUE TITLE
datasource of aci_interface_config doesn't provide output all parameters are null

### ISSUE THREAD

**Issue by micronemo** [CiscoDevNet/terraform-provider-aci#1153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V 6.0(2h) 

### Affected Resource(s)

* aci_interface_config

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
datasource of aci_interface_config provides a output 

### Actual Behavior

datasource of aci_interface_config doesn't provide output all parameters are null
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by akinross** [comment]
Hi @micronemo,

Could you provide a bit more details on the what you did, and or provide config used and logs. I just did a test on the same version and see that state is populated as expected:

**Comment by micronemo** [comment]
data "aci_interface_config" "test" {
  interface = "1/1"
  node      = 101
}

output "pippo" {
  value = data.aci_interface_config.test
}

  + pippo = {
      + admin_state                      = null
      + annotation                       = null
      + breakout                         = null
      + description                      = null
      + id                               = null
      + interface                        = null
      + name_alias                       = null
      + node                             = null
      + operational_associated_group     = null
      + operational_associated_sub_group = null
      + pc_member                        = null
      + pc_port_dn                       = null
      + policy_group                     = null
      + port_dn                          = null
      + port_type                        = null
      + role                             = null
    }
    ll parameters are null

**Comment by akinross** [comment]
Hi @micronemo,

Could you please provide the logs with TF_LOG set to TRACE? See link https://developer.hashicorp.com/terraform/internals/debugging with additional information on debugging.

Could you also provide me the configuration as present on the apic?

What is the port type of the interface you are trying get the information from access or fabric?

**Comment by akinross** [comment]
Hi @micronemo, could you please provide us the requested information so I can assist you further with your issue?

**Comment by akinross** [comment]
Hi @micronemo, did you get a chance to look at the comments?

**Comment by micronemo** [comment]
thanks i update terraform and i try again now works thanks very mauch

**Comment by micronemo** [comment]
i update terraform and i try again, now works thanks very much

**Comment by akinross** [comment]
Hi @micronemo,

I have set this issue back to reviewer approved, because I have attached a PR to raise an error for when object is not found. This one is currently still in our approval process until it can be merged into master.
