### ISSUE TITLE
Enhancement: allow copy service configuration in resource/datasource aci_function_node

### ISSUE THREAD

**Issue by micronemo** [CiscoDevNet/terraform-provider-aci#1161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* aci_aci_6.0(2h)

### Terraform Configuration Files

resource "aci_function_node" "local" {
  l4_l7_service_graph_template_dn = aci_l4_l7_service_graph_template.local.id
  name = "sonda"
  func_type = "None"
  is_copy = "yes"
   managed = "no"
  relation_vns_rs_node_to_l_dev   = aci_l4_l7_device.Localname.id
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
i want create a copy service so i set  is_copy = "yes" but this doesn't create the child class vnsAbsFuncConn
that i must create with 

resource "aci_rest_managed" "vnsAbsFuncConn" {
  class_name = "vnsAbsFuncConn"
  dn         = "${aci_function_node.local.id}/AbsFConn-copy"
  content = {
    name = "copy"
  }
}

but create the function node provide and consumer that i don't want

					{
						"vnsAbsNode": {
							"attributes": {
								"annotation": "orchestrator:terraform",
								"descr": "",
								"funcTemplateType": "OTHER",
								"funcType": "None",
								"isCopy": "yes",
								"managed": "no",
								"name": "sonda",
								"nameAlias": "",
								"ownerKey": "",
								"ownerTag": "",
								"routingMode": "unspecified",
								"sequenceNumber": "0",
								"shareEncap": "no",
								"userdom": ":all:"
							},
							"children": [
								{
									"vnsRsNodeToLDev": {
										"attributes": {
											"annotation": "orchestrator:terraform",
											"tDn": "uni/tn-test2/lDevVip-NOME",
											"userdom": ":all:"
										}
									}
								},
								{
									"vnsAbsFuncConn": {   <-------------- creates this that shouldn't be there
										"attributes": {
											"annotation": "",
											"attNotify": "no",
											"connType": "none",
											"descr": "",
											"deviceLIfName": "",
											"name": "provider",
											"nameAlias": "",
											"ownerKey": "",
											"ownerTag": "",
											"userdom": ":all:"
										}
									}
								},
								{
									"vnsAbsFuncConn": {   <------ does not create this that should be there instead
										"attributes": {
											"annotation": "orchestrator:terraform",
											"attNotify": "no",
											"connType": "none",
											"descr": "",
											"deviceLIfName": "",
											"name": "copy",
											"nameAlias": "",
											"ownerKey": "",
											"ownerTag": "",
											"userdom": ":all:"
										}
									}
								},
								{
									"vnsAbsFuncConn": { <-------------- creates this that shouldn't be there
										"attributes": {
											"annotation": "",
											"attNotify": "no",
											"connType": "none",
											"descr": "",
											"deviceLIfName": "",
											"name": "consumer",
											"nameAlias": "",
											"ownerKey": "",
											"ownerTag": "",
											"userdom": ":all:"
										}
									}
								}
							]
						}
					},

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by akinross** [comment]
For person working on this issue, see reference: https://www.cisco.com/c/en/us/td/docs/dcn/aci/apic/6x/l4-l7-configuration/cisco-apic-layer-4-to-layer-7-services-deployment-guide-60x/configuring-copy-services-60x.html

The current configuration should be pushed when copy is enabled on vnsAbsNode class.

```
<vnsAbsNode descr="" funcTemplateType="OTHER" funcType="None" isCopy="yes" managed="no"
      name="CP1" ownerKey="" ownerTag="" routingMode="unspecified" sequenceNumber="0"
      shareEncap="no">
        <vnsAbsFuncConn attNotify="no" descr="" name="copy" ownerKey="" ownerTag=""/>
        <vnsRsNodeToLDev tDn="uni/tn-t22/lDevVip-copy0"/>
    </vnsAbsNode>
```

Verify document for any other potential updates to the resource.

**Comment by micronemo** [comment]
Hi @akinross 
temporary solution:
resource "aci_rest_managed" "vnsAbsNode" {
  class_name = "vnsAbsNode"
  dn         = "${aci_l4_l7_service_graph_template.local.id}/AbsNode-sonda"
  content = {
    name     = "sonda"
    funcType = "None"
    isCopy   = "yes"
    managed  = "no"
  }
}

resource "aci_rest_managed" "vnsRsNodeToLDev" {
  class_name = "vnsRsNodeToLDev"
  dn         = "${aci_rest_managed.vnsAbsNode.dn}/rsNodeToLDev"
  content = {
    tDn = aci_l4_l7_device.Localname.id
  }
}

resource "aci_rest_managed" "vnsAbsFuncConn" {
  class_name = "vnsAbsFuncConn"
  dn         = "${aci_rest_managed.vnsAbsNode.dn}/AbsFConn-copy"
  content = {
    name = "copy"
  }
}

**Comment by micronemo** [comment]
Hi @akinross 
to complete the configuration i add:

resource "aci_connection" "local" {
  l4_l7_service_graph_template_dn      = aci_l4_l7_service_graph_template.local.id
  name                                                  = "C1"
  relation_vns_rs_abs_connection_conns = [aci_l4_l7_service_graph_template.local.term_prov_dn, aci_l4_l7_service_graph_template.local.term_cons_dn]
  relation_vns_rs_abs_copy_connection  = [aci_rest_managed.vnsAbsFuncConn.dn] <- this is the previous missing object
}

**Comment by micronemo** [comment]
Hi 
i don't understand because the creation of 
resource "aci_rest_managed" "vnsAbsFuncConn" {
  class_name = "vnsAbsFuncConn"
  dn         = "${aci_function_node.Localname.id}/AbsFConn-copy"
  content = {
    name = "copy"
  }
}
is not fixed with a resource inside terraform

**Comment by shrsr** [comment]
@micronemo The resource back-end code for "aci_function_node" has been modified with the following:
```
if vnsAbsNodeAttr.IsCopy == "yes" {
		vnsAbsFuncConnAttr.DeviceLIfName = ""
		vnsAbsFuncConn := models.NewFunctionConnector(fmt.Sprintf("AbsFConn-%s", "copy"), vnsAbsNode.DistinguishedName, "", vnsAbsFuncConnAttr)
		err = aciClient.Save(vnsAbsFuncConn)
		if err != nil {
			return diag.FromErr(err)
		}
		d.Set("conn_copy_dn", vnsAbsFuncConn.DistinguishedName)
	}
```
You should be able to use `is_copy = "yes"` as seen below to create a copy node -

```
resource "aci_function_node" "tf_copy1" {
  l4_l7_service_graph_template_dn = aci_l4_l7_service_graph_template.tf_sg_4.id
  name                            = "CP1"
  func_template_type              = "OTHER"
  is_copy                         = "yes"
  managed                         = "no"
  func_type                       = "None"
  relation_vns_rs_node_to_l_dev   = aci_l4_l7_device.tf_device3.id
}
```
Please let us know if this works.

**Comment by micronemo** [comment]
@shrsr 
if the resource vnsAbsFuncConn is in back-end how i can complete this: (see <<<<<<<<<<<<<)

esource "aci_function_node" "Localname" {
  l4_l7_service_graph_template_dn = aci_l4_l7_service_graph_template.Localname.id
  name                            = "sonda"
  func_type                       = "None"
  is_copy                         = "yes"
  managed                         = "no"
  sequence_number                 = "0"
  relation_vns_rs_node_to_l_dev   = aci_l4_l7_device.Localname.id
}
-------------   not exist -------------------------------
resource "aci_rest_managed" "vnsAbsFuncConn" {
  class_name = "vnsAbsFuncConn"
  dn         = "${aci_function_node.Localname.id}/AbsFConn-copy"
  content = {
    name = "copy"
  }
}
-----------------------------------------------------------

resource "aci_connection" "local" {
  l4_l7_service_graph_template_dn      = aci_l4_l7_service_graph_template.Localname.id
  name                                 = "C1"
  relation_vns_rs_abs_connection_conns = [aci_l4_l7_service_graph_template.Localname.term_prov_dn, aci_l4_l7_service_graph_template.Localname.term_cons_dn]
  relation_vns_rs_abs_copy_connection  = [aci_rest_managed.vnsAbsFuncConn.dn]         <<<<<<<<<<<<<<<<<<<<<<<<
}

**Comment by shrsr** [comment]
@micronemo A new attribute called `conn_copy_dn` is exposed to retrieve the DN of the copy node. `aci_rest_managed.vnsAbsFuncConn.dn` would be replaced by `aci_function_node.Localname.conn_copy_dn`. Your configuration would look like this:
```
resource "aci_function_node" "Localname" {
  l4_l7_service_graph_template_dn = aci_l4_l7_service_graph_template.Localname.id
  name = "sonda"
  func_type = "None"
  is_copy = "yes"
  managed = "no"
  sequence_number = "0"
  relation_vns_rs_node_to_l_dev = aci_l4_l7_device.Localname.id
}

resource "aci_connection" "local" {
  l4_l7_service_graph_template_dn = aci_l4_l7_service_graph_template.Localname.id
  name = "C1"
  relation_vns_rs_abs_connection_conns = [aci_l4_l7_service_graph_template.Localname.term_prov_dn, 
  aci_l4_l7_service_graph_template.Localname.term_cons_dn]
  relation_vns_rs_abs_copy_connection = [aci_function_node.Localname.conn_copy_dn]
}
```
Please let us know once you've tried it.

**Comment by micronemo** [comment]
hi @shrsr 
ok but conn_copy_dn is not presemt of official guide of this resourse

**Comment by shrsr** [comment]
@micronemo It was added to the docs after the latest release:
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/function_node
