### ISSUE TITLE
anomalous behavior of aci_contract resource

### ISSUE THREAD

**Issue by micronemo** [CiscoDevNet/terraform-provider-aci#1162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)
aci_contract

* ACI 6.0(2h) 

### Terraform Configuration Files

```
resource "aci_contract" "local" {
  name                     = "any666"
  tenant_dn                = aci_tenant.local.id
  relation_vz_rs_graph_att = aci_l4_l7_service_graph_template.local.id
  filter {
    filter_name = "any999"
    filter_entry {
      filter_entry_name = "any1111"
      ether_t           = "ip"
    }
  }
```
it does not create the subject that links the filter to the contract and therefore it does not work
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by akinross** [comment]
Hi @micronemo,

Did you try using the [aci_contract_subject](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/contract_subject), and [aci_contract_subject_filter](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/contract_subject_filter) resources?

**Comment by akinross** [comment]
Hi @micronemo,

Apologies for the confusing but the resource was not intended to configure the subject information. I think this was an attempt to simplify the configuration and decrease the amount of resources required for configuration. This however was never completed with subject, since separate resources were also already created. 

For now this is not something we will pursue in fixing, since it is already possible to configure with the other resources.

**Comment by micronemo** [comment]
@akinross 
it is not very clear the point of being able to configure filters and contract if there is no subject. the **relation_vz_rs_graph_att** parameter is proprietary to the subject so the contract macro configured like this is also unusable because i cannot combine it with other resources
so i have to use it only to be able to configure the contract name ?
just configure a subject with the same contract name with a permit and it would work

**Comment by akinross** [comment]
Hi @micronemo,

From the model documentation I see that `vzRsSubjGraphAtt` is the relationship that is attached with subject, the `vzRsGraphAtt` is attached to the contract itself. This is the relationship that is exposed in the contract resource.

Regarding your question yes the resource is used to configure the name, but also you can set prio, scope, dscp. Then you can reference the id of the resource as input for your subject resource, see the example in [aci_contract_subject](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/contract_subject)

**Comment by micronemo** [comment]
Hi @akinross 
this is a counterintuitive solution with a trick

resource "aci_contract" "local" {
  name      = "any666"
  tenant_dn = aci_tenant.local.id
  filter {
    filter_name = "any999"
    filter_entry {
      filter_entry_name = "any1111"
      ether_t           = "ip"
    }
  }
}

resource "aci_contract_subject" "local" {
  contract_dn                   = aci_contract.local.id
  name                          = "sbj-${aci_contract.local.name}"
  relation_vz_rs_subj_graph_att = aci_l4_l7_service_graph_template.local.id
}

resource "aci_contract_subject_filter" "local" {
  contract_subject_dn = aci_contract_subject.local.id
  filter_dn           = "${aci_tenant.local.id}/flt-${aci_contract.local.filter[0].filter_name}"
  action              = "permit"
}

**Comment by akinross** [comment]
Hi @micronemo,

I am not sure what you mean by counter intuitive with a trick, but this could work indeed. Pay attention when you are changing filter statements that your order of the existing filters does not change, else you might get into issues where you are referencing the wrong filter. This can be avoided by using the [aci_filter](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/filter) resource, because then you reference the actual resource directly.

**Comment by micronemo** [comment]
Hi @akinross 
as a counterintuitive solution I mean you have a contract the filters but you are missing the subject and aci_contract_subject_filter to tie it all together and you have to use values like "${aci_tenant.local.id}/flt-${aci_contract.local.filter[0].filter_name}"
the purpose was to use the macro inside aci_contract otherwise you can use the 4 resources:
aci_contract
aci_contract_subject
aci_contract_subject_filter  
aci_filter
if you want you can close this problem

**Comment by akinross** [comment]
Hi @micronemo,

Apologies for the confusion here. I will keep this issue open with label `wontfix` so other can see this thread in case they bump into similar issue.
