### ISSUE TITLE
Provider does not handle quotes in password

### ISSUE THREAD

**Issue by edudppaz** [CiscoDevNet/terraform-provider-aci#1180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v1.5.6

### APIC version and APIC Platform

* V 6.0(3e) on prem

### Affected Resource(s)

* All

### Terraform Configuration Files

```hcl
```

### Debug Output

```
err: incomplete node at line '6'. Please report this issue to the provider
developers.

Error: incomplete node at line '6'

Error: Creation of rest request failed
```

### Expected Behavior
Terraform properly logs into the apic

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

For me it seems like the issue is the go code not properly setting the whole password as a raw string and not scaping quotes , is only scaping backslashes:

```go
// Adding the follwing replace allows support for (1) Login Domains, where login is in the format of: apic#LOCAL\admin2
	// (2) escapes out the password to support scenarios where the user password includes backslashes
	escUserName := strings.ReplaceAll(c.username, `\`, `\\`)
	escPwd := strings.ReplaceAll(c.password, `\`, `\\`)
	body := []byte(fmt.Sprintf(authPayload, escUserName, escPwd))
```

So, when quotes are used on the password, the Go code cannot properly generate the json body for the authentication.

### References

* #0000

**Comment by akinross** [comment]
Hi @edudppaz, thank you for raising this bug, I have added it to the todo items.
