### ISSUE TITLE
Document Dependencies

### ISSUE THREAD

**Issue by Alexpf20210007** [CiscoDevNet/terraform-provider-aci#1188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When you create a bunch of resources using Terraform, the resources may or may not be created if the resources that they depend on have not been created. This causes not found errors when running the script. If I use Terraform depends_on, then I can get the script to run without error. I think that you should write the list of dependencies in the documentation to make it easier to write code.

**Comment by akinross** [comment]
Hi @Alexpf20210007,

Thank you for raising this issue and apologies for the inconvenience. A way to prevent this by leveraging data sources and using the id as input for the resources that require an (implicit) dependency. This way you would not need the depends on statement.

Furthermore we are currently in the progress of making improvements to the documentation for new resources which would provide more detailed information. See the following example of new resource documentation:

https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/external_management_network_instance_profile

In parallel we are investigating migration of existing resources to plugin framework. During this migration we shall also address the documentation.

**Comment by akinross** [comment]
Hi @Alexpf20210007,

I am closing this issue and referred to it in https://github.com/CiscoDevNet/terraform-provider-aci/issues/101 which is a generic detail add issue.

In case you have any follow up question please let us know.
