### ISSUE TITLE
Import for resource `aci_rest_managed` considers _unmanaged_ keys in the `content`  attribute

### ISSUE THREAD

**Issue by jgomezve** [CiscoDevNet/terraform-provider-aci#1190]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* 1.7.5
### APIC version and APIC Platform

* 6.0.5h

### Affected Resource(s)

* aci_rest_managed

### Terraform Configuration Files

```hcl
resource "aci_rest_managed" "fvCtx" {
  dn         = "uni/tn-TENANT-EXAMPLE/ctx-VRF1"
  class_name = "fvCtx"
  content = {
    "descr"               = ""
    "ipDataPlaneLearning" = "enabled"
    "name"                = "VRF1"
    "nameAlias"           = ""
    "pcEnfDir"            = "ingress"
    "pcEnfPref"           = "enforced"
  }
}

import {
  to = aci_rest_managed.fvCtx
  id = "fvCtx:uni/tn-TENANT-EXAMPLE/ctx-VRF1"
}
```

### Debug Output

```console
aci_rest_managed.fvCtx: Preparing import... [id=fvCtx:uni/tn-TENANT-EXAMPLE/ctx-VRF1]
aci_rest_managed.fvCtx: Refreshing state... [id=uni/tn-TENANT-EXAMPLE/ctx-VRF1]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aci_rest_managed.fvCtx will be updated in-place
  # (imported from "fvCtx:uni/tn-TENANT-EXAMPLE/ctx-VRF1")
  ~ resource "aci_rest_managed" "fvCtx" {
        annotation = "orchestrator:terraform"
        class_name = "fvCtx"
      ~ content    = {
          - "bdEnforcedEnable"    = "no" -> null
            "descr"               = ""
            "ipDataPlaneLearning" = "enabled"
          - "knwMcastAct"         = "permit" -> null
            "name"                = "VRF1"
            "nameAlias"           = ""
          - "ownerKey"            = "" -> null
          - "ownerTag"            = "" -> null
            "pcEnfDir"            = "ingress"
            "pcEnfPref"           = "enforced"
          - "userdom"             = ":all:" -> null
          - "vrfIndex"            = "0" -> null
        }
        dn         = "uni/tn-TENANT-EXAMPLE/ctx-VRF1"
        id         = "uni/tn-TENANT-EXAMPLE/ctx-VRF1"
    }

Plan: 1 to import, 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

Terraform should have imported the resources with the keys defined in the attribute `content`

### Actual Behavior

Terraform considers keys that exist on the APIC but that are not defined in the resource block. As an example in the output above the key `ownerKey` exists on the APIC but is not defined in the resource block

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This does not happen in the provider version 2.11.x

**Comment by akinross** [comment]
Hi @jgomezve,

The import operation will read all attributes and will then compare this to what is provided in the config. If an attribute is not included in the config but was included in the GET response, the plan will show a -> null operation, which will trigger a POST, though anything with null will not be included in the payload and therefore will also not be changed.

Due to migration of terraform plugin framework migration we are subdued to more intense comparison checks between config / plan / state. We have looked into plan modification of the resource but this would lead to invalid plan errors.

If you do not want to see these changes reflected in your plan, you can specify the value from apic for those attributes in your config file like:

```
resource "aci_rest_managed" "fvCtx" {
  dn         = "uni/tn-TENANT-EXAMPLE/ctx-VRF1"
  class_name = "fvCtx"
  content = {
    "descr"               = ""
    "ipDataPlaneLearning" = "enabled"
    "name"                = "VRF1"
    "nameAlias"           = ""
    "pcEnfDir"            = "ingress"
    "pcEnfPref"           = "enforced"
    "bdEnforcedEnable"    = "no"
    "ownerKey"            = ""
    "ownerTag"            = ""
    "userdom"             = ":all:common:"
    "vrfIndex"            = "0"
    "knwMcastAct"         = "permit"
  }
}
```

Are you ok with closing the issue?

**Comment by jgomezve** [comment]
Thanks for the information @akinross . You can close the issue
