### ISSUE TITLE
tofu init: authentication signature from unknown issuer

### ISSUE THREAD

**Issue by tomvrugt** [CiscoDevNet/terraform-provider-aci#1198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
$ tofu -v
OpenTofu v1.6.2
on linux_amd64
```

### APIC version and APIC Platform

* V6.0-5h on-prem

### Affected Resource(s)

N/A

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aci = {
      source = "CiscoDevNet/aci"
    }
  }
}
```

### Expected Behavior
ACI provider is installable from OpenTofu registry

### Actual Behavior

Installing the ACI provider from OpenTofu registry fails. Please submit GPG public key to https://github.com/opentofu/registry.

### Steps to Reproduce

```bash
$tofu init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of ciscodevnet/aci...
- Installing ciscodevnet/aci v2.14.0...
╷
│ Error: Failed to install provider
│
│ Error while installing ciscodevnet/aci v2.14.0: authentication signature from unknown issuer
╵
```

### References

* #0000

**Comment by akinross** [comment]
Hi @tomvrugt, 

Thanks for rising the issue, we are currently already in the progress of looking into this. See also https://github.com/opentofu/registry/pull/390.

**Comment by tomvrugt** [comment]
@akinross Thanks for the speedy answer! I'll await the deplyment of opentofu/registry#390 then. Cheers!

**Comment by lhercot** [comment]
It actually has been merged with https://github.com/opentofu/registry/pull/394 as they had their automated submission did not allow to add but wanted to update the existing key but we uses different keys for different providers.

**Comment by tomvrugt** [comment]
Yes, it now works now! Thanks @akinross @lhercot ! Closing the issue
