### ISSUE TITLE
Cannot use custom port with aci_filter_entry resource

### ISSUE THREAD

**Issue by bestpath-gb** [CiscoDevNet/terraform-provider-aci#121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/terraform-providers/aci v0.4.0
```

### APIC version and APIC Platform

N/A. Validation error before any configuration is deployed.

### Affected Resource(s)

* aci_filter_entry

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=0.13.0"

  required_providers {
    aci = {
      source  = "terraform-providers/aci"
      version = "~> 0.4.0"
    }
  }
}

provider "aci" {
  username = "myusername"
  password = "mypassword"
  url      = "https://BestPathLabAPIC"
  insecure = true
}

resource "aci_tenant" "tenant" {
  name        = "BestPath"
}

resource "aci_filter" "filter" {
  tenant_dn = aci_tenant.tenant.id
  name      = "TCP-22-FILTER"
}

resource "aci_filter_entry" "filter_entry" {
  filter_dn   = aci_filter.filter.id
  name        = "TCP-22-FILTER-ENTRY"
  d_to_port   = "22"
  d_from_port = "22"
  ether_t     = "ip"
  prot        = "tcp"
}


```

### Expected Behavior

`terraform plan` should plan to create the tenant, filter and filter entry. `terraform apply` should deploy the configuration to the APIC and the resulting filter entry (`vzEntry`) should have `dFromPort` and `dToPort` attributes with a value of `22`, as was the case before the 0.4.0 update.

### Actual Behavior

`terraform plan` fails with the following validation error:

```
Error: expected d_from_port to be one of [unspecified ftpData smtp dns http pop3 https rtsp], got 22

  on main.tf line 28, in resource "aci_filter_entry" "filter_entry":
  28: resource "aci_filter_entry" "filter_entry" {



Error: expected d_to_port to be one of [unspecified ftpData smtp dns http pop3 https rtsp], got 22

  on main.tf line 28, in resource "aci_filter_entry" "filter_entry":
  28: resource "aci_filter_entry" "filter_entry" {
```

### Steps to Reproduce

1. `terraform plan`

**Comment by euphdk** [comment]
Same problem with `aci_lacp_policy`:

```
resource "aci_lacp_policy" "lacp-active" {
  name      = "LACP-Active"
  mode      = "active"
  ctrl      = "fast-sel-hot-stdby,graceful-conv,susp-individual" # It is possible to choose multiple here, but the new version only allow one.
  max_links = "16"
  min_links = "1"
}
```

**Comment by davemcdonnell** [comment]
+1 for this issue. I cant see how anyone could be using this module in production without being able to specify a port outside of "ftpData smtp dns http pop3 https rtsp".

**Comment by nkatarmal-crest** [comment]
@davemcdonnell, @bestpath-gb please use the latest version (0.4.1) which fixes the issue.

**Comment by bestpath-gb** [comment]
@nkatarmal-crest That's sorted the problem with `aci_filter_entry` resources. Thanks. The documentation needs updating with the new location of the provider but I can open a different issue for that.

@euphdk If v0.4.1 doesn't fix your problem with `aci_lacp_policy`, open a fresh issue.
