### ISSUE TITLE
file modules.yaml in cisco ACI nexus as code 

### ISSUE THREAD

**Issue by micronemo** [CiscoDevNet/terraform-provider-aci#1215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* aci_XXXXX

### Terraform Configuration Files

I would like to know in which folder I have to put the custom modules.yaml file since it only uses the one inside the .terraform folder which enables all the modules creating resources not required with the default setting. also I would like to know how the external bridge domains can be created since it seems to be an absent feature 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by akinross** [comment]
Hi @micronemo,

I am not sure what it is what you are trying to do from your description. 

This repository is for the ACI terraform provider and not Nexus as Code. Please refer to the documentation of NaC: https://developer.cisco.com/docs/nexus-as-code/introduction/#cisco-nexus-as-code.

In case the explanation on the webpage is not clear you could try raising the question on the GitHub page: https://github.com/netascode/terraform-aci-nac-aci

**Comment by micronemo** [comment]
thanks
