### ISSUE TITLE
useg epg creation

### ISSUE THREAD

**Issue by micronemo** [CiscoDevNet/terraform-provider-aci#1221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

how can I create a complete useg epg in the aci_application_epg resource by setting is_attr_based_epg = "yes" I create a useg but I can't create:
resource "aci_rest_managed" "fvCrtrn_ubuntu" {
   class_name = "fvCrtrn"
   dn = "${aci_application_epg.ubuntu_useg.id}/crtrn"
   content = {
     match = "any"
     name = "default"
     prev = "0"
     scope = "scope-bd"
   }
}

resource "aci_rest_managed" "fvVmAttr" {
   class_name = "fvVmAttr"
   dn = "${aci_rest_managed.fvCrtrn_ubuntu.dn}/vmattr-0"
   content = {
     operator = "startsWith"
     type = "vm-name"
     value = "ubuntu"
     name = "0"

Are there any resources on this?

### New or Affected Resource(s) + ACI Class(es):

* aci_XXXXX + fv:XXXX

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by shrsr** [comment]
@micronemo Thank you for opening this issue. I went through our provider and looks like the resource aci_application_epg doesn't allow an implicit creation of "fvCrtrn".
Our team will look into it and update the resource with the ability to create "fvCrtrn" and other missing objects.
