### ISSUE TITLE
Enhancement: Add Resource or attribute in aci_bridge_domain to configure Rogue Endpoint Exception list (DCNE-144)

### ISSUE THREAD

**Issue by dirkf98** [CiscoDevNet/terraform-provider-aci#1257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

it would be great if you could manage the Rogue Endpoint Exception list for a bridge domain through Terraform. Either as a specific resource or another attribute within ac_bridge_domain. That would be objects for the class fvRogueExceptionMac. In the GUI this can be configured in the respective bridge domain -> Advanced/Troubleshooting.
This exception list was introducted in 5.2.3.

### New or Affected Resource(s) + ACI Class(es):

Class fvRogueExceptionMac under fvBD

### APIC version and APIC Platform

* V 5.2.3 and on-prem

### Potential Terraform Configuration

```hcl
    resource "aci_bridge_domain" "foobridge_domain" {
        tenant_dn                   = aci_tenant.tenant_for_bd.id
        description                 = "from terraform"
        name                        = "demo_bd"
        rogue_mac_exceptions = ["xx:xx:xx:xx:xx:xx", "xx:xx:xx:xx:xx:yy"]
```

**Comment by akinross** [comment]
Hi @dirkf98,

Thank you for raising this issue, I will add it to the to do items. I am not sure this will be added to the resource itself but will likely be a separate resource since we typically only add relationship classes to the resource. Will be discussed with the team when it is assigned.

**Comment by dirkf98** [comment]
Hello @akinross,

thank you for the quick feedback. A separate resource would be perfectly fine for me.

Dirk

**Comment by akinross** [comment]
Hi @dirkf98,

You are welcome. Just additional information, currently we are working on migration to plugin framework of EPG similar as we did recently for ESG (merged to master but not released yet). After EPG, the likely next candidate will be BD. These should we non-breaking changes that include new functionality.
