### ISSUE TITLE
aci_lacp_policy doesn't accept more than one 'ctrl' property

### ISSUE THREAD

**Issue by euphdk** [CiscoDevNet/terraform-provider-aci#126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/ciscodevnet/aci v0.4.1
```

### APIC version and APIC Platform

* V 4.2(5k) ACI Simulator

### Affected Resource(s)

* aci_lacp_policy

### Terraform Configuration Files

```hcl
provider "aci" {
  username = "user"
  password = "pass"
  url      = "https://acisim/"
  insecure = true
  version  = "0.4.1"
}

resource "aci_lacp_policy" "lacp-active" {
  name      = "LACP-Active"
  mode      = "active"
  ctrl      = "fast-sel-hot-stdby,graceful-conv,susp-individual"
  max_links = "16"
  min_links = "1"
}

```

### Expected Behavior

The `ctrl` option isn't limited to one of the options provided, but can be list of multiple properties for the LAG. The example above works in < 0.4.0, but should come in that specific order if terraform should'n try to change it on every run.

### Actual Behavior

```
 $ terraform plan

Error: expected ctrl to be one of [symmetric-hash susp-individual graceful-conv load-defer fast-sel-hot-stdby], got fast-sel-hot-stdby,graceful-conv,susp-individual

  on test.tf line 18, in resource "aci_lacp_policy" "lacp-active":
  18: resource "aci_lacp_policy" "lacp-active" {

```
### Steps to Reproduce

1. `terraform plan`

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.

**Comment by euphdk** [comment]
It seems to work, but only after I did a `rm -rf terraform.tfstate .terraform/`. Before that I got a `Error: missing expected [`.

Don't know if it is related to #147 and #139 ?

**Comment by euphdk** [comment]
Saw the response in #147, so closing the issue as the original problem has been resolved.
