### ISSUE TITLE
Add Resource/Knob to enable TGW for a region and associate subnets for attachments

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-aci#134]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is need for an option to enable TGW under the resource "aci_cloud_context_profile" and associate cloud subnets for attachments on a specific region. 

```
resource "aci_cloud_context_profile" "ctx-vrf1-useast1" {
  tenant_dn                = aci_tenant.terraform_ten.id
  name                     = "ctx-vrf1-useast1"
  primary_cidr             = "172.11.0.0/16"
  region                   = "us-east-1"
  cloud_vendor             = "aws"
  relation_cloud_rs_to_ctx = aci_vrf.vrf1.id
}
```

### New or Affected Resource(s) + ACI Class(es):

aci_cloud_context_profile
aci_cloud_cidr_pool
aci_cloud_subnet

### APIC version and APIC Platform

5.0.2h on Cloud ACI for AWS. 

### Potential Terraform Configuration

Additional argument reference such as `Transit Gateway` = true or false. A data source to specify cloud subnets which would be associated to TGW. 

### References

https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/cloud_context_profile

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.

**Comment by marinalf** [comment]
I added the hub_network reference pointing to "uni/tn-infra/gwrouterp-default" and got the error below. Besides enabling TGW, we also need association to an existing hub network (defined during the first time setup) which I could not find an option for.

**Error: 
Relation target dn uni/tn-infra/gwrouterp-default not found**

```
resource "aci_cloud_context_profile" "ctx-vrf1-useast1" {
  tenant_dn                = aci_tenant.terraform_ten.id
  name                     = "ctx-vrf1-useast1"
  primary_cidr             = "172.11.0.0/16"
  region                   = "us-east-1"
  cloud_vendor             = "aws"
  relation_cloud_rs_to_ctx = aci_vrf.vrf1.id
  hub_network              = "uni/tn-infra/gwrouterp-default"
```
Updated code: https://github.com/marinalf/cloudaci-demo-terraform/blob/main/main.tf

**Comment by nkatarmal-crest** [comment]
@marinalf The dn you are using does not exist. That is why this error is thrown.

**Comment by marinalf** [comment]
Please, can you clarify your comment when you say the dn I am using does not exist? I am not sure which dn are you referring to, as I am using the exact sample code.

```
resource "aci_cloud_context_profile" "ctx-vrf1-useast1" {
  tenant_dn                = aci_tenant.terraform_ten.id
  name                     = "ctx-vrf1-useast1"
  primary_cidr             = "172.11.0.0/16"
  region                   = "us-east-1"
  cloud_vendor             = "aws"
  relation_cloud_rs_to_ctx = aci_vrf.vrf1.id
  hub_network              = "uni/tn-infra/gwrouterp-default"
```

<img width="717" alt="image" src="https://user-images.githubusercontent.com/12536683/99259434-041f7b00-27e8-11eb-9b72-9fb66c8a8d24.png">

- hub_network - (Optional) hub network Dn which enables Transit Gateway.

[https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/cloud_context_profile](url)

What else am I missing to enable TGW and associate to an existing hub1 network?


<img width="569" alt="image" src="https://user-images.githubusercontent.com/12536683/99260067-ebfc2b80-27e8-11eb-88ac-cfcec7b8c73c.png">

**Comment by nkatarmal-crest** [comment]
@marinalf this one, uni/tn-infra/gwrouterp-default

**Comment by marinalf** [comment]
ok, do you have a working example I can use that enables TGW and associate it to an existing Hub network?

**Comment by marinalf** [comment]
I fixed it by replacing "default" with "hub1", which is the name I used during initial setup. It would be great to have the documentation being more specific. 

```
resource "aci_cloud_context_profile" "ctx-vrf1-useast1" {
  tenant_dn                = aci_tenant.terraform_ten.id
  name                     = "ctx-vrf1-useast1"
  primary_cidr             = "172.11.0.0/16"
  region                   = "us-east-1"
  cloud_vendor             = "aws"
  relation_cloud_rs_to_ctx = aci_vrf.vrf1.id
  hub_network              = "uni/tn-infra/gwrouterp-hub1"

```

Thank you!

**Comment by nkatarmal-crest** [comment]
@marinalf since this issue has been fixed i am closing this thread. The documentation improvements are tracked in other issue.
