### ISSUE TITLE
Change terraform registry documentation to be searchable by the resource name

### ISSUE THREAD

**Issue by Bullenj01** [CiscoDevNet/terraform-provider-aci#136]
On the terraform registry, the searchable portion is based on class name which is not user friendly.  For example, if I just type domain in there it should pull up the aci_epg_to_domain resource as well as other resources for domain specific actions.  A person would have to figure out the class of the epg-domain relation first and search for that in this case fvrsdomatt

![image](https://user-images.githubusercontent.com/24844853/95248553-76fb0680-07e5-11eb-9b55-5718bf38f9d3.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.
