### ISSUE TITLE
aci_subnet scope only accepts one value

### ISSUE THREAD

**Issue by cpaggen** [CiscoDevNet/terraform-provider-aci#139]
If you try to set both public (advertised externally) and shared (shared between VRFs) in an aci_subnet resource, you get the following error: **expected scope to be one of [public private shared], got public shared**

The scope parameter should accept a list of strings, because it's possible for a BD subnet to be both public _and_ shared at the same time. Private and shared are accepted by the API. Private and public are mutually exclusive.

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.

**Comment by FrederikSuijs** [comment]
I just tried.

    bd_test.tf line 17, in resource "aci_subnet" "demosubnet":
      17:   scope       = "public,shared"
      
    Inappropriate value for attribute "scope": list of string required

It seems at least a list of strings is expected now.
However, now running into another error:

    Error: missing expected [

This is also reported in #147

**Comment by FrederikSuijs** [comment]
as @euphdk mentioned, starting from scratch with a new .tfstate does seem to work.
I quickly tried targetting https://sandboxapicdc.cisco.com/ and the bug seems resolved.

**Comment by thomasnoppe** [comment]
I am also hitting this issue.
Starting from scratch in a working fabric is not an option ...

**Comment by FrederikSuijs** [comment]
I did some testing and it seems you need to update the terraform.tfstate to comply to the new structure. You can use your favorite find/replace tool and apply something similar to this regex:
[https://regex101.com/r/1fTlrL/2](https://regex101.com/r/1fTlrL/2)

**Comment by thomasnoppe** [comment]
Thx! I will give it a try.

**Comment by nkatarmal-crest** [comment]
Hey @FrederikSuijs , @thomasnoppe please don't use regex to do it. You can refer to this comment and fix your issue. https://github.com/CiscoDevNet/terraform-provider-aci/issues/147#issuecomment-720274320
