### ISSUE TITLE
Add fvCep as data source

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#140]
Please add `fvCep` as a data source. As `fvCep` tdn represents the full path of the endpoint, it allows the user to derive a lot of relevant information, such as EPG, IP address, MAC address, Tenant, etc.
This is also required in the context of Consul NIA integration.

Nic

**Comment by nkatarmal-crest** [comment]
@vfiftyfive I have added this data source in v0.5.1. Please try that out and let me know if i need to add anything else.
