### ISSUE TITLE
tags/annotations cause error or don't get created

### ISSUE THREAD

**Issue by tigelane** [CiscoDevNet/terraform-provider-aci#152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/ciscodevnet/aci v0.5.0
```

### APIC version and APIC Platform

* https://sandboxapicdc.cisco.com/    4.1(1k)
* 4.2(2f)

### Affected Resource(s)

* Many - Tenant, AP, VRF/CTX, Bridge Domain
* Seems like anything that uses Annotations

### Terraform Configuration Files

```
resource "aci_tenant" "tenant" {
  name        = "tagged_tenant"
  annotation  = "atag"
}
resource "aci_vrf" "vrf1" {
  tenant_dn   = aci_tenant.tenant.id
  name        = "single_tagged_vrf"
  annotation  = "atag"
}
resource "aci_application_profile" "ap" {
  tenant_dn   = aci_tenant.tenant.id
  name        = "single_tagged_ap"
  annotation  = "atag"
}
resource "aci_bridge_domain" "bd" {
  tenant_dn   = aci_tenant.tenant.id
  name        = "double_tagged_bd"
  annotation  = "atag,btag"
}
```

### Expected Behavior

* `tenant`, `vrf1`, `ap` to have a single annotation `atag` on it once created.
* `bd` to have two annotations on it once created `atag` and `btag`.

### Actual Behavior

* `tenant`, `vrf1`, `ap` are created, but no annotations are applied.
* `bd` is not created and errors (additional object with two tags error)

```
aci_tenant.tenant: Creating...
aci_tenant.tenant: Creation complete after 9s [id=uni/tn-tagged_tenant]
aci_application_profile.ap: Creating...
aci_vrf.vrf1: Creating...
aci_bridge_domain.bd: Creating...
aci_application_profile.ap: Creation complete after 1s [id=uni/tn-tagged_tenant/ap-single_tagged_ap]
aci_vrf.vrf1: Creation complete after 6s [id=uni/tn-tagged_tenant/ctx-single_tagged_vrf]

Error: property annotation of BD-double_tagged_bd failed validation for value 'atag,btag'

  on main.tf line 23, in resource "aci_bridge_domain" "bd":
  23: resource "aci_bridge_domain" "bd" {

```

### Steps to Reproduce

1. `terraform apply`
2. Go look at created objects with single annotation or see error if you tried to add two annotations.

### Important Factoids

Not that I can think of.

**Comment by nkatarmal-crest** [comment]
@tigelane APIC API doesn't allow to pass multiple annotations that way. Also with new versions of APIC tags in the UI are pointing to tagInst object rather than annotation parameter. So you are not able to view it in the UI.

CC: @lhercot @vfiftyfive

**Comment by tigelane** [comment]
Ah thank you @nkatarmal-crest   It seems that tagInst isn't implemented in the provider yet.  Maybe this should be a feature request vs bug?

**Comment by nkatarmal-crest** [comment]
@tigelane It should be a feature request for a new resource. I am closing this one out as it's not causing any issues in the code.
