### ISSUE TITLE
Add name for Cloud ACI subnets

### ISSUE THREAD

**Issue by marinalf** [CiscoDevNet/terraform-provider-aci#158]
### Description

Unable to add names per subnet to separate TGW and user subnets

### Terraform Version

Terraform v0.13.4
aci v0.5.1

### APIC version and APIC Platform

5.0.2h on Cloud ACI for AWS.

### Affected Resource(s)

aci_cloud_subnet

### Terraform Configuration Files

```hcl
resource "aci_cloud_subnet" "cloud_subnet1" {
  cloud_cidr_pool_dn            = aci_cloud_cidr_pool.cloud_cidr_pool.id
  name                          = "TGW Subnet A"
  ip                            = "172.11.1.0/24"
  usage                         = "gateway"
  zone                          = "uni/clouddomp/provp-aws/region-us-east-1/zone-us-east-1a"
```

### Debug Output

```
Error: Unsupported argument

  on main.tf line 57, in resource "aci_cloud_subnet" "cloud_subnet1":
  57:   name                          = "TGW Subnet A"

An argument named "name" is not expected here

```
### Expected Behavior

Every subnet with unique name 

### References

The name argument was available before per example below:

https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/examples/cloud_apic/main.tf

Or is there any other way we can enable it?

**Comment by nkatarmal-crest** [comment]
@marinalf this issue has been fixed in the v0.5.2 of the provider.
