### ISSUE TITLE
ACI L2ext domain

### ISSUE THREAD

**Issue by zilgopy** [CiscoDevNet/terraform-provider-aci#161]
Hi,
I found that I am not able to find a resource for creating an L2ext domain.  There are physical domains, L3ext domains and vmm domains, but it seems like it doesn't provide **External Bridged Domains**.
![image](https://user-images.githubusercontent.com/59171349/98819256-9847b600-2467-11eb-8c75-2aacc467654c.png)

**Comment by Thomjohn21** [comment]
Has this enhancement been added to v0.5.4?

**Comment by AshuSoni-crest** [comment]
We have resolved this issue by adding a new resource "aci_l2_outside", You will receive the updates in the next release of terraform-provider-aci. Let me know if you have any other queries.
