### ISSUE TITLE
aci_contract import not working as expected

### ISSUE THREAD

**Issue by jhtut** [CiscoDevNet/terraform-provider-aci#163]
### Terraform Version

$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/ciscodevnet/aci v0.5.1

### APIC version and APIC Platform

* V 4.2(3I) and on-prem.

### Affected Resource(s)

* aci_contract

### Terraform Configuration Files

resource "aci_contract" "TerraformDemoTest" {
    annotation  = "orchestrator:terraform"
    name        = "TerraformDemoTest"
    prio        = "unspecified"
    scope       = "context"
    target_dscp = "unspecified"
    tenant_dn   = "uni/tn-Production"
}

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

'terraform plan' should not be doing any update to the resource.

### Actual Behavior

'terraform plan' noted that there will be in-place update for filter_entry_ids and filter_ids.  Even after 'terraform apply', it still raised this in-place update.  

If I destroy the state and create brand new by just declaring resource without importing, 'terraform plan' will not complain after first apply which create state file.

The other work around is adding the last 2 lines in resource.

resource "aci_contract" "TerraformDemoTest" {
    annotation  = "orchestrator:terraform"
    name        = "TerraformDemoTest"
    prio        = "unspecified"
    scope       = "context"
    target_dscp = "unspecified"
    tenant_dn   = "uni/tn-Production"
    filter_entry_ids = [] <---
    filter_ids = [] <---
}

  # aci_contract.TerraformDemoTest will be updated in-place
  ~ resource "aci_contract" "TerraformDemoTest" {
        annotation       = "orchestrator:terraform"
      + filter_entry_ids = (known after apply)
      + filter_ids       = (known after apply)
        id               = "uni/tn-Production/brc-TerraformDemoTest"
        name             = "TerraformDemoTest"
        prio             = "unspecified"
        scope            = "context"
        target_dscp      = "unspecified"
        tenant_dn        = "uni/tn-Production"
    }

### Steps to Reproduce

1. Declare empty terraform resource.
resource "aci_contract" "TerraformDemoTest" {
}

2. Import terraform resource.

terraform import aci_contract.TerraformDemoTest "uni/tn-Production/brc-TerraformDemoTest"

3. `terraform plan`

* #0000

**Comment by nirav-cloudknox** [comment]
@jhtut You can ignore this one. It won't affect anything on the API side.

**Comment by nkatarmal-crest** [comment]
@jhtut It's expected, it won't have any effect on the API.
