### ISSUE TITLE
aci_subnet doesn't accept more than one 'ctrl' property

### ISSUE THREAD

**Issue by rtrcwby5183** [CiscoDevNet/terraform-provider-aci#166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/ciscodevnet/aci v0.5.1

### APIC version and APIC Platform

* V 4.2.4(o) On Prem

### Affected Resource(s)

* aci_subnet

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aci = {
      source  = "CiscoDevNet/aci"
      version = "0.5.1"
    }
  }
}
#configure provider with your cisco aci credentials.
provider "aci" {
  username = "user"
  password = "pass"
  url      = "https:/apic"
  insecure = true
}

# aci_subnet.tn-Infrastructure-BD-ESX_Vmotion-subnet-fc00ccccccs64:
resource "aci_subnet" "tn-Infrastructure-BD-ESX_Vmotion-subnet-fc00ccccccs64" {
    ctrl                            = "nd,querier"
    ip                              = "fc00:ccc::/64"
    parent_dn                       = "uni/tn-Infrastructure/BD-ESX_Vmotion"
    preferred                       = "yes"
    relation_fv_rs_bd_subnet_to_out = []
    scope                           = [
        "private",
    ]
    virtual                         = "no"
}
```

### Expected Behavior

nd and querier options should have been enabled (this line was gathered from import)

### Actual Behavior

```hcl
$ terraform plan

Error: expected ctrl to be one of [unspecified querier nd no-default-gateway], got nd,querier

  on aci.tf line 21, in resource "aci_subnet" "tn-Infrastructure-BD-ESX_Vmotion-subnet-fc00ccccccs64":
  21: resource "aci_subnet" "tn-Infrastructure-BD-ESX_Vmotion-subnet-fc00ccccccs64" {
```
### Steps to Reproduce

1. `terraform plan`

**Comment by nkatarmal-crest** [comment]
@rtrcwby5183 this issue has been fixed in the v0.5.2 of the Terraform provider. Please use that version to solve this issue.
