### ISSUE TITLE
provider 0.5.2 not available in terraform registry

### ISSUE THREAD

**Issue by d0ckt8le** [CiscoDevNet/terraform-provider-aci#168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.5

### APIC version and APIC Platform

not relevant

### Affected Resource(s)

aci provider

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
    aci = {
      source  = "CiscoDevNet/aci"
      version = "0.5.2"
    }
  }
  required_version = ">= 0.13"
}

```

### Expected Behavior

download of terraform aci provider 0.5.2

### Actual Behavior

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
ciscodevnet/aci: no available releases match the given constraints 0.5.2

### Steps to Reproduce

use the version.tf

https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs also does not list 0.5.2

**Comment by lhercot** [comment]
Should be fixed now. It is now available here: https://registry.terraform.io/providers/CiscoDevNet/aci/latest

Can you confirm it is fixed for you too?

**Comment by d0ckt8le** [comment]
It works now.

Thank you very much!
