### ISSUE TITLE
aci_l3_ext_subnet - Scope should be list object

### ISSUE THREAD

**Issue by richwats** [CiscoDevNet/terraform-provider-aci#169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/ciscodevnet/aci v0.5.1

### APIC version and APIC Platform

ACI 4.2(3j)

### Affected Resource(s)

aci_l3_ext_subnet

### Terraform Configuration Files

```hcl
resource "aci_l3_ext_subnet" "tf-default-match-1" {
  external_network_instance_profile_dn  = aci_external_network_instance_profile.exepg-default.id
  name_alias                            = "tf-default-match-1"
  description                           = "Match 0.0.0.0/1"
  ip                                    = "0.0.0.0/1"
  scope                                 = "shared-security"
}
```

### Actual Behavior

Error: External subnet's shared_security scope also needs import_security. Dn0=uni/tn-common/out-Lab-9348-Peering/instP-DEFAULT/extsubnet-[0.0.0.0/1], 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The ACI L3 Subnet GUI configuration allows for BOTH "External Subnets for External EPG"  (import-security option) and "Shared Security Import Subnet" (shared-security option).  If "shared-security" is selected, then the "import-security" option MUST also be selected.

"The APIC GUI blocks the configuration if “Shared Security Import Subnet” is configured without “External Subnets for the External EPG”. This scope is also a longest prefix match."

This terraform option should be a list object, not a single string field.

### References

* https://www.cisco.com/c/en/us/solutions/collateral/data-center-virtualization/application-centric-infrastructure/guide-c07-743150.html#L3Outsubnetscopeoptions

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the latest version of provider. Please download the latest version of provider (v0.5.3).
