### ISSUE TITLE
Provider Version 0.5.2 Errors out after the end of the plan with error message Error: missing expected [

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#171]
### Terraform Version
erraform v0.14.0
+ provider registry.terraform.io/ciscodevnet/aci v0.5.2

### APIC version and APIC Platform

* APIC 4.2(5k) - Simulator - On Prem

### Affected Resource(s)

Unfortunately I have no idea what the affected resource is.  There isn't enough information.  

When I try to run a plan the error message "Error: missing expected [" is returned.  I do not get this error message with version 0.5.1.  

I am looking for some guidance on what I should do to troubleshoot.

### Terraform Configuration Files

All of my code is available here:
https://github.com/scotttyso/terraform-aci-fabric-deploy

### Debug Output

The only error message is "Error: missing expected ["

### Expected Behavior

In 0.5.1 the "terraform plan -out main.plan" works.  In 0.5.2 it doesn't

### Actual Behavior

The only error message is "Error: missing expected ["

### Steps to Reproduce

The github link above has the terraform.tfstate file in it.  Simply running a plan against it with 0.5.2 is producing the error.

1. `terraform apply`

**Comment by thomasnoppe** [comment]
I have the same problem but on a running production fabric;
A while ago I had to do a state change for issue https://github.com/CiscoDevNet/terraform-provider-aci/issues/147
This seems very similar.

**Comment by thomasnoppe** [comment]
The problem seems to be caused by the ctrl attribute being changed from string to list of strings

https://github.com/CiscoDevNet/terraform-provider-aci/pull/167/commits/f2ca8e77790dd1ba6f8a9dac0025bb2ea5c68bfd

**Comment by thomasnoppe** [comment]
What would be the best way (without downtime) to fix this error?

I am using the aci_subnet resource in a custom module:

` {
      "module": "module.epg[\"291\"]",
      "mode": "managed",
      "type": "aci_subnet",
      "name": "subnet",
      "provider": "provider[\"registry.terraform.io/ciscodevnet/aci\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 1,
          "attributes": {
            "annotation": "orchestrator:terraform",
            "ctrl": "nd",
            "description": "",
            "id": "uni/tn-uzl/BD-vlan291_bd/subnet-[10.254.197.254/24]",
            "ip": "10.254.197.254/24",
            "name_alias": "",
            "parent_dn": "uni/tn-uzl/BD-vlan291_bd",
            "preferred": "no",
            "relation_fv_rs_bd_subnet_to_out": [],
            "relation_fv_rs_bd_subnet_to_profile": "",
            "relation_fv_rs_nd_pfx_pol": "",
            "scope": [
              "public"
            ],
            "virtual": "no"
          },
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjEifQ==",
          "dependencies": [
            "aci_l3_domain_profile.l3out_dom",
            "aci_l3_outside.to_cores",
            "aci_tenant.uzl",
            "aci_vrf.vrf",
            "module.epg.aci_bridge_domain.bd"
          ]
        }
      ]
    },`

**Comment by scotttyso** [comment]
For me based on your feedback I just went and updated my terraform state file changing the ctrl to match the requirement

So I changed
"ctrl": "nd"
to
"ctrl": [
  "nd"
]

I ran the apply after making that change and it removed the error and didn't note it as a change.

Maybe someone else has a better suggestion but it worked for me.

**Comment by nkatarmal-crest** [comment]
@scotttyso if you are running it as local state than it's good but if you are using remote state and than you should remove the whole resource using terraform state rm command and than run the terraform apply.

**Comment by d0ckt8le** [comment]
I validated this on a simulator and seems to work.
I will apply this to production asap.

thx!
