### ISSUE TITLE
Fix aci_vlan_pool attributes and documentation

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#174]
According to the documentation, current supported attributes for `aci_vlan_pool` are:

-  vlan_pool_dn - (Required) Distinguished name of parent VLANPool object.
- _from - (Required) _from of Object ranges.
- to - (Required) to of Object ranges.
- alloc_mode - (Optional) alloc_mode for object ranges. Allowed values: "dynamic", "static", "inherit"
- annotation - (Optional) annotation for object ranges.
- from - (Optional) encapsulation block start
- name_alias - (Optional) name_alias for object ranges.
- role - (Optional) system role type. Allowed values: "external", "internal"
- to - (Optional) encapsulation block end

`to` appears 2 times and `_from` is a required attribute instead of `from`. `_from` should not be allowed as an attribute and `from` should be made mandatory.

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the latest version of provider. Please download the latest version of provider (v0.5.3).
