### ISSUE TITLE
Add resources for Consul Terraform Sync service-graph creation

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#176]
The following resources are needed to create Service Graph Templates:
- vnsAbsGraph
- vnsAbsNode
- vnsRsNodeToLDev
- vnsLDevCtx
- vnsRsLDevCtxToLDev
- vnsLIfCtx
- vnsRsLIfCtxToSvcRedirectPol
- vnsRsLIfCtxToLIf
- vnsRsLIfCtxToBD

When relation is strong between parent and children (children are not needed as standalone resources), nested inline resource block definition is preferred over individual resource definition.

**Comment by AshuSoni-crest** [comment]
We have resolved this issue by adding few new resources, You will receive the updates in the next release of terraform-provider-aci. Let me know if you have any other queries.

**Comment by lhercot** [comment]
Fixed in v0.6.0. Closing.
