### ISSUE TITLE
Complete L3OUT resource

### ISSUE THREAD

**Issue by DravenChikken** [CiscoDevNet/terraform-provider-aci#177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Complete the L3OUT resource for OSPF or BGP creation

### APIC version and APIC Platform
5.1h

### Potential Terraform Configuration

Rather having to create the REST configuration, it would be ideal to add BGP configuration for ext_l3outs within the terraform aci provider

**Comment by AshuSoni-crest** [comment]
We have resolved this issue, You will receive the updates in the next release of terraform-provider-aci. Let me know if you have any other queries.
