### ISSUE TITLE
EPG Contract Master Support

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/terraform-provider-aci#179]
ACI supports the concept of EPG Contract Master.
We should add support for this to the EPG resource

**Comment by lhercot** [comment]
@camrossi it seems this is already supported with "relation_fv_rs_sec_inherited" which would be a list of EPG DNs.

Can you verify if that works for you?

We might want to update the documentation on what it does.

**Comment by camrossi** [comment]
Yes you are correct! Just tested and it works fine. Here is an example of a working code. 

We should probably just document it a bit better, contract inheritance was the old name of the feature but now in the GUI is called contract Master and I think I was looking for it with that name. 

```
resource "aci_application_epg" "epg_master" {
  application_profile_dn = aci_application_profile.app1.id
  name                   = "epg_master"
  relation_fv_rs_bd      = aci_bridge_domain.bd1.id
}

resource "aci_application_epg" "epg1" {
  application_profile_dn = aci_application_profile.app1.id
  name                   = "epg1"
  relation_fv_rs_bd      = aci_bridge_domain.bd1.id
  relation_fv_rs_sec_inherited = [aci_application_epg.epg_master.id]
}
```
