### ISSUE TITLE
Update variable access style in examples script

### ISSUE THREAD

**Issue by huyenduong** [CiscoDevNet/terraform-provider-aci#183]
In new terraform format, variable can be accessed using simple format such as:

data "aci_vmm_domain" "ACI" {
    provider_profile_dn = var.provider_profile_dn
    name                = var.vmmDomain
}

However, example script stills old style:

resource "aci_vmm_domain" "foovmm_domain" {
        provider_profile_dn = "${aci_provider_profile.example.id}"

Can we update example scripts to use new style )without "${}"

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) + ACI Class(es):

* aci_XXXXX + fv:XXXX

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by scotttyso** [comment]
I would also add to the request the following

When the variable is Set of String, examples should show the required format.. i.e.
on aci_application_epg
relation_fv_rs_sec_inherited = [...]
