### ISSUE TITLE
aci_cloud_aws_provider resource fails when setting the region argument on cAPIC 5.1(2e)

### ISSUE THREAD

**Issue by jerewill-cisco** [CiscoDevNet/terraform-provider-aci#184]
An apparent change in behavior in cAPIC as of the 5.1(2e) release now causes aci_cloud_aws_provider resources with the optional 'region' attribute set to fail.  Error message returned from the cAPIC is as follows.

"Error: Admin implicit props cannot be modified, prop=region"

**Comment by nirav-cloudknox** [comment]
@jerewill-cisco The region field, is optional there, can you try without the region field?

**Comment by nkatarmal-crest** [comment]
@vfiftyfive can we remove the bug label from this issue? I have tested this on the cloud APIC 4.2(3j) and it works perfectly there, it seems the issue is present only in the 5.1(2e) or highest. 

CC: @lhercot
