### ISSUE TITLE
Add required_providers syntax in the usage examples

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/terraform-provider-aci#209]
The current examples are missing this:

```
terraform {
  required_providers {
    aci = {
      source = "CiscoDevNet/aci"
      version = "0.5.4"
    }
  }
}
```

We should add this in the following places:

- https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs#example-usage
- https://github.com/CiscoDevNet/terraform-provider-aci#using-the-provider

**Comment by trenzy** [comment]
I am working on updating the documentation for both links. For the link:

https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs#example-usage

There is a "Use Provider" button at the top right of the page that provides an example like yours. I'll add something in the providers section to point to this.

For the link:
https://github.com/CiscoDevNet/terraform-provider-aci#using-the-provider

I am updating this section and should have it completed soon. I will provide an example similar to what you have provided.

**Comment by camrossi** [comment]
Thank you! 
And I know about the "Use Provider" button but I keep forgetting of its existence  :D
