### ISSUE TITLE
aci_spine_switch_association & aci_leaf_selector missing node blocks

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

14.6 

### APIC version and APIC Platform

* V 4.2(5k) on prem

### Affected Resource(s)

* aci_spine_switch_association 
* aci_leaf_selector 
* aci_leaf_profile

### Terraform Configuration Files

```hcl
resource "aci_spine_switch_association" "spine_switch_association" {
  for_each                                = local.spine_switch_association
  spine_profile_dn                        = each.value["spine_profile_dn"]
  annotation                              = each.value["annotation"]
  description                             = each.value["description"]
  name                                    = each.value["name"]
  name_alias                              = each.value["name_alias"]
  relation_infra_rs_spine_acc_node_p_grp  = each.value["spine_policy_group"]
  spine_switch_association_type           = each.value["switch_association_type"]   # Options are (ALL|ALL_IN_POD|range)
}

resource "aci_rest" "spine_node_block" {
  for_each   = local.spine_switch_association
  path       = "/api/node/mo/${each.value["spine_profile_dn"]}/spines-${each.value["name"]}-typ-${each.value["switch_association_type"]}.json"
  class_name = "infraNodeBlk"
  payload    = <<EOF
{
  "infraNodeBlk": {
    "attributes": {
      "dn": "${each.value["spine_profile_dn"]}/spines-${each.value["name"]}-typ-${each.value["switch_association_type"]}",
      "from_": "${each.value.node_block_from}",
      "to_": "${each.value.node_block_to}",
      "name": "${each.value["name"]}",
    },
    "children": []
  }
}
  EOF
}

resource "aci_spine_port_selector" "spine_port_selector" {
  for_each          = local.spine_switch_association
  spine_profile_dn  = each.value["spine_profile_dn"]
  tdn               = each.value["spine_interface_profile"]
}
```

### Expected Behavior

resource aci_leaf_profile has node_blocks to_ from_ but is missing the leaf Policy Group association, which is found in aci_leaf_selector.

aci_leaf_selector and aci_spine_switch_association both have the Policy Group Association but are both missing node_blocks.

Please update aci_leaf_selector and aci_spine_switch_assocation to support what I am doing with the rest module up above.

### Actual Behavior

have to create rest_api resource to finish configuration for spine node blocks and policy group association to leaf switches.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by scotttyso** [comment]
also on the aci_leaf_profile provide an option not to do leaf_selectors as part of the main policy that spine and leaf policies can be accomplished in the same way.  Today leaf_selector is required under aci_leaf_profile.. It would be better to be consistent with spine and leaf policies.

**Comment by RutvikS-crest** [comment]
@scotttyso a resource "aci_node_block" is present to attach node block to both these resources. Let me know in case of any queries.
