### ISSUE TITLE
aci_spine_switch_association > relation_infra_rs_spine_acc_node_p_grp

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#262]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 14.6 
ACI Provider 0.5.4
### APIC version and APIC Platform

* V4.2(5k) on-prem

### Affected Resource(s)

* aci_spine_switch_association 

### Terraform Configuration Files

```hcl
resource "aci_spine_switch_association" "spine_switch_association" {
  for_each                                = local.spine_switch_association
  spine_profile_dn                        = each.value["spine_profile_dn"]
  annotation                              = each.value["annotation"]
  description                             = each.value["description"]
  name                                    = each.value["name"]
  name_alias                              = each.value["name_alias"]
  relation_infra_rs_spine_acc_node_p_grp  = "uni/infra/funcprof/spaccnodepgrp-default"
  # relation_infra_rs_spine_acc_node_p_grp  = each.value["spine_policy_group"]
  spine_switch_association_type           = each.value["switch_association_type"]   # Options are (ALL|ALL_IN_POD|range)
}
```

### Actual Behavior

The code is working but it always tells me it is going to re-apply the policy-group with the following on a "terraform plan"

```
Terraform will perform the following actions:

  # module.dc1-spine101_spine_profile_sw_assoc.aci_spine_switch_association.spine_switch_association["dc1-spine101"] will be updated in-place
  ~ resource "aci_spine_switch_association" "spine_switch_association" {
        id                                     = "uni/infra/spprof-dc1-spine101/spines-dc1-spine101-typ-range"
        name                                   = "dc1-spine101"
      ~ relation_infra_rs_spine_acc_node_p_grp = jsonencode({}) -> "uni/infra/funcprof/spaccnodepgrp-default"
        # (3 unchanged attributes hidden)
    }
```

When I login to the APIC the default policy group is associated to the switch selector but I just get this message each time I run a new terraform plan/apply

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lhercot** [comment]
Issue fixed in master branch. Fix will be present in v1.0.0.
