### ISSUE TITLE
Request STP/BPDU Interface Policy Creation Support

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for Spanning Tree Interface Policies

### New or Affected Resource(s) + ACI Class(es):

* aci_spanning_tree
* Class: stpIfPol

### APIC version and APIC Platform

* V all

### Potential Terraform Configuration

```hcl
#------------------------------------------
# Create Spanning-Tree Interface Policies
#------------------------------------------

/*
API Information:
 - Class: "stpIfPol"
 - Distinguished Name: "uni/infra/ifPol-{Policy Name}"
GUI Location:
 - Fabric > Access Policies > Policies > Interface > Spanning Tree Interface : {Policy Name}
*/
resource "aci_rest" "stp" {
  for_each   = local.stp
  path       = "/api/node/mo/uni/infra/ifPol-${each.value["name"]}.json"
  class_name = "stpIfPol"
  payload    = <<EOF
{
  "stpIfPol": {
    "attributes": {
      "dn": "uni/infra/ifPol-${each.value["name"]}",
      "annotation": "${each.value["annotation"]}",
      "ctrl": "${each.value["ctrl"]}",
      "descr": "${each.value["description"]}",
      "name": "${each.value["name"]}",
      "nameAlias": "${each.value["name_alias"]}"
    }
  }
}
  EOF
}

```

### References

* #0000

**Comment by RutvikS-crest** [comment]
This resource has been added to the provider in release v0.6.0. resource name: aci_spanning_tree_interface_policy
