### ISSUE TITLE
Firmware Node Block - Add Nodes to aci_firmware_group

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently the provider doesn't support adding nodes to the aci_firmware_group

### New or Affected Resource(s) + ACI Class(es):

* aci_firmware_group_nodeblock
* 

### APIC version and APIC Platform

* All.

### Potential Terraform Configuration

```hcl
/*
API Information:
 - Class: "fabricNodeBlk"
 - Distinguished Name: "uni/fabric/fwgrp-{Firmware Group Name}/nodeblk-{name}"
GUI Location:
 - Admin > Firmware > Nodes > {Firmware Group Name}
*/
resource "aci_rest" "node_firmware_block" {
  for_each   = local.node_firmware_block
  path       = "/api/node/mo/${each.value["firmware_group_dn"]}/nodeblk-blk${node_id_from}-${node_id_to}.json"
  class_name = "fabricNodeBlk"
  payload    = <<EOF
{
  "fabricNodeBlk": {
    "attributes": {
      "annotation": "${var.each.value["annotation"]}",
      "descr": "${var.each.value["description"]}",
      "dn": "${each.value["firmware_group_dn"]}/nodeblk-blk${each.value["node_id_from"]}-${each.value["node_id_to"]}",
      "from_": "${each.value["node_id_from"]}",
      "name": "blk${each.value["node_id_from"]}-${each.value["node_id_to"]}",
      "nameAlias": "${each.value["name_alias"]}",
      "to_": "${each.value["node_id_to"]}",
    },
    "children": []
  }
}
  EOF
}

```

### References

* #0000

**Comment by AshuSoni-crest** [comment]
hey @scotttyso, we already have a resource for your request, but the resource name is different: **aci_node_block_firmware**,
Please refer [aci_node_block_firmware resource docs](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/node_block_firmware) for more information.
let me know if you have any queries

**Comment by scotttyso** [comment]
Okay... I am sorry for missing this.  I have tried to go through the list multiple times before I submit a request..  I simply missed this... thanks for the update.
