### ISSUE TITLE
ctrl repeatedly set as "unspecified" within aci_subnet resource 

### ISSUE THREAD

**Issue by jody-garellek** [CiscoDevNet/terraform-provider-aci#293]
### Terraform Version

+ provider registry.terraform.io/hashicorp/vault v2.18.0
+ provider registry.terraform.io/terraform-providers/aci v0.5.4

### APIC version and APIC Platform

* V 4.2.0 (4i) on-prem

### Affected Resource(s)

* aci_subneg

### Terraform Configuration Files

resource "aci_subnet" "systems" {
  parent_dn = aci_bridge_domain.systems.id
  description      = "systems subnet created by terraform"
  ip               = "192.168.24.1/22"
  ctrl             = ["unspecified"]
  preferred        = "yes"
  scope            = ["public"]
}

### Expected Behavior

No changes should be made once the subnet is created

### Actual Behavior

Terraform tries to correct the ctrl setting every time Terraform is run:
# aci_subnet.systems will be updated in-place
  ~ resource "aci_subnet" "systems" {
      ~ ctrl                            = [
          - "",
          + "unspecified",
        ]
        id                              = "uni/tn-eng-prod/BD-eng-systems-bd/subnet-[192.168.24.1/22]"
        # (8 unchanged attributes hidden)
    }

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

No

### References

 https://github.com/CiscoDevNet/terraform-provider-aci/issues/171

**Comment by lhercot** [comment]
We have resolved this issue, the fix is available in v0.7.0.
