### ISSUE TITLE
aci_attachable_access_entity_profile - missing Ability to turn on/off Infrastructure VLAN

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) + ACI Class(es):

* aci_attachable_access_entity_profile Class infraAttEntityP
New resource
* aci_aaep_to_epg Class infraRsFuncToEpg

### APIC version and APIC Platform

* 2.X and Above

### Potential Terraform Configuration

```hcl
Infrastructure VLAN Portion

resource "aci_physical_domain" "physical" {
  infra_vlan= "yes/no"
}

Here is the API Call Output
https://asgard-apic01.rich.ciscolabs.com/api/node/mo/uni/infra/attentp-testing123/provacc.json
{
	"infraProvAcc": {
		"attributes": {
			"dn": "uni/infra/attentp-{{aep_name}}/provacc",
			"status": "deleted"
		},
		"children": []
	}
}

{
	"infraProvAcc": {
		"attributes": {
			"dn": "uni/infra/attentp-{{aep_name}}/provacc",
			"status": "created"
		},
		"children": []
	}
}

## Associate EPG's to the AAEP ##
I would recommend this be a different resource because it might be a chicken and egg problem related to EPG's.  I think a separate resource would make it easier.

url: https://asgard-apic01.rich.ciscolabs.com/api/node/mo/uni/infra/attentp-{{aep_name}}/gen-default.json
{
	"infraRsFuncToEpg": {
		"attributes": {
			"tDn": "uni/tn-prod/ap-nets/epg-v0997_epg",
			"status": "created,modified",
			"encap": "vlan-997"
		},
		"children": []
	}
}

```

### References

* #0000

**Comment by FrederikSuijs** [comment]
With regards to attaching an aaep to epg, I've seen multiple issues around that; #275 and #67
Basically the resources are already there, but lacking proper documentation imo.

Here is a configuration example snippet ( I've left out some irrelevant config such as domains/BD/AP...) :

```hcl
resource "aci_attachable_access_entity_profile" "aaep1" {
  name = "default_AAEP"
  relation_infra_rs_dom_p = [
    module.fabric_domain_physdom["default_Physdom"].id,
    module.fabric_domain_l3dom["default-L3dom"].id,
  ]
}

resource "aci_access_generic" "access_generic" {
  attachable_access_entity_profile_dn = aci_attachable_access_entity_profile.aaep1.id
  name                                = "default"
}

resource "aci_application_epg" "application_epg" {
  application_profile_dn = aci_application_profile.application_profile.id
  name                   = "demo_EPG"
  relation_fv_rs_bd      = aci_bridge_domain.bridge_domain.id
}

resource "aci_epgs_using_function" "epgs_using_function" {
  access_generic_dn = aci_access_generic.access_generic.id
  tdn               = aci_application_epg.application_epg.id
  encap             = "vlan-10"
  instr_imedcy      = "immediate"
  mode              = "regular"
}
```



For enabling/disabling the infra vlan, you get a thumbs up :)

**Comment by scotttyso** [comment]
Perfect.  I either missed this or didn't understand what it was for.  Thanks.

**Comment by RutvikS-crest** [comment]
Hi @scotttyso, I guess there is a resource with the name "aci_vlan_encapsulationfor_vxlan_traffic" to create or destroy infrastructure VLANs. Let me know in case of any queries.
