### ISSUE TITLE
A way to associate DB to a vrf and a EPG to a BD

### ISSUE THREAD

**Issue by gnuowned** [CiscoDevNet/terraform-provider-aci#332]
I can't find a way to associate a BD to a VRF I just can't find it in the doc. 

It should be a way to do that something like this:
```
resource "aci_bridge_domain" "dev_bd" {
  tenant_dn	= aci_tenant.tenant.id
  name		= "dev_bd"
  vrf_dn            = aci_vrf.vfr_for_db.id    <- this should be able to happen. 
}
```
In the same way, there is no way to associate a application epg to a bd.  Should be a way to do this, something like this: 

```
resource "aci_application_epg" "APP_EPG" {
  application_profile_dn = aci_application_profile.test-app.id
  bridge_domain_dn = aci_bd.bd_for_epg.id    <---- this. 
  name			 = "APP_EPG"
}
```

**Comment by FrederikSuijs** [comment]
You have to look for **relation_fv_rs_bd**, see snippet below.

```hcl
resource "aci_bridge_domain" "bridge_domain" {
  name               = "${var.cn}_BD"
  tenant_dn          = var.tenant_id
  relation_fv_rs_ctx = aci_vrf.vrf.id
  relation_fv_rs_bd_to_out = [module.L3out.l3out_id]
}

resource "aci_application_epg" "application_epg" {
  application_profile_dn = aci_application_profile.application_profile.id
  name                   = "${var.cn}_EPG"
  relation_fv_rs_bd      = aci_bridge_domain.bridge_domain.id
}
```

I have to agree with you, a lot of the code/examples are not that intuitive/user friendly. This is a perfect example of that. I hope the BU realizes that and tries to streamline this a bit more.

**Comment by gnuowned** [comment]
wow, 

 Indeed is not intuitive. Thanks for your answer. 

Regards!
