### ISSUE TITLE
Map aaaDomain to user

### ISSUE THREAD

**Issue by PhilipWhiteside** [CiscoDevNet/terraform-provider-aci#340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

SecDom was added here #102, however the tenant and user resources does not have a `aaaUserDomain` argument to map into the newly created SecDom. 

### New or Affected Resource(s) + ACI Class(es):

* `aci_tenant` + `aaaDomainRef`
* `aci_local_user` + `aaaUserDomain`

### APIC version and APIC Platform

* Version: 5.1(2e) on-prem

### Potential Terraform Configuration

```hcl
resource "aci_local_user" "default" {
  for_each = local.tenants

  name     = "${local.prefix}${each.key}"
  pwd      = try(each.value.password, local.defaults.password)
  aaaDomin = aci_aaa_domain.default.id
}
```

**Comment by lhercot** [comment]
PR #814 allows the mapping of tenants and other object to security domains with the aci_aaa_domain_relationship resource.

This issue should focus on the aci_local_user + aaaUserDomain part.

**Comment by lhercot** [comment]
We documented on how to achieve this here: https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/examples/aci_local_user_domain/main.tf
