### ISSUE TITLE
unknown attribute 'descr' in element 'fabricExplicitGEp'

### ISSUE THREAD

**Issue by vaneuk** [CiscoDevNet/terraform-provider-aci#343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.15.0

### APIC version and APIC Platform

* V 4.2.6l and on-prem

### Affected Resource(s)

* aci_vpc_explicit_protection_group

### Terraform Configuration Files

```hcl
resource "aci_vpc_explicit_protection_group" "vpc_domains" {
  for_each                         = local.vpc_domains
  name                             = each.value["name"]
  annotation                       = each.value["annotation_domain"]
  switch1                          = each.value["node1_id"]
  switch2                          = each.value["node2_id"]
  vpc_domain_policy                = each.value["domain_policy"]
  vpc_explicit_protection_group_id = each.value["vpc_domain_id"]
}
```

### Debug Output

```
│ Error: unknown attribute 'descr' in element 'fabricExplicitGEp'
│ 
│   on ../modules/vpc_domains_v2/main.tf line 12, in resource "aci_vpc_explicit_protection_group" "vpc_domains":
│   12: resource "aci_vpc_explicit_protection_group" "vpc_domains" {
```
If we look at the produced JSON in debug, we see that descr attributes is present in fabricExplicitGEp, which is not a valid attribute.
```json
{
    "fabricExplicitGEp": {
        "attributes": {
            "annotation": "",
            "descr": "",
            "dn": "uni/fabric/protpol/expgep-vPC_101-102",
            "id": "101",
            "name": "vPC_101-102",
            "rn": "fabric/protpol/expgep-vPC_101-102",
            "status": "modified"
        },
        "children": [
            {
                "fabricNodePEp": {
                    "attributes": {
                        "id": "101"
                    }
                }
            },
            {
                "fabricNodePEp": {
                    "attributes": {
                        "id": "102"
                    }
                }
            },
            {
                "fabricRsVpcInstPol": {
                    "attributes": {
                        "tnVpcInstPolName": "default"
                    }
                }
            }
        ]
    }
}
```

Looks like the issue is that type VPCExplicitProtectionGroup uses BaseAttributes, which has descr defined:
https://github.com/CiscoDevNet/terraform-provider-aci/blob/41f09d9637f292de63cd3bffae8fdde97b30f3ec/vendor/github.com/ciscoecosystem/aci-go-client/models/fabric_explicit_g_ep.go#L12

### Expected Behavior

vpc_explicit_protection_group should be created

### Actual Behavior

vpc_explicit_protection_group was not created because of error

### Steps to Reproduce

1. `terraform apply`

**Comment by AshuSoni-crest** [comment]
We have resolved this issue, You will receive the updates in the next release of terraform-provider-aci.
