### ISSUE TITLE
aci_l3out_path_attachment and aci_l3out_path_attachment_secondary_ip missing support for VPC

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V4.X, and 5.X

### Affected Resource(s)

* aci_l3out_path_attachment
* aci_l3out_path_attachment_secondary_ip

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

The resource is missing support for VPC.

Need to add the following Attributes:
Side: [A|B]
Then Because there is a Side A and Side B need the ability to assign to each side the following:
addr
ipv6Dad
llAddr

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by scotttyso** [comment]
I am not sure if it is better to add a new resource of type l3extMember

**Comment by AshuSoni-crest** [comment]
We have resolved this issue by adding a new resource "aci_l3out_vpc_member". You will receive the updates in the next release of terraform-provider-aci.
