### ISSUE TITLE
aci_l3out_path_attachment rejects custom MTU Values

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

All 

### APIC version and APIC Platform

* V All

### Affected Resource(s)

* aci_l3out_path_attachment

### Terraform Configuration Files

```hcl
resource "aci_l3out_path_attachment" "Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf201_Interface_Profile_Eth1-48_path_attachment" {
    depends_on                      = [
        aci_tenant.common,
        aci_logical_node_profile.Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf201,
        aci_logical_interface_profile.Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf201_Interface_Profile_Eth1-48
    ]
    logical_interface_profile_dn    = aci_logical_interface_profile.Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf201_Interface_Profile_Eth1-48.id
    target_dn                       = "topology/pod-1/paths-201/pathep-[eth1/48]"
    if_inst_t                       = "l3-port"
    addr                            = "198.18.0.16/31"
    annotation                      = ""
    ipv6_dad                        = "enabled"
    mtu                             = "9000"
    target_dscp                     = "unspecified"
}

```

### Panic Output

 Error: expected mtu to be one of [inherit], got 9000
│ 
│   with aci_l3out_path_attachment.Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf202_Interface_Profile_Eth1-48_path_attachment,
│   on L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf202.tf line 82, in resource "aci_l3out_path_attachment" "Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf202_Interface_Profile_Eth1-48_path_attachment":
│   82: resource "aci_l3out_path_attachment" "Tenant_common_L3Out_dc1-dmz_L3_Node_Profile_dc1-leaf202_Interface_Profile_Eth1-48_path_attachment" {

### Expected Behavior

Ability to Set MTU Value

### Actual Behavior

Only Accepts inherit

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lhercot** [comment]
We have resolved this issue, the fix is available in v0.7.0.
