### ISSUE TITLE
Floating SVI: l3extRsDynPathAtt support

### ISSUE THREAD

**Issue by camrossi** [CiscoDevNet/terraform-provider-aci#413]
This class is required to add to a floating SVI a node and its floating IP

For now this is a workaround 

```
resource "aci_rest" "floating_svi_path" {
    path       = "/api/mo/uni/tn-${var.l3out.l3out_tenant}/out-${var.l3out.name}/lnodep-${var.l3out.node_profile_name}/lifp-${var.l3out.int_prof_name}/vlifp-[topology/pod-${each.value.pod_id}/node-${each.value.node_id}]-[vlan-${var.l3out.vlan_id}]/rsdynPathAtt-[uni/phys-${var.l3out.physical_dom}].json"
    for_each = {for v in var.l3out.anchor_nodes:  v.node_id => v}
    class_name = "l3extRsDynPathAtt"
      content = {
        "floatingAddr" = var.l3out.floating_ip
        "tDn" = "uni/phys-${var.l3out.physical_dom}"
  }
}
```

**Comment by lhercot** [comment]
Can you check if aci_l3out_floating_svi fulfill your ask?

**Comment by camrossi** [comment]
Maybe I am missing something but I am not sure how I can add the floatingAddr with the aci_l3out_floating_svi.
There is no documentation for it nor code as far as I can tell and even if I can specify a relation_l3ext_rs_dyn_path_att you must also specify a Floating IP so for me this is non-working. 
I am happy to have the code added to the aci_l3out_floating_svi as long as it works. 

![image](https://user-images.githubusercontent.com/16535101/149053840-8f585110-1f33-40ef-96b0-ae57b867d1ab.png)
