### ISSUE TITLE
aci_l3out_path_attachment_secondary_ip doesn't support VPC aci_l3out_vpc_member

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aci_l3out_path_attachment_secondary_ip supports port-channels and routed/sub-interfaces.  But not VPC

With the New aci_l3out_vpc_member need the ability to add secondaries to it as well.

### New or Affected Resource(s) + ACI Class(es):

* aci_l3out_vpc_secondary_ip Side A and Side B

### APIC version and APIC Platform

* All
* 
### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by qzx** [comment]
@scotttyso this might just be a documentation issue, (maybe a bit of a naming issue on the parameter in the resource), but this works perfectly fine:

`resource "aci_l3out_path_attachment" "fw_vpc" {
  logical_interface_profile_dn = data.aci_logical_interface_profile.this.id
  target_dn                    = "topology/pod-2/protpaths-203-204/pathep-[FIREWALL-VPC]"
  if_inst_t                    = "ext-svi"
  encap                        = "vlan-100"
  mtu                          = "1500"
}

resource "aci_l3out_vpc_member" "fw_vpc_a" {
  leaf_port_dn = aci_l3out_path_attachment.fw_vpc.id
  side         = "A"
  addr         = "10.19.1.154/29"
}

resource "aci_l3out_vpc_member" "fw_vpc_b" {
  leaf_port_dn = aci_l3out_path_attachment.fw_vpc.id
  side         = "B"
  addr         = "10.19.1.155/29"
}

resource "aci_l3out_path_attachment_secondary_ip" "fw_vpc_a_float" {
  l3out_path_attachment_dn = aci_l3out_vpc_member.fw_vpc_a.id
  addr  = "10.19.1.158/29"
}

resource "aci_l3out_path_attachment_secondary_ip" "fw_vpc_b_float" {
  l3out_path_attachment_dn = aci_l3out_vpc_member.fw_vpc_b.id
  addr  = "10.19.1.158/29"
}
`

**Comment by RutvikS-crest** [comment]
Closing this issue as aci_l3out_vpc_member already supports adding side A and B.
