### ISSUE TITLE
Idempotency fails when control(ctrl) is set to 'unspecified'.

### ISSUE THREAD

**Issue by shrsr** [CiscoDevNet/terraform-provider-aci#422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* All

### Affected Resource(s)

* All resources which accepts ctrl as a list

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

When control(ctrl) is set to 'unspecified' and applied a second or subsequent number of times, state should not change.

When control(ctrl) is set to 'unspecified', idempotency fails

1. `terraform apply`

### References

* #0000

**Comment by lhercot** [comment]
We have resolved this issue, the fix is available in v0.7.0.
