### ISSUE TITLE
The provider ciscodevnet/aci does not support resource type "aci_spanning_tree_interface_policy"

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-aci#426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.3

### APIC version and APIC Platform

* All

### Affected Resource(s)

* aci_spanning_tree_interface_policy

### Terraform Configuration Files

```hcl
resource "aci_spanning_tree_interface_policy" "STP_bpduFG" {
    description = "BPDU Filter and Guard"
    name        = "example"
    ctrl        = ["bpdu-filter","bpdu-guard"]
}

```

### Panic Output

Ignore that the output looks weird for terraform init.  It is just how I am reading stdout.  The ACI Provider version as shown below is 0.6.0 but the new resource type is not recognized.

```
b'\n'
b'\x1b[0m\x1b[1mInitializing the backend...\x1b[0m\n'
b'\n'
b'\x1b[0m\x1b[1mInitializing provider plugins...\x1b[0m\n'
b'- Reusing previous version of ciscodevnet/aci from the dependency lock file\n'
b'- Using previously-installed ciscodevnet/aci v0.6.0\n'
b'\n'
b'\x1b[0m\x1b[1m\x1b[32mTerraform has been successfully initialized!\x1b[0m\x1b[32m\x1b[0m\n'
b'\x1b[0m\x1b[32m\n'
b'You may now begin working with Terraform. Try running "terraform plan" to see\n'
b'any changes that are required for your infrastructure. All Terraform commands\n'
b'should now work.\n'
b'\n'
b'If you ever set or change modules or backend configuration for Terraform,\n'
b'rerun this command to reinitialize your working directory. If you forget, other\n'
b'commands will detect it and remind you to do so if necessary.\x1b[0m\n'
╷
│ Error: Invalid resource type
│ 
│   on Policies_Interface_STP_bpduFG.tf line 12, in resource "aci_spanning_tree_interface_policy" "STP_bpduFG":
│   12: resource "aci_spanning_tree_interface_policy" "STP_bpduFG" {
│ 
│ The provider ciscodevnet/aci does not support resource type "aci_spanning_tree_interface_policy".
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lhercot** [comment]
We have resolved this issue, the fix is available in v0.7.0.
