### ISSUE TITLE
Add Description Attribute to resource aci_range

### ISSUE THREAD

**Issue by wietersr** [CiscoDevNet/terraform-provider-aci#453]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aci_range resource has no name or description attribute in the current release. When trying to scale the range attributes using for_each loop and object map variables, there's really no way to cleanly reference a key value in the object map, which is required for map objects. I believe "description" would work. The GUI configuration screen allows the administrator to add a description string (but not name or name_alias despite the MIT object model allowing those).

I've never contributed to a community git hub project, nor am I well-versed in Golang, but would be interested in contributing to this and using it as a motivation to learn both github and go if there is access to community coaching.

### New or Affected Resource(s) + ACI Class(es):

* aci_range + fvns:EncapBlk

### APIC version and APIC Platform

* all.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by wietersr** [comment]
description attribute (while NOT documented) is a usable attribute. Perhaps update the docs...

**Comment by lhercot** [comment]
Reopening to trac as a documentation fix.
