### ISSUE TITLE
change to aci_logical_interface_profile breaks existing code/state, makes transition to 0.7.0 difficult

### ISSUE THREAD

**Issue by jeremypng** [CiscoDevNet/terraform-provider-aci#456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

❯ terraform -v
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.0

### APIC version and APIC Platform

* V 5.1.1h and on-prem

### Affected Resource(s)

* aci_logical_interface_profile
* aci_l3_outside

### Expected Behavior

There should be a note in the documentation on how to deal with the removal of the relation_l3ext_rs_path_l3_out_att attribute from the aci_logical_interface_profile resource. It is not listed as a breaking change.

This attribute was removed in commit 7136d15ed014ee2459e86852c3c940c530b4530c

### Actual Behavior

Running terraform plan resulted in this output for each aci_l3_outside object in my state/config:
```
│ Error: missing expected [
│
│
```

Enabling trace produced this output:
```
2021-06-02T13:05:01.591-0500 [TRACE] vertex "aci_l3_outside.l3out": dynamic subgraph encountered errors: missing expected [,missing expected [,missing expected [,missing expected [,missing expected [
2021-06-02T13:05:01.593-0500 [TRACE] vertex "aci_l3_outside.l3out": visit complete
```

### Steps to Reproduce

Use a state file from 0.5.4 with an aci_logical_interface_profile using the relation_l3ext_rs_path_l3_out_att attribute, and linked to an aci_l3_outside resource. Update your provider to 0.7.0 and run terraform plan.

### Important Factoids

To workaround this issue I had to edit the state file and remove the relation_l3ext_rs_path_l3_out_att attribute from the aci_logical_interface_profile objects. Then I had to remove the aci_l3_outside objects from the state and import them.

**Comment by lhercot** [comment]
This is related to the change we made on aci_l3_outside. When you do a plan or apply. The first thing that TF will do is refresh everything which will include the aci_l3_outside.

Did you try directly removing the aci_l3_outside item with "terraform state rm 'aci_l3_outside.l3out'" ? You will then have to import it or re-apply.
Other people also added the [] to the aci_l3_outside 'enforce_rtctrl' attribute.

We are trying not to introduce breaking changes but those were bugs we had to fix has they were not letting user properly configured that property.

**Comment by jeremypng** [comment]
I did remove it and re-import it. I think I ended up hitting two issues. One was the enforce_rtrctrl: issue you mentioned. The other was the removal of the relation_l3ext_rs_path_l3_out_att attribute.

My problem is resolved, I just thought some added information in the release notes might help others when they upgrade.

**Comment by lhercot** [comment]
Closing as issue is resolved.
