### ISSUE TITLE
Change log statements in service_manager.go

### ISSUE THREAD

**Issue by anvitha-jain** [CiscoDevNet/terraform-provider-aci#527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

In vendor/service_manager.go file, within the function - func CheckForErrors() the log statements being printed are all the same -> log.Printf("[DEBUG] Exit from errors %v", cont).
These statements needs to reframed.

* #0000

**Comment by AshuSoni-crest** [comment]
hey @anvitha-jain, What should be there in those logs?

**Comment by anvitha-jain** [comment]
In the code all the log statements are under a single condition and they print the same message, instead they should be printing relavant messages for each check.

**Comment by lhercot** [comment]
Issue fixed in master branch. Fix will be present in v1.0.0.
