### ISSUE TITLE
Add EPG attribute name into the export list of aci_application_EPG

### ISSUE THREAD

**Issue by kristofff1204** [CiscoDevNet/terraform-provider-aci#537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If we want to add a VM into a distributed port group we must generate the correct name after the EPF is being created.
But if i check the state file the name of the effective port group is there but it isn't exported as an attribute to the outside world.

With exporting this attribute you will always get the correct port group name in vsphere.

### New or Affected Resource(s) + ACI Class(es):

aci_application_epg

### APIC version and APIC Platform

* V 4.2

* #0000

**Comment by akinross** [comment]
Hi @kristofff1204, 

I tried recreating your described issue but do not fully comprehend what it is that you are trying to achieve. Could you please provide me a full example ( tf execution file and the statefile ) of what you are doing?

**Comment by akinross** [comment]
Hi @kristofff1204,

Would you be able to share an example?

**Comment by akinross** [comment]
Hi @kristofff1204,

Assuming that you have managed to fix the issue. Will close the issue for now. Please re-open or create a new issue if assistance is still required.
