### ISSUE TITLE
aci_epg_to_static_path resource bug 

### ISSUE THREAD

**Issue by kozhabergenova** [CiscoDevNet/terraform-provider-aci#555]
### Terraform Version
terraform -v
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.0

### APIC Version
Application Policy Infrastructure Controller
Version: 4.2(4i)

### Affected Resource(s)
resource "aci_epg_to_static_path"
resource "aci_application_epg"

### Terraform Configuration Files
terraform {
  required_providers {
    aci = {
      source = "CiscoDevNet/aci"
      version = "0.7.0"
    }
  }
}

provider "aci" {
  username = var.aci_username
  password = var.aci_password
  url = "https://apic1.test.net/"
  insecure = true
}

data "aci_tenant" "terraform-dev" {
  name  = "terraform-dev"
}

data "aci_vrf" "vrf-terraform-dev" {
  tenant_dn  = data.aci_tenant.terraform-dev.id
  name       = "vrf-terraform-dev"
}

resource "aci_application_profile" "app_profile" {
  tenant_dn   = data.aci_tenant.terraform-dev.id
  name        = "PROJECT2_DEV_AP"
}

resource "aci_bridge_domain" "bridge_domain" {
  tenant_dn                   = data.aci_tenant.terraform-dev.id
  name                        = "Vlan_16_BD"
  relation_fv_rs_ctx          = data.aci_vrf.vrf-terraform-dev.id
  optimize_wan_bandwidth      = "no"
  annotation                  = "tag_bd"
  arp_flood                   = "yes"
  ep_clear                    = "no"
  host_based_routing          = "no"
  intersite_bum_traffic_allow = "yes"
  intersite_l2_stretch        = "yes"
  ip_learning                 = "yes"
  limit_ip_learn_to_subnets   = "yes"
  mcast_allow                 = "no"
  multi_dst_pkt_act           = "bd-flood"
  bridge_domain_type          = "regular"
  unicast_route               = "yes"
  unk_mac_ucast_act           = "proxy"
  unk_mcast_act               = "flood"
  vmac                        = "not-applicable"
}

resource "aci_application_epg" "application_epg" {
  application_profile_dn = aci_application_profile.app_profile.id
  relation_fv_rs_bd      = aci_bridge_domain.bridge_domain.id
  name                   = "PROJECT2_DEV_EPG"
  description            = "%s"
  annotation             = "tag_epg"
  exception_tag          = "0"
  flood_on_encap         = "disabled"
  has_mcast_source       = "no"
  is_attr_based_epg      = "no"
  match_t                = "AtleastOne"
  pc_enf_pref            = "unenforced"
  pref_gr_memb           = "exclude"
  prio                   = "unspecified"
  shutdown               = "no"
}

resource "aci_epg_to_static_path" "staic_path_2_computes" {
  application_epg_dn  = aci_application_epg.application_epg.id
  for_each = toset(var.vpc_name)
  tdn  = "topology/pod-1/protpaths-101-102/pathep-${each.key}"
  encap  = "vlan-16"
  mode  = "regular"
}

resource "aci_subnet" "subnet" {
  parent_dn   = aci_bridge_domain.bridge_domain.id
  ip          = "10.10.16.1/24"
  preferred   = "no"
  scope       = ["public","shared"]
  description = "This subnet is created by terraform"
}

### Debug Output
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

   aci_application_epg.application_epg will be created
  + resource "aci_application_epg" "application_epg" {
      + annotation             = "tag_epg"
      + application_profile_dn = (known after apply)
      + description            = "%s"
      + exception_tag          = "0"
      + flood_on_encap         = "disabled"
      + fwd_ctrl               = (known after apply)
      + has_mcast_source       = "no"
      + id                     = (known after apply)
      + is_attr_based_epg      = "no"
      + match_t                = "AtleastOne"
      + name                   = "PROJECT2_DEV_EPG"
      + name_alias             = (known after apply)
      + pc_enf_pref            = "unenforced"
      + pref_gr_memb           = "exclude"
      + prio                   = "unspecified"
      + relation_fv_rs_bd      = (known after apply)
      + shutdown               = "no"
    }

   aci_application_profile.app_profile will be created
  + resource "aci_application_profile" "app_profile" {
      + annotation  = "orchestrator:terraform"
      + description = (known after apply)
      + id          = (known after apply)
      + name        = "PROJECT2_DEV_AP"
      + name_alias  = (known after apply)
      + prio        = (known after apply)
      + tenant_dn   = "uni/tn-terraform-dev"
    }

   aci_bridge_domain.bridge_domain will be created
  + resource "aci_bridge_domain" "bridge_domain" {
      + annotation                  = "tag_bd"
      + arp_flood                   = "yes"
      + bridge_domain_type          = "regular"
      + description                 = (known after apply)
      + ep_clear                    = "no"
      + ep_move_detect_mode         = (known after apply)
      + host_based_routing          = "no"
      + id                          = (known after apply)
      + intersite_bum_traffic_allow = "yes"
      + intersite_l2_stretch        = "yes"
      + ip_learning                 = "yes"
      + ipv6_mcast_allow            = (known after apply)
      + limit_ip_learn_to_subnets   = "yes"
      + ll_addr                     = (known after apply)
      + mac                         = (known after apply)
      + mcast_allow                 = "no"
      + multi_dst_pkt_act           = "bd-flood"
      + name                        = "Vlan_16_BD"
      + name_alias                  = (known after apply)
      + optimize_wan_bandwidth      = "no"
      + relation_fv_rs_ctx          = "uni/tn-terraform-dev/ctx-vrf-terraform-dev"
      + tenant_dn                   = "uni/tn-terraform-dev"
      + unicast_route               = "yes"
      + unk_mac_ucast_act           = "proxy"
      + unk_mcast_act               = "flood"
      + v6unk_mcast_act             = (known after apply)
      + vmac                        = "not-applicable"
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV1_INTPG"] will be created
  + resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + annotation         = "orchestrator:terraform"
      + application_epg_dn = (known after apply)
      + description        = (known after apply)
      + encap              = "vlan-16"
      + id                 = (known after apply)
      + instr_imedcy       = (known after apply)
      + mode               = "regular"
      + primary_encap      = (known after apply)
      + tdn                = "topology/pod-1/protpaths-101-102/pathep-VPC_SRV1_INTPG"
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV2_INTPG"] will be created
  + resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + annotation         = "orchestrator:terraform"
      + application_epg_dn = (known after apply)
      + description        = (known after apply)
      + encap              = "vlan-16"
      + id                 = (known after apply)
      + instr_imedcy       = (known after apply)
      + mode               = "regular"
      + primary_encap      = (known after apply)
      + tdn                = "topology/pod-1/protpaths-101-102/pathep-VPC_SRV2_INTPG"
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV3_INTPG"] will be created
  + resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + annotation         = "orchestrator:terraform"
      + application_epg_dn = (known after apply)
      + description        = (known after apply)
      + encap              = "vlan-16"
      + id                 = (known after apply)
      + instr_imedcy       = (known after apply)
      + mode               = "regular"
      + primary_encap      = (known after apply)
      + tdn                = "topology/pod-1/protpaths-101-102/pathep-VPC_SRV3_INTPG"
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV4_INTPG"] will be created
  + resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + annotation         = "orchestrator:terraform"
      + application_epg_dn = (known after apply)
      + description        = (known after apply)
      + encap              = "vlan-16"
      + id                 = (known after apply)
      + instr_imedcy       = (known after apply)
      + mode               = "regular"
      + primary_encap      = (known after apply)
      + tdn                = "topology/pod-1/protpaths-101-102/pathep-VPC_SRV4_INTPG"
    }

   aci_subnet.subnet will be created
  + resource "aci_subnet" "subnet" {
      + annotation  = "orchestrator:terraform"
      + ctrl        = (known after apply)
      + description = "This subnet is created by terraform"
      + id          = (known after apply)
      + ip          = "10.10.16.1/24"
      + name_alias  = (known after apply)
      + parent_dn   = (known after apply)
      + preferred   = "no"
      + scope       = [
          + "public",
          + "shared",
        ]
      + virtual     = (known after apply)
    }

Plan: 8 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_application_profile.app_profile: Creating...
aci_bridge_domain.bridge_domain: Creating...
aci_application_profile.app_profile: Creation complete after 1s [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP]
aci_bridge_domain.bridge_domain: Creation complete after 3s [id=uni/tn-terraform-dev/BD-Vlan_16_BD]
aci_subnet.subnet: Creating...
aci_application_epg.application_epg: Creating...
aci_subnet.subnet: Creation complete after 2s [id=uni/tn-terraform-dev/BD-Vlan_16_BD/subnet-[10.10.16.1/24]]
aci_application_epg.application_epg: Creation complete after 3s [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV2_INTPG"]: Creating...
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV1_INTPG"]: Creating...
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV4_INTPG"]: Creating...
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV3_INTPG"]: Creating...
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV3_INTPG"]: Creation complete after 0s [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV3_INTPG]]]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV2_INTPG"]: Creation complete after 1s [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV2_INTPG]]]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV1_INTPG"]: Creation complete after 1s [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV1_INTPG]]]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV4_INTPG"]: Creation complete after 1s [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV4_INTPG]]]

Apply complete! Resources: 8 added, 0 changed, 0 destroyed.
$ terraform plan
aci_application_profile.app_profile: Refreshing state... [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP]
aci_bridge_domain.bridge_domain: Refreshing state... [id=uni/tn-terraform-dev/BD-Vlan_16_BD]
aci_subnet.subnet: Refreshing state... [id=uni/tn-terraform-dev/BD-Vlan_16_BD/subnet-[10.10.16.1/24]]
aci_application_epg.application_epg: Refreshing state... [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV2_INTPG"]: Refreshing state... [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV2_INTPG]]]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV4_INTPG"]: Refreshing state... [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV4_INTPG]]]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV3_INTPG"]: Refreshing state... [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV3_INTPG]]]
aci_epg_to_static_path.staic_path_2_computes["VPC_SRV1_INTPG"]: Refreshing state... [id=uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV1_INTPG]]]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

   aci_bridge_domain.bridge_domain has been changed
  ~ resource "aci_bridge_domain" "bridge_domain" {
        id                          = "uni/tn-terraform-dev/BD-Vlan_16_BD"
        name                        = "Vlan_16_BD"
      + relation_fv_rs_bd_flood_to  = []
      + relation_fv_rs_bd_to_out    = []
        # (22 unchanged attributes hidden)
    }
   aci_subnet.subnet has been changed
  ~ resource "aci_subnet" "subnet" {
        id                              = "uni/tn-terraform-dev/BD-Vlan_16_BD/subnet-[10.10.16.1/24]"
      + relation_fv_rs_bd_subnet_to_out = []
        # (8 unchanged attributes hidden)
    }
   aci_application_epg.application_epg has been changed
  ~ resource "aci_application_epg" "application_epg" {
        id                           = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG"
        name                         = "PROJECT2_DEV_EPG"
      + relation_fv_rs_cons          = []
      + relation_fv_rs_cons_if       = []
      + relation_fv_rs_fc_path_att   = []
      + relation_fv_rs_graph_def     = []
      + relation_fv_rs_intra_epg     = []
      + relation_fv_rs_node_att      = []
      + relation_fv_rs_prot_by       = []
      + relation_fv_rs_prov          = []
      + relation_fv_rs_prov_def      = []
      + relation_fv_rs_sec_inherited = []
        # (13 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these
changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV1_INTPG"] must be replaced
-/+ resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + application_epg_dn = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG" # forces replacement
      + description        = (known after apply)
      ~ id                 = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV1_INTPG]]" -> (known after apply)
      ~ instr_imedcy       = "lazy" -> (known after apply)
      ~ primary_encap      = "unknown" -> (known after apply)
      ~ tdn                = "topology/pod-1/protpaths-101-102/pathep-[VPC_SRV1_INTPG]" -> "topology/pod-1/protpaths-101-102/pathep-VPC_SRV1_INTPG" # forces replacement
        # (3 unchanged attributes hidden)
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV2_INTPG"] must be replaced
-/+ resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + application_epg_dn = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG" # forces replacement
      + description        = (known after apply)
      ~ id                 = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV2_INTPG]]" -> (known after apply)
      ~ instr_imedcy       = "lazy" -> (known after apply)
      ~ primary_encap      = "unknown" -> (known after apply)
      ~ tdn                = "topology/pod-1/protpaths-101-102/pathep-[VPC_SRV2_INTPG]" -> "topology/pod-1/protpaths-101-102/pathep-VPC_SRV2_INTPG" # forces replacement
        # (3 unchanged attributes hidden)
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV3_INTPG"] must be replaced
-/+ resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + application_epg_dn = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG" # forces replacement
      + description        = (known after apply)
      ~ id                 = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV3_INTPG]]" -> (known after apply)
      ~ instr_imedcy       = "lazy" -> (known after apply)
      ~ primary_encap      = "unknown" -> (known after apply)
      ~ tdn                = "topology/pod-1/protpaths-101-102/pathep-[VPC_SRV3_INTPG]" -> "topology/pod-1/protpaths-101-102/pathep-VPC_SRV3_INTPG" # forces replacement
        # (3 unchanged attributes hidden)
    }

   aci_epg_to_static_path.staic_path_2_computes["VPC_SRV4_INTPG"] must be replaced
-/+ resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + application_epg_dn = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG" # forces replacement
      + description        = (known after apply)
      ~ id                 = "uni/tn-terraform-dev/ap-PROJECT2_DEV_AP/epg-PROJECT2_DEV_EPG/rspathAtt-[topology/pod-1/protpaths-101-102/pathep-[VPC_SRV4_INTPG]]" -> (known after apply)
      ~ instr_imedcy       = "lazy" -> (known after apply)
      ~ primary_encap      = "unknown" -> (known after apply)
      ~ tdn                = "topology/pod-1/protpaths-101-102/pathep-[VPC_SRV4_INTPG]" -> "topology/pod-1/protpaths-101-102/pathep-VPC_SRV4_INTPG" # forces replacement
        # (3 unchanged attributes hidden)
    }

Plan: 4 to add, 0 to change, 4 to destroy.

### Expected Behavior
On the second Terraform Apply:
No changes. Your infrastructure matches the configuration.

### Actual Behavior
  aci_epg_to_static_path.staic_path_2_computes["VPC_SRV1_INTPG"] must be replaced
-/+ resource "aci_epg_to_static_path" "staic_path_2_computes" {
      + application_epg_dn = (known after apply) # forces replacement
      + description        = (known after apply)
Nothing is changed, so it's not clear why terraform wants to create "application_epg_dn" again and forces replacement to it
### Steps to Reproduce
1. `terraform apply`

**Comment by vaneuk** [comment]
Hi,
Following line
```
tdn = "topology/pod-1/protpaths-101-102/pathep-${each.key}"
```

Should be changed to
```
tdn = "topology/pod-1/protpaths-101-102/pathep-[${each.key}]"
```

**Comment by shrsr** [comment]
@kozhabergenova 
I second @vaneuk's comment. Please change the tdn in "aci_epg_to_static_path" from ` "topology/pod-1/protpaths-101-102/pathep-${each.key}"` to ` "topology/pod-1/protpaths-101-102/pathep-[${each.key}]"`
```
resource "aci_epg_to_static_path" "staic_path_2_computes" {
    application_epg_dn = aci_application_epg.application_epg.id
    for_each = toset(var.vpc_name)
    tdn = "topology/pod-1/protpaths-101-102/pathep-${each.key}"
    encap = "vlan-16"
    mode = "regular"
}
```

**Comment by lhercot** [comment]
Closing as we provided an answer and no response for a week. Feel free to re-open an issue if needed.
