### ISSUE TITLE
aci_application_epg  - Contract relation refresh issue for both prov and cons when changes made outside of Terraform.

### ISSUE THREAD

**Issue by pcshetty** [CiscoDevNet/terraform-provider-aci#556]
Terraform Version
Terraform v0.15.5

provider[registry.terraform.io/ciscodevnet/aci] 0.7.1
APIC version and APIC Platform
Application Policy Infrastructure Controller
Version: 4.2(2e)

Affected Resource(s)
aci_application_epg

Terraform Configuration Files

 resource "aci_application_epg" "barapplication_epg" {
    application_profile_dn  = "uni/tn-TERRAFORM_TEST/ap-APP_CF_XXX_01_TEST"
    name                              = "barapplication_epg"
    relation_fv_rs_cons  = ["uni/tn-TERRAFORM_TEST/brc-CON_XXX_LABONLY_TEST"]
    relation_fv_rs_prov = ["uni/tn-TERRAFORM_TEST/brc-CON_XXX_WEB_INT_VIP"]
    
  }
Debug Output
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aci_application_epg.barapplication_epg has been changed
  ~ resource "aci_application_epg" "barapplication_epg" {
        id                           = "uni/tn-TERRAFORM_TEST/ap-APP_CF_XXX_01_TEST/epg-barapplication_epg"
        name                         = "barapplication_epg"
      ~ relation_fv_rs_cons          = [
          - "uni/tn-TERRAFORM_TEST/brc-CON_XXX_LABONLY_TEST",
        ]
      ~ relation_fv_rs_prov          = [
          - "uni/tn-TERRAFORM_TEST/brc-CON_XXX_WEB_INT_VIP",
        ]
        # (18 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to
these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aci_application_epg.barapplication_epg will be updated in-place
  ~ resource "aci_application_epg" "barapplication_epg" {
        id                           = "uni/tn-TERRAFORM_TEST/ap-APP_CF_XXX_01_TEST/epg-barapplication_epg"
        name                         = "barapplication_epg"
      ~ relation_fv_rs_cons          = [
          + "uni/tn-TERRAFORM_TEST/brc-CON_XXX_LABONLY_TEST",
        ]
      ~ relation_fv_rs_prov          = [
          + "uni/tn-TERRAFORM_TEST/brc-CON_XXX_WEB_INT_VIP",
        ]
        # (18 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

Panic Output
NA

Ignore other contract relationships that are not managed by the terraform config file.
When I rerun the apply or plan again (without any changes to the config file), the output keeps showing 1 to change, if other contracts attached to the EPG are not managed using terraform config.

When no change to the config file, the output should be --->
terraform apply
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Steps to Reproduce
terraform apply
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
terraform apply -refresh=false

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

--

Important Factoids
References
 This issue may be related to this note on the readme files as these are contract relationships? 

----- https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md

NOTE: Currently only resource properties supports the reflecting manual changes made in CISCO ACI. Manual changes to relationship is not taken care by the provider.

**Comment by pcshetty** [comment]
Hi 

Any plan to look into these issues ( 257, 556 and 557.) Also is there any workaround for these issues? 


Thank you
Prathap

**Comment by pcshetty** [comment]
Hi,

Please let us know if any update on this or any dev code we can use to do some testing etc.

Regards,
Prathap

**Comment by lhercot** [comment]
This is the expected behavior.
If you modify a relationship that is explicitly listed as part of a resources in the UI, Terraform will make the change necessary to fix it back to your intent declared in the plan.

You should be able to get around this issue by using the aci_epg_to_contract resources in place of using the relation_fv_rs_cons and relation_fv_rs_prov lists.

Let me know if that resolves your issue.

**Comment by pcshetty** [comment]
thanks for the update.
We are not sure about the comment as the main issue is partial/not so clear diff between what is in the Terraform(TF) config file and the device when the TF plan says there are config changes outside of Terraform.  
We expect if there are four contracts under an EPG in TF config but EPG on a device has five, then Terraform is not showing the contract that is not part of the TF config, is this normal or this will be fixed in the next release?

**Comment by pcshetty** [comment]
also, the strange thing I noticed is sometimes it won't report that there are changes outside of Terraform, it is intermittently reporting this diff between contract relations in TF config and EPG on the device.

**Comment by pcshetty** [comment]
Hi,

Here are some of the screenshots from the Terraform apply.  Basically on the device, I have two provider contracts configured for EPG_Terraform_Deploy_Test_02  but in the terraform config, I only got one uni/tn-TN_SOU_PROD_CF/brc-TEST_CONT_CONS. 

Every time I run apply, I get bellow message and Terraform does not delete the 2nd provider contract to get the device as per the declared state for that EPG nor it reports the diff correctly with the list of the contract not matching the declared state.  it says 1 to change but does not do any change on the device.
What should be the exact behaviour in the senario? 
I think this issue applies similar relationships in  Ext EPG and contract subjects.

everytime it report this ( which is in the config)
**~ relation_fv_rs_prov          = [
          + "uni/tn-TN_SOU_PROD_CF/brc-TEST_CONT_CONS",**
        ]

----------
![image](https://user-images.githubusercontent.com/66314205/136753061-2c96e328-045a-4b72-b349-18f24d8bd48b.png)
![image](https://user-images.githubusercontent.com/66314205/136753115-1fb2faeb-a4b5-4cc3-818b-c0bd2ab9b760.png)
-----------------------------
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aci_application_epg.EPG_Terraform_Deploy_Test_02-APP_CF_OBO_01-TN_SOU_PROD_CF has been changed
  ~ resource "aci_application_epg" "EPG_Terraform_Deploy_Test_02-APP_CF_OBO_01-TN_SOU_PROD_CF" {
        id                           = "uni/tn-TN_SOU_PROD_CF/ap-APP_CF_OBO_01/epg-EPG_Terraform_Deploy_Test_02"
        name                         = "EPG_Terraform_Deploy_Test_02"
      ~ relation_fv_rs_prov          = [
          - "uni/tn-TN_SOU_PROD_CF/brc-TEST_CONT_CONS",
        ]
        # (21 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan
may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aci_application_epg.EPG_Terraform_Deploy_Test_02-APP_CF_OBO_01-TN_SOU_PROD_CF will be updated in-place
  ~ resource "aci_application_epg" "EPG_Terraform_Deploy_Test_02-APP_CF_OBO_01-TN_SOU_PROD_CF" {
        id                           = "uni/tn-TN_SOU_PROD_CF/ap-APP_CF_OBO_01/epg-EPG_Terraform_Deploy_Test_02"
        name                         = "EPG_Terraform_Deploy_Test_02"
      **~ relation_fv_rs_prov          = [
          + "uni/tn-TN_SOU_PROD_CF/brc-TEST_CONT_CONS",**
        ]
        # (21 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aci_application_epg.EPG_Terraform_Deploy_Test_02-APP_CF_OBO_01-TN_SOU_PROD_CF: Modifying... [id=uni/tn-TN_SOU_PROD_CF/ap-APP_CF_OBO_01/epg-EPG_Terraform_Deploy_Test_02]
aci_application_epg.EPG_Terraform_Deploy_Test_02-APP_CF_OBO_01-TN_SOU_PROD_CF: Modifications complete after 1s [id=uni/tn-TN_SOU_PROD_CF/ap-APP_CF_OBO_01/epg-EPG_Terraform_Deploy_Test_02]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

**Comment by pcshetty** [comment]
FYI - related to the same issues updated in-place also does not report the changes to the relationships, ie. below diff is not correct it says it deleting  4 contracts but I am only deleting the one contract relationship in the config file.
I want to delete cont relationships but i get below plan output --
- "uni/tn-TN_XXX_PROD_CF/brc-CON_XXX_SB"    


Plan output -- 

aci_application_epg.EPG_CF_MICROSERVICE_PROXY_XXX_01-APP_XXX_XXX_01-TN_XX_XXX_XX will be updated in-place
  ~ resource "aci_application_epg" "EPG_CF_MICROSERVICE_PROXY_XX_01-APP_xX_XXX_01-TN_XXX_XX_CF" {
        id                           = "uni/tn-TN_XXX_XXX_CF/ap-APP_XXX_XXX_01/epg-EPG_CF_MICROSERVICE_PROXY_XX_01"
        name                         = "EPG_CF_MICROSERVICE_PROXY_XXX_01"
      ~ relation_fv_rs_cons          = [
          - "uni/tn-TN_XXX_PROD_CF/brc-CON_XXX_NB",
          - "uni/tn-TN_XXX_PROD_CF/brc-CON_XXX_VIP",
          - "uni/tn-TN_SXX_PROD_CF/brc-CON_XXX_VIP2",
          - "uni/tn-TN_XXX_PROD_CF/brc-CON_XXX_SB"           
        ] -> (known after apply)
        # (21 unchanged attributes hidden)
    }

**Comment by pcshetty** [comment]
Hi,

Any update on this bug fix?

Thanks 
Prathap

**Comment by dpeachey** [comment]
Hi,

I'm also experiencing a problem with this, the diff is not correct for the 'relation_fv_rs_cons' and 'relation_fv_rs_prov' attributes meaning that the TF plan output is not correct, so you cannot see properly which contracts are being added or removed. I'm also only talking here about contracts that are added/removed through Terraform, not on the device itself. 

Is this planned to be fixed?

Thanks,

Dan

**Comment by lhercot** [comment]
We will be looking at it but it is not top of the priority list as you can use the aci_epg_to_contract resource to avoid using those module attributes.

**Comment by dpeachey** [comment]
The 'aci_epg_to_contract' resource does provide quite the same functionality - you lose the ability to see config drift, when a contract was added or removed on the device, outside of the Terraform workflow, so the use of 'relation_fv_rs_cons' and 'relation_fv_rs_prov' is preferable.

**Comment by lhercot** [comment]
This issue has been fixed in v2.0.0. The current behavior is that if you use the relation_fv_rs_prov or relation_fv_rs_cons Terraform will remove any contract relationship that is added manually and not present in this relation and if you use the aci_epg_to_contract, it will only manipulate those contracts. If you find any issue that does not comply to this behavior. Feel free to reopen an issue.
