### ISSUE TITLE
aci_contract_subject - filter relation refresh issue when changes made outside of Terraform

### ISSUE THREAD

**Issue by pcshetty** [CiscoDevNet/terraform-provider-aci#557]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform Version
Terraform v0.15.5

provider[registry.terraform.io/ciscodevnet/aci] 0.7.1

### APIC version and APIC Platform

APIC version and APIC Platform
Application Policy Infrastructure Controller
Version: 4.2(2e)

### Affected Resource(s)

aci_contract_subject

### Terraform Configuration Files

```json
{
    "resource": {
        "aci_contract_subject": {
          
            "SBJ_TCP_80-CON_xxx_MICROSERVICES_PROXY_VIP-TN_xxx_PROD_CF": {
                "contract_dn": "${aci_contract.CON_xxx_MICROSERVICES_PROXY_VIP-TN_xxx_PROD_CF.id}",
                "description": "xx",
                "name": "SBJ_TCP_80",
                "relation_vz_rs_subj_filt_att": [
                    "uni/tn-common/flt-TCP_80"
                ]
            }
    }
   }
}


```

### Debug Output

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aci_contract_subject.SBJ_TCP_80-CON_xxx_MICROSERVICES_PROXY_VIP-TN_xxx_PROD_CF has been changed
  ~ resource "aci_contract_subject" "SBJ_TCP_80-CON_xxx_MICROSERVICES_PROXY_VIP-TN_xxx_PROD_CF" {
        id                           = "uni/tn-TN_xxx_PROD_CF/brc-CON_xxx_MICROSERVICES_PROXY_VIP/subj-SBJ_TCP_80"
        name                         = "SBJ_TCP_80"
      ~ relation_vz_rs_subj_filt_att = [
          - "uni/tn-common/flt-TCP_80",
        ]
        # (8 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to
these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aci_contract_subject.SBJ_TCP_80-CON_xxx_MICROSERVICES_PROXY_VIP-TN_xxx_PROD_CF will be updated in-place
  ~ resource "aci_contract_subject" "SBJ_TCP_80-CON_xxx_MICROSERVICES_PROXY_VIP-TN_xxx_PROD_CF" {
        id                           = "uni/tn-TN_xxx_PROD_CF/brc-CON_xxx_MICROSERVICES_PROXY_VIP/subj-SBJ_TCP_80"
        name                         = "SBJ_TCP_80"
      ~ relation_vz_rs_subj_filt_att = [
          + "uni/tn-common/flt-TCP_80",
        ]
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Panic Output

NA

### Expected Behavior

Ignore other filter relationships that are not managed by the terraform config file.  Basically, another filter TCP_443 is added outside of Terraform config & state file. i.e  via UI etc
-- | --
When no change to the config file, the output should be --->
terraform apply
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

### Actual Behavior
terraform apply
Plan: 0 to add, 1 to change, 0 to destroy.

### Steps to Reproduce

terraform apply
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
terraform apply -refresh=false
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

1. `terraform apply`

### References

This issue may be related to this note on the readme files as these are contract relationships?

----- https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md

NOTE: Currently only resource properties supports the reflecting manual changes made in CISCO ACI. Manual changes to relationship is not taken care by the provider.

* #0000

**Comment by lhercot** [comment]
This is the expected behavior.
If you modify a relationship that is explicitly listed as part of a resources in the UI, Terraform will make the change necessary to fix it back to your intent declared in the plan.

We could go around this limitation by introducing a dedicated resources like aci_contract_subject_to_filter so you will not explicitly declare all relationships in aci_contract_subject. You could also look at ignore_changes as proposed by the terraform binary.

As a best practice, you should avoid making changes to Terraform managed objects in UI or make the appropriate equivalent changes back to your Terraform plan.

**Comment by pcshetty** [comment]
Hi,

Any update on this bug fix?

Thanks 
Prathap

**Comment by lhercot** [comment]
This issue has been fixed in v2.0.0. Please check and feel free to re-open the issue if needed.

**Comment by pcshetty** [comment]
Thank you. i will test and let you know if any issues.

**Comment by pcshetty** [comment]
@lhercot  thanks for the udpate. Now it removes contract relationships that are not in the config but if the list is empty in the config and there are contracts attached to the EPG on the device it won't remove them.

Example: In TF config file ===
        "relation_fv_rs_prov": [ ],                
         "relation_fv_rs_cons": [ ]

but on the device, we have some redudent contracts attached to the EPG, which we wanted to cleanup but the v2.0.0 provider won't remove them. 
BTW this relationships clean-up issue is also seen in the subject filter and External EPG contract relationships, if the list is empty in the config file then clean up does not work. 

Do you want me to open a new ticket?
