### ISSUE TITLE
When you create an EPG from a terraform module, it want to re-create EPG randomly while it already exist.

### ISSUE THREAD

**Issue by qfaure** [CiscoDevNet/terraform-provider-aci#566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Tested all this terraform version :
* v0.15.0
* v.1.0.0
* v.1.0.1
* v.1.0.2
* v.1.0.3

ACI provider version :
* 0.7.0
* 0.7.1

### APIC version and APIC Platform

* Version 4.1(1k) - https://sandboxapicdc.cisco.com/

### Affected Resource(s)

* aci_application_epg

### Terraform Configuration Files

I have create a local module for creating 1 EPG.

Module code:
```hcl
resource "aci_application_epg" "this" {
  name                   = var.epg_name
  application_profile_dn = var.application_profile
  relation_fv_rs_bd      = var.bridge_domain
  description            = "%s"
  annotation             = "orchestrator:terraform"
  exception_tag          = "0"
  flood_on_encap         = "disabled"
  has_mcast_source       = "no"
  is_attr_based_epg      = "no"
  match_t                = "AtleastOne"
  pc_enf_pref            = "unenforced"
  pref_gr_memb           = "exclude"
  prio                   = "unspecified"
  shutdown               = "no"
}
```
code that call the module  ( 1 tf file per EPG)
```hcl
module "vlan-1-epg" {
  source              = "../../modules/epg"
  tenant_id           = module.aci_tenant.tenant-id
  application_profile = module.aci_tenant.applications_profiles["DEV-APP"]
  bridge_domain       = aci_bridge_domain.VLAN_1_BD.id
  domains             = ["uni/phys-MY_PHYSICAL_DOMAIN"]
  epg_name            = "VLAN-1-EPG"
  epg-gtw-scope       = ["public", "shared"]
  epg-gtw             = "10.X.X.X./24"
}
```

Do it for EPG  2, 3 , 4 , 5 , 6...
In order to reproduce the bug , create more than 4/ 5 files , one for each EPG.
### Expected Behavior

EPG are created, nothing expected to be plan / apply.

### Actual Behavior

When launching terraform plan/apply,  it's randomly want to re-create existing EPG. All EPG are is the tfstate but plan / apply want to recreate it... This behavior is only on EPG ressource, doing this for bridge_domain, filter, filter_entry working as expected.

### Steps to Reproduce
⚠️ This code is only an example to reproduce the behaviour. It does not contain any good practices.

1. Get code in zip
2. Unzip in the same folder.
3. Add sandbox password in the provider block in both demo folder and modules folder.
4. `tterraform plan`t  in order to see that it will create :
  * 1 Tenant, 
  * 1 VRF,
  * 1 APP-PROFILE
  * 6 EPG and 6 Bridge domain.
4. `terraform apply`
5. one all it's created, exec  `tterraform plan` again (sometimes it will say that there is not changes)
 repeat `tterraform plan` several times
6. Terraform will say : EPG-X need to be created while it already exist.
[aci-demo.zip](https://github.com/CiscoDevNet/terraform-provider-aci/files/7032956/aci-demo.zip)

**Comment by qfaure** [comment]
Hi @lhercot  do you have some update on this issue please?

**Comment by shrsr** [comment]
@qfaure I just went through your TF configuration files. We don't need to provide passwords for both provider blocks in demo and modules folder. Please update the tenant.tf with your password in the demo folder. The provider.tf in the modules folder just needs the following source address.

```
terraform {
  required_providers {
    aci = {
      source = "ciscodevnet/aci"
      version = "0.7.1"
    }
  }
}
```
Can you please try running TF again. I have attached the zip file.
[aci-demo.zip](https://github.com/CiscoDevNet/terraform-provider-aci/files/7394224/aci-demo.zip)

**Comment by lhercot** [comment]
Closing this issue as we have not heard back. If the issue is still there after our solution proposition, feel free to reopen the issue.

**Comment by qfaure** [comment]
Hi @shrsr  and @lhercot,
sorry for the delay of my answer. It"s seems that solved the issue but it's very a strange behavior.
Thanks
