### ISSUE TITLE
adding multiple domains with aci_epg_to_domain not possible

### ISSUE THREAD

**Issue by lennartjung** [CiscoDevNet/terraform-provider-aci#581]
Hi,

I am trying to add multiple domains to an EPG using the resource "aci_epg_to_domain", however this does not seem to be possible using e.g. a set [] - apologies, if I am mistaken.

The ACI policy model states clearly EGP:DOMAIN as 1:N (https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/policy-model-guide/b-Cisco-ACI-Policy-Model-Guide.html#id_107454) 

however the documentation of the provider only gives the option to use a tdn (tdn - (Required) Distinguished Name of Target Domain object. / 
 https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/epg_to_domain)

Is there another way to add multiple domains to an EPG?

**Comment by lhercot** [comment]
You need to define one resource of time epg_to_domain per domain you want to associate to an EPG.
If you want to pass a list of domains for a specific EPG, you should create a Terraform module that takes the list and output domains. 

This would be very similar to this modules: https://github.com/CiscoDevNet/terraform-mso-modules/tree/main/mso_schema_site_anp_epg_static_ports

Let us know if that solves your issue.

**Comment by lhercot** [comment]
Closing as we did not hear back and provided a solution. Feel free to reopen an issue if needed.
