### ISSUE TITLE
ESG related issues

### ISSUE THREAD

**Issue by mihiguch** [CiscoDevNet/terraform-provider-aci#592]
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/end_point_security_group
1: Left pane says “aci_end_point_security_group” but the right pane says “aci_endpoint_security_group”. I think the left one should be corrected. Same for aci_endpoint_security_group_selector.

2: VRF is mandatory configuration for ESG (it’s like bd configuration for EPG) but it’s optional in the argument reference. VRF relationship configuration should be mandatory.
And also, it should be listed just after “name” instead of in the bottom of the configuration. (at first, I didn’t recognize that VRF relationship configuration exists in the example)
 
3: At ESG, we don’t have couple of options that exist on EPG, but these are listed in argument reference. I think these should be removed from code and doc as it’s not applicable to ESG in general.
resource "aci_endpoint_security_group" "example" {
  application_profile_dn  = aci_application_profile.example.id
  name  = "example"
  annotation = "orchestrator:terraform"
  flood_on_encap = "disabled"             <<< ESG doesn’t have flood in encap option
  match_t = "AtleastOne"
  pc_enf_pref = "unenforced"
  pref_gr_memb = "exclude"
  prio = "unspecified"                    <<< ESG doesn’t have QoS class configuration at EPG level
 
  fv_rs_cons {
    prio = "unspecified"
    target_dn = aci_resource.example.id
  }
 
  fv_rs_cons_if {
    prio = "unspecified"
    target_dn = aci_resource.example.id
  }
 
  fv_rs_cust_qos_pol = aci_resource.example.id
 
  fv_rs_intra_epg = [aci_resource.example.id]
 
  fv_rs_prov {
    match_t = "AtleastOne"
    prio = "unspecified"
    target_dn = aci_resource.example.id
  }
 
  fv_rs_scope = aci_resource.example.id   <<< It seems this is the one for VRF association, but it’s explained as “optional” It should be mandatory. And also, it should be “relation_fv_rs_scope” instead of “fv_rs_scope”. I think others should be corrected too.
 
  fv_rs_sec_inherited = [aci_resource.example.id] 
}
 
 
4: It seems we currently support IP selector only.
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/end_point_security_group_selector
APIC currently support EPG selector and Tag selector. It would be nice to support Tag and EPG selectors.
 

5: Regarding data-source end_point_security_group_selector, the doc doesn’t mention “name”, but it complains “name” is mandatory when I issues “terraform apply”. Is “name” mandatory? Then, can you update the doc? https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/data-sources/end_point_security_group_selector
 
MIHIGUCH-M-826T:Create_tenant mihiguch$ terraform apply
╷
│ Error: Missing required argument
│ 
│   on main.tf line 151, in data "aci_endpoint_security_group_selector" "esg1_selector":
│  151: data "aci_endpoint_security_group_selector" "esg1_selector" {
│ 
│ The argument "name" is required, but no definition was found.
╵

**Comment by lhercot** [comment]
Please check v1.0.1. It should have all those issues fixed including new resources and datasources for ESG Tag Selector and ESG EPG Selector.

See documentation for the other requested changes.
