### ISSUE TITLE
aci_vmm_domain - syntax in documentation is wrong

### ISSUE THREAD

**Issue by vanniew** [CiscoDevNet/terraform-provider-aci#621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.1
+ provider registry.terraform.io/hashicorp/vsphere v2.0.2

### APIC version and APIC Platform

* v5.2.2e

### Affected Resource(s)

* aci_vmm_domain

### Terraform Configuration Files
Terraform Registry Documentation is wrong - Below is the syntax in the documentation
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/data-sources/vmm_domain

data "aci_vmm_domain" "dev_vmmdom" {
  provider_profile_dn  = "${**aci_provider_profile.**example.id}"
  name                 = "demo_vmmdomp"
}

### Debug Output

NA

### Panic Output

NA

### Actual Behavior

I was unable to provide the required parameter provider_profile_dn. Aci_provider_profile resource (required parameter to create aci_vmm_domain.xxx.id) does not exist in the ACI terraform provider and documentation. Experimented with various possibilities to complete provider_profile_dn. https://terra-lab.ciscolive.com/lab/pod20/part3/tenant describes the correct procedure/syntax to create the object.

Below Terraform HCL code worked. The code sample in the official terraform documentation is not working. 

data "aci_vmm_domain" "eu-spdc-cdc" {
    provider_profile_dn  = "**/uni/vmmp-VMware**"
    name                 = "demo_vmmdomp"
}

### Steps to Reproduce

Create an EPG to VMM Domain binding using the documentation.
1. Create aci_application_epg resource. https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/application_epg
2. Create aci_vmm_domain data source **(This step fails if using the snippet provided in the documentation. This step passes if you use the snippet specified in "Actual Behavior" above)**
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/data-sources/vmm_domain
3. Create aci_epg_to_domain resource. 
https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/data-sources/epg_to_domain

1. `terraform apply`

NA

### References

NA

**Comment by anvitha-jain** [comment]
@vanniew,

The dn map for provider_profile_dn is updated in the PR #625 and will also be updated in the registry with the release of next version.
| Vendor              | provider_profile_dn         |
| -----------        | -----------                       |
| Microsoft          |  uni/vmmp-Microsoft       |
| CloudFoundry  | uni/vmmp-CloudFoundry |
| OpenShift         | uni/vmmp-OpenShift       |
| OpenStack       | uni/vmmp-OpenStack      |
| VMware            | uni/vmmp-VMware           |
| Kubernetes      | uni/vmmp-Kubernetes      |
| Redhat             |  uni/vmmp-Redhat            |

**Comment by vanniew** [comment]
Thanks for updating.
