### ISSUE TITLE
Idempotency problem with relation_fv_rs_prov in aci_application_epg

### ISSUE THREAD

**Issue by aj-cruz** [CiscoDevNet/terraform-provider-aci#627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.1

### APIC version and APIC Platform
V 5.1(4c) on-prem (simulator)

### Affected Resource(s)
aci_application_epg
    relation_fv_rs_prov
    
(I tested relation_fv_rs_cons and confirmed it is not affected by this)

### Terraform Configuration Files

```hcl
resource "aci_application_epg" "epg" {
  for_each               = var.application_epgs
  name                   = each.value.name
  annotation             = each.value.annotation
  application_profile_dn = "uni/tn-${each.value.tenant}/ap-${each.value.application}"
  pref_gr_memb           = each.value.pref_gr_memb
  relation_fv_rs_bd      = "uni/tn-${each.value.tenant}/BD-${each.value.bridge_domain}"
  relation_fv_rs_prov = [
    for con in each.value.provided_contracts: 
      "uni/tn-%{if length(regexall("common-", con)) > 0}common%{else}${each.value.tenant}%{endif}/brc-${trimprefix(con, "common-")}"
  ]
}
```

### Expected Behavior
Resource created, subsequent runs have zero changes.

### Actual Behavior
```
Terraform will perform the following actions:

  # module.application-epgs.aci_application_epg.epg["epg1"] will be updated in-place
  ~ resource "aci_application_epg" "epg" {
        id                           = "uni/tn-MyTenant-1/ap-Prod-App/epg-Web-EPG"
        name                         = "Web-EPG"
      ~ relation_fv_rs_graph_def     = [
          - "uni/tn-common/brc-default/graphcont",
        ]
        # (19 unchanged attributes hidden)
    }

  # module.application-epgs.aci_application_epg.epg["epg2"] will be updated in-place
  ~ resource "aci_application_epg" "epg" {
        id                           = "uni/tn-MyTenant-1/ap-Prod-App/epg-App-EPG"
        name                         = "App-EPG"
      ~ relation_fv_rs_graph_def     = [
          - "uni/tn-common/brc-default/graphcont",
        ]
        # (19 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The create operation on relation_fv_rs_prov appears to be adding:
`relation_fv_rs_graph_def     = [
          "uni/tn-common/brc-default/graphcont",
        ]`

I tried hard-coding it empty in the resource but I get the same behavior

### References

* #0000

**Comment by lhercot** [comment]
This issue has been fixed in v2.0.0. Please check and feel free to re-open the issue if needed.
