### ISSUE TITLE
Implement read in the aci_rest resource type

### ISSUE THREAD

**Issue by jblackman** [CiscoDevNet/terraform-provider-aci#652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aci_rest` resource type currently does not implement Read. The impact is that we cannot control drift, for example if somebody manually deletes such a managed resource, then the next Terraform run will not detect and correct this.

@danischm used issue #230 to correct this, but then closed it without merging and replaced it with PR #355. This PR is still open, but introduces a new `managed_rest_resource`. I'm not sure why, as he did not mention this in the PR. Perhaps it expects `aci_rest` to be used for non-managed REST resources, but that seems a bit contradictory.

I would like to propose to resurrect the idea of adding Read to the `aci_rest` resource type - effectively to resurrect #230. Does anybody have a strong opinion why not to do this?

### New or Affected Resource(s) + ACI Class(es):

* aci_rest

### APIC version and APIC Platform

* all

### References

* #230
* #355

**Comment by jblackman** [comment]
Raised PR #663 to resurrect the change.

**Comment by lhercot** [comment]
This should be addressed by the PR #781 which introduce aci_rest_managed with full state management.
