### ISSUE TITLE
 Error: Plugin did not respond

### ISSUE THREAD

**Issue by samfaslogcisco** [CiscoDevNet/terraform-provider-aci#746]
Error: The terraform-provider-aci_v1.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

╷
│ Error: Plugin did not respond
│
│   with aci_bridge_domain.external_tf,
│   on main.tf line 37, in resource "aci_bridge_domain" "external_tf":
│   37: resource "aci_bridge_domain" "external_tf" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aci_v1.0.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0xe39bec]

goroutine 196 [running]:
github.com/terraform-providers/terraform-provider-aci/aci.resourceAciBridgeDomainRead(0x13bfca0, 0xc00042efc0, 0xc0004d2000, 0x11fb760, 0xc000391ec0, 0xc0004c1de0, 0xc00041d8f0, 0x40cbc8)
        github.com/terraform-providers/terraform-provider-aci/aci/resource_aci_fvbd.go:1069 +0x16c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000fe900, 0x13bfc20, 0xc0001dfac0, 0xc0004d2000, 0x11fb760, 0xc000391ec0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:297 +0x1ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000fe900, 0x13bfc20, 0xc0001dfac0, 0xc0000a7650, 0x11fb760, 0xc000391ec0, 0xc0007a34d0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:564 +0x1c2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00024b7c0, 0x13bfc20, 0xc0001dfac0, 0xc0001dfb00, 0xc0001dfac0, 0x1187920, 0x11b91c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:575 +0x42f
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00016a860, 0x13bfc20, 0xc0001dfac0, 0xc00042ec60, 0xc00016a860, 0xc000453020, 0xc0001bbba0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x101
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x11b91c0, 0xc00016a860, 0x13bfce0, 0xc000453020, 0xc00042ec00, 0x0, 0x13bfce0, 0xc000453020, 0xc000486000, 0x408)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00016ec40, 0x13cd4a0, 0xc0002ffe00, 0xc0001e5000, 0xc000106b10, 0x1b75cf0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc00016ec40, 0x13cd4a0, 0xc0002ffe00, 0xc0001e5000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000038510, 0xc00016ec40, 0x13cd4a0, 0xc0002ffe00, 0xc0001e5000)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x204

Error: The terraform-provider-aci_v1.0.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by shrsr** [comment]
@samfaslogcisco I was unable to reproduce the issue by using my TF configuration file.
Can you please provide the entire TF file that's causing this issue at your end? This will help us debug the issue.

**Comment by shrsr** [comment]
@samfaslogcisco Can you also let me know the APIC version you are using against the TF file?

**Comment by samfaslogcisco** [comment]
Hi @shrsr , 
The APIC version is 5.2(2h).
Attaching the TF file,
![main tf](https://user-images.githubusercontent.com/83404954/146478521-d0b5a4a2-87ff-46ab-9347-c0fe5b9021c5.GIF)

**Comment by shrsr** [comment]
@samfaslogcisco I'm unable to access the file. Can you please send it again in a different format?

**Comment by adealdag** [comment]
I have just opened an issue that might be a duplicated of this. @shrsr you can take my config from there

https://github.com/CiscoDevNet/terraform-provider-aci/issues/768

**Comment by shrsr** [comment]
@samfaslogcisco Please share the configuration that caused the crash.

**Comment by samfaslogcisco** [comment]
> 

https://user-images.githubusercontent.com/83404954/150532072-da07b8a5-2a48-4974-9564-ab1c84375e49.MOV

Please remove the .MOV at the end of the file
