### ISSUE TITLE
aci_filter_entry  missing expected [ when upgrading provider from 0.7.1 to 1.0.1

### ISSUE THREAD

**Issue by qfaure** [CiscoDevNet/terraform-provider-aci#754]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version 1.04

### APIC version and APIC Platform

* Version: 5.1(4c) on premise

### Affected Resource(s)

* aci_filter_entry

### Terraform Configuration Files

Current filter working on version 0.7.1. Now trying to upgrade to the version 1.0.1 of the provider.
```hcl
resource "aci_filter" "all" {
  tenant_dn   = aci_tenant.dev.id
  description = ""
  name        = "all"
  annotation  = "orchestrator:terraform"
}


resource "aci_filter_entry" "all" {
  filter_dn     = aci_filter.all.id
  description   = ""
  name          = "all"
  annotation    = "orchestrator:terraform"
  ether_t       = "ipv4"
}

```

### Debug Output
Error: missing expected [.

So regarding the release changes of the aci provider( breaking changes on aci_filter_entry) try to update my code with :
```hcl
resource "aci_filter" "all" {
  tenant_dn   = aci_tenant.dev.id
  description = ""
  name        = "all"
  annotation  = "orchestrator:terraform"
}


resource "aci_filter_entry" "all" {
  filter_dn     = aci_filter.all.id
  description   = ""
  name          = "all"
  annotation    = "orchestrator:terraform"
  ether_t       = "ipv4"
  tcp_rules     = ["unspecified"]
}

```

Same result.
### Expected Behavior

No changes on the filter entry with tcp rules with default value.

### Actual Behavior

Error during terraform plan : 
missing [ .

### Steps to Reproduce

Having provider with 0.7.1 and trying to upgrade to latest version.

terraform init -upgrade 
terraform plan 

Filter entry will failed with tcp rules on default value.

**Comment by oldguardmd** [comment]
Looks like this got broken during V2 migration (#507)?

https://github.com/CiscoDevNet/terraform-provider-aci/commit/f269251ef69c3150e3dc62043017e88e6568fb0d

**Comment by lhercot** [comment]
When upgrading to a new release please always check the changelog: https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/CHANGELOG.md

You are probably hitting the BREAKING CHANGE on "Fix tcp_rules from string to list in aci_filter_entry"

At your own risk, you can try to edit your state file to replace the string tcp_rules to a list of strings.

**Comment by oldguardmd** [comment]
That makes sense now that I understand what you are saying. Because I upgraded from 0.7.1 to 1.2.0, the terraform.tfstate file had references to the tcp_rules in string format, not list format. Modifying the terraform.tfstate file to change tcp_rules to a list corrected the issue.

            "tcp_rules": ["unspecified"]

I also found that if I just removed the following: 
- terraform.tfstate
- terraform.lock.hcl
- .terraform (Entire directory)
I get a good state file and don't have the issue after doing init and apply. The state file is created without the inconsistencies that cause the issue after upgrading. 

Not sure which is the best workaround for most users, but my guess is if they want to ensure the state is preserved in terraform, they need to edit the state file.

Appreciate the help sorting this out.

**Comment by lhercot** [comment]
Another possible way to resolve is to execute the following commands:
```
terraform state rm aci_filter_entry.all
terraform import aci_filter_entry.all dn_of_your_filter_entry

**Comment by DimmySa** [comment]
Thank You for getting back to us.
Upgrade/Modify the provider version from 0.7.1 to 1.0.1
&
After having transformed the string to a list ("tcp_rules": ["unspecified"]) we got the following error for all the resources 

Error: Plugin did not respond
11:15:01 │
11:15:01 │ with aci_bridge_domain.vlan_1522_bd,
11:15:01 │ on vlan-1522-bd.tf line 1, in resource "aci_bridge_domain" "vlan_1522_bd":
11:15:01 │ 1: resource "aci_bridge_domain" "vlan_1522_bd" {
11:15:01 │
11:15:01 │ The plugin encountered an error, and failed to respond to the
11:15:01 │ plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may
11:15:01 │ contain more details.
11:15:01 ╵
11:15:01 ╷
11:15:01 │ Error: Request cancelled
11:15:01 │
11:15:01 │ with aci_bridge_domain.vlan_1523_bd,
11:15:01 │ on vlan-1523-bd.tf line 1, in resource "aci_bridge_domain" "vlan_1523_bd":
11:15:01 │ 1: resource "aci_bridge_domain" "vlan_1523_bd" {

**Comment by lhercot** [comment]
Where you able to fix the issue?

**Comment by lhercot** [comment]
I will close this issue as I did not hear back from my response of Dec 17th. Feel free to comment back if you want it to be reopened or open a new issue.

**Comment by qfaure** [comment]
Yes in my case we fix by changing the tfstate. Issue can be close for me. Thanks
