### ISSUE TITLE
Macos M1 chipset

### ISSUE THREAD

**Issue by francesco-supportlan** [CiscoDevNet/terraform-provider-aci#765]
Hi,

Is there a plan to get the provider working with Apple M1 chip?

Right now, I'm getting the following error when trying to init my terraform when using my mac:

Error: Incompatible provider version
│
│ Provider registry.terraform.io/ciscodevnet/aci v1.0.1 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this
│ provider may have different platforms supported.

I was using m1-terraform-provider-helper but not working yet with monterey 12.0.1 (issue was already opened).

Thanks

**Comment by yannickvranckx** [comment]
Any progress on this issue, i am running into the same issue. Would be kind of a pain having to maintain 2 terraform versions for this.

**Comment by lhercot** [comment]
To the best of my knowledge, this requires an upgrade of the Golang version we are currently building with.
To limit the introduction of regressions with that Golang version upgrade, we are working on increasing our automated testing capabilities. Once those items are done we will look at releasing an official version with M1 support.

Feel free to start testing by building the provider with a newer version of Golang.

A temporary workaround is to run the terraform binary in a local linux container.

**Comment by dafjedavid** [comment]
Seen this issue before. Works fine on my Apple Macbook Air M1. Installed terraform under brew and package tfenv.

**Comment by yannickvranckx** [comment]
> Seen this issue before. Works fine on my Apple Macbook Air M1. Installed terraform under brew and package tfenv.

You are most likely using the amd64 with Rosetta. This works some of the time, but i have seen this generate weird errors as well. 
I just installed the package via Brew and you get the same exact error.

**Comment by cubinet-code** [comment]
I would also appreciate if the provider could be built for darwin_arm64 and published to the repository.
It works fine if build locally and used locally.

```
provider_installation {
  dev_overrides {
    "registry.terraform.io/hashicorp/aci" = "./plugins"
  }

  direct {}
}
```

```
% ls ./plugins 
terraform-provider-aci_v2.0.0_x3
```

**Comment by lhercot** [comment]
Please try v2.2.0 which was published yesterday and should have the darwin arm64 binaries. I do not have a M1 Mac so I am unable to test it.

Let us know if there are any issues with it.

**Comment by lhercot** [comment]
@francesco-supportlan @yannickvranckx @cubinet-code Any of you able to test this?

**Comment by francesco-supportlan** [comment]
Planned to test it over the weekend. I'll keep you posted

**Comment by cubinet-code** [comment]
Yes, works for me on a M1 Macbook Pro now. Excellent. Thank you very much Lionel! 

`Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
oliverf@mbp-m1 test % terraform version
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/ciscodevnet/aci v2.2.1
`

**Comment by francesco-supportlan** [comment]
Works for me on m1 macbook pro. Thanks!
