### ISSUE TITLE
Static VLAN Pool and Dynamic Range issue.

### ISSUE THREAD

**Issue by M7Fa** [CiscoDevNet/terraform-provider-aci#772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v1.0.11

### APIC version and APIC Platform

* On-prem Version 4.2(7f)

### Affected Resource(s)

* aci_vlan_pool 
* aci_ranges

### Terraform Configuration Files

```hcl
resource "aci_vlan_pool" "aci_static_vlanpool" {
  name        = "aci-static-vlanpool"
  alloc_mode  = "static"
}

resource "aci_ranges" "vlan_pool_static" {
  vlan_pool_dn = aci_vlan_pool.aci_static_vlanpool.id
  from         = "vlan-100"
  to           = "vlan-101"
  alloc_mode   = "dynamic"
  role         = "external"
}
```

### Panic Output
Error: The allocMode of Encap 100-101 block should match the namespace or be set to inherit
│
│   with aci_ranges.vlan_pool_static["range1"],
│   on 03c_fabric_accesspol.tf line 142, in resource "aci_ranges" "vlan_pool_static":
│  142: resource "aci_ranges" "vlan_pool_static" {
│

### Expected Behavior
A Static VLAN Pool Created with a Dynamic Range of VLAN from Vlan100 to 101.

### Actual Behavior
VLAN Pool Created.  Ranges in pool were not created.

### Steps to Reproduce

1. `terraform plan`
```
$ terraform.exe plan -out test.tfplan 

  # aci_ranges.vlan_pool_static["range1"] will be created
  + resource "aci_ranges" "vlan_pool_static" {
      + alloc_mode   = "dynamic"
      + annotation   = "orchestrator:terraform"
      + description  = "from terraform"
      + from         = "vlan-100"
      + id           = (known after apply)
      + name_alias   = (known after apply)
      + role         = "external"
      + to           = "vlan-101"
      + vlan_pool_dn = (known after apply)
    }


  # aci_vlan_pool.aci_vmm_dynamic_vlanpool will be created
  + resource "aci_vlan_pool" "aci_vmm_dynamic_vlanpool" {
      + alloc_mode  = "static"
      + annotation  = "orchestrator:terraform"
      + description = "from terraform"
      + id          = (known after apply)
      + name        = "aci_vmm_dynamic_vlanpool"
      + name_alias  = (known after apply)
    }

```
2. `terraform apply`
```
$ terraform.exe apply test.tfplan 
aci_vlan_pool.aci_vmm_dynamic_vlanpool: Creating...
aci_vlan_pool.aci_vmm_dynamic_vlanpool: Creation complete after 0s [id=uni/infra/vlanns-[aci_vmm_dynamic_vlanpool]-static]

Error: The allocMode of Encap 100-101 block should match the namespace or be set to inherit
│
│   with aci_ranges.vlan_pool_static["range1"],
│   on 03c_fabric_accesspol.tf line 142, in resource "aci_ranges" "vlan_pool_static":
│  142: resource "aci_ranges" "vlan_pool_static" {
│

```

### References

* #0000

**Comment by tigelane** [comment]
It doesn't work like this.  You have to put a static range in a dynamic allocation mode pool.  If you want to mix static allocation and dynamic then the VLAN Pool needs to be set to Dynamic.  You can then put either Dynamic or Static below it.  Go check this in the UI.  The following works on Version 4.2(5n).

```
resource "aci_vlan_pool" "aci_vlanpool" {
  name       = "aci-vlanpool"
  alloc_mode = "dynamic"
}

resource "aci_ranges" "vlan_pool_static" {
  vlan_pool_dn = aci_vlan_pool.aci_vlanpool.id
  from         = "vlan-100"
  to           = "vlan-101"
  alloc_mode   = "static"
  role         = "external"
}

resource "aci_ranges" "vlan_pool_dynamic" {
  vlan_pool_dn = aci_vlan_pool.aci_vlanpool.id
  from         = "vlan-102"
  to           = "vlan-103"
  alloc_mode   = "dynamic"
  role         = "external"
}
```

**Comment by shrsr** [comment]
@tigelane is right. You can put a static range in a static or dynamic allocation mode pool, but if you want to mix static and dynamic ranges in the same pool, the pool allocation mode should be set to dynamic. We're closing this issue as @tigelane's example is correct.
