### ISSUE TITLE
Terraform cannot update/create ACI resource when there's already have same name's resource in APIC.

### ISSUE THREAD

**Issue by johncui0505** [CiscoDevNet/terraform-provider-aci#774]
Issue Reproduction:
1. Create a Tenant at APIC GUI, name "MyFirstTenant", no Description info added.
2. Try to create a Tenant with same name ("MyFirstTenant"), and also add a Description "Created by terraform".

Result:
1. Terraform output shows "Added" one Tenant.
2. No any change from APIC GUI. No "terraform" tag been added below Tenant "MyFirstTenant". And also no Description info there.
3. Checked Terraform tfstate file. showing as below:

      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "annotation": "",
            "description": "",
            "id": "uni/tn-MyFirstTenant",
            "name": "MyFirstTenant",
            "name_alias": "",
            "relation_fv_rs_tenant_mon_pol": null,
            "relation_fv_rs_tn_deny_rule": null
          },

No Description info there. Exactly same as the Tenant info which we created from APIC GUI.

4. If we re-run Terraform script, (same name, plus descritpion info), it will create a Tenant along with "terraform" tag at the APIC GUI, and also the Description info been added.

May I know how it works? And which behavior should be expected? 

Thanks,
John

**Comment by lhercot** [comment]
Please share the resource block you used.

If it is an existing tenant that you want to modify with Terraform, you should first import it with terraform import then use terraform apply to modify it.

Directly applying might work but it is not the way it should be used.

**Comment by lhercot** [comment]
@johncui0505 Could let us know if this is still an issue? If yes, please share the resource block you used.

**Comment by lhercot** [comment]
Closing this issue as we have not heard back. Feel free to reopen an issue if you still have any issues.
