### ISSUE TITLE
Relationship attributes are not imported when using terraform import

### ISSUE THREAD

**Issue by shrsr** [CiscoDevNet/terraform-provider-aci#776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### APIC version and APIC Platform

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Affected Resource(s)

* All resources that have relationship attributes

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

*See implementation in resource_aci_fvbd.go

**Comment by mike-guy** [comment]
I was going to raise an issue for this, but appears you're already aware of this. Examples of resources I've seen this with:

* aci_physical_domain does not import relation_infra_rs_vlan_ns
* aci_leaf_access_bundle_policy_group does not import relation_infra_rs_lacp_pol, relation_infra_rs_lldp_if_pol or relation_infra_rs_cdp_if_pol (plus presumably the rest associated with the object - untested)
* aci_l3_domain_profile does not import relation_infra_rs_vlan_ns
* aci_access_port_selector not importing relation_infra_rs_acc_base_grp
* aci_leaf_profile doesn't import relation_infra_rs_acc_port_p
* aci_attachable_access_entity_profiles does not import relation_infra_rs_dom_p

**Comment by mike-guy** [comment]
Additional for reference:

* aci_spine_access_port_selector does not import relation_infra_rs_sp_acc_grp

**Comment by shrsr** [comment]
@mike-guy Thank you for providing us with the list. We'll look into it.
