### ISSUE TITLE
Error: Relation Target DN does not exist - VMM deployment

### ISSUE THREAD

**Issue by yannickvranckx** [CiscoDevNet/terraform-provider-aci#779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.4 on windows_amd64

### APIC version and APIC Platform

APIC 4.2(7)

### Affected Resource(s)

resource "aci_vmm_domain"
resource "aci_attachable_access_entity_profile"

### Terraform Configuration Files

```hcl
resource "aci_attachable_access_entity_profile" "aaep_industrial" {
  depends_on               = [aci_vmm_domain.industrial]
  description              = "aaep for vmm domain industrial"
  name                     = var.aaep_industrial
  relation_infra_rs_dom_p  = ["VMware/vDS_ACI_Industrial"]
```

```hcl
resource "aci_vmm_domain" "industrial" {
    provider_profile_dn                   = "uni/vmmp-VMware"
    name                                  = var.vmm_domain_name
    access_mode                           = "read-write"
    pref_encap_mode                       = "vlan"
    relation_vmm_rs_default_cdp_if_pol    = data.aci_cdp_interface_policy.cdp_industrial.id
    relation_vmm_rs_default_lldp_if_pol   = data.aci_lldp_interface_policy.lldp_industrial.id
    relation_vmm_rs_default_lacp_lag_pol  = data.aci_lacp_policy.port_channel_pol.id
    relation_infra_rs_vlan_ns             = aci_vlan_pool.industrial.id
}
```

### Expected Behavior

The AAEP should be linked to the VMM domain without an error, but an error does occur. The config is applied anyways.

### Actual Behavior

Terraform produces an error, it is stating it has not found relation target dn Vmware/vDS_ACI_Industrial. However the config is applied and the from the AAEP side, the domain is formed.

### Steps to Reproduce

1. `terraform plan -out "vmm_policies.plan"`
2. `terraform apply "vmm_policies.plan"

### Important Factoids

- Running Terraform on a Windows x64 client
- Direct connection to the Cisco APIC
- Using cert-based authentication
![image001](https://user-images.githubusercontent.com/41998248/150590482-73f0555e-71b6-4362-90d4-d65736b4568f.png)
![image002](https://user-images.githubusercontent.com/41998248/150590489-c154c036-b01d-45ca-bd14-fd1f239821f8.png)
![image003](https://user-images.githubusercontent.com/41998248/150590492-c9b3c1f1-d2b7-4933-b560-e32d6fd40dc1.png)

**Comment by lhercot** [comment]
You should use the interpolation for the DN of the domain.
So I would do:
```
relation_infra_rs_dom_p  = [aci_vmm_domain.industrial.id]
```

Now is you still want to hard set it, the DN is not "VMware/vDS_ACI_Industrial" but it is "uni/vmmp-VMware/dom-vDS_ACI_Industrial".

Let us know if that fixes the issue.

**Comment by lhercot** [comment]
@yannickvranckx Did it fix the issue?

**Comment by yannickvranckx** [comment]
> @yannickvranckx Did it fix the issue?

Hello,

That did fix the issue.
