### ISSUE TITLE
Importing Application profile

### ISSUE THREAD

**Issue by cvad2or** [CiscoDevNet/terraform-provider-aci#78]
Hello,

I have an issue with importing App profile to Terraform from Cisco ACI. I use next resource in .tf file:

 resource "aci_application_profile" "APP_4" { 
name= "APP_4" 
tenant_dn= "uni/tn-New"  
} 
 and importing CLI will be:

 **terraform import aci_application_profile.APP_4 uni/tn-New/ap-APP_4** 

but after successful importing this resource and during the planning I receive next message:

  **# aci_application_profile.APP_4 must be replaced**
-/+ resource "aci_application_profile" "APP_4" {
      + annotation  = (known after apply)
      + description = (known after apply)
      ~ id          = "uni/tn-New/ap-APP_4" -> (known after apply)
        name        = "APP_4"
      + name_alias  = (known after apply)
      ~ prio        = "unspecified" -> (known after apply)
      **+ tenant_dn   = "uni/tn-New" # forces replacement**
    }

What I am doing wrong? Why terraform replace the existing configuration?

Thanks a lot.

**Comment by nkatarmal-crest** [comment]
@cvad2or Thanks for opening this. I will look into this issue.

**Comment by cvad2or** [comment]
> @cvad2or Thanks for opening this. I will look into this issue.

Hello, do you think this is a problem only with app or may be with all resources?

**Comment by cvad2or** [comment]
> @cvad2or Thanks for opening this. I will look into this issue.

Hello, do you think this is a problem only with app or may be with all resources?

**Comment by nkatarmal-crest** [comment]
It may be an issue with some other resource as well, where the parentDN extraction logic is not working as per the dn format. I will check all the resources and will take necessary actions to resolve them.

**Comment by jhtut** [comment]
This issue is not just specific to "Application Profile".  I tried importing VRF, BD, Subnet, all import for those resources are missing the parent dn.  Do we know when likely it will be fixed?

**Comment by jhtut** [comment]
@nkatarmal-crest  Is there progress made on this?

**Comment by d0ckt8le** [comment]
> This issue is not just specific to "Application Profile". I tried importing VRF, BD, Subnet, all import for those resources are missing the parent dn. Do we know when likely it will be fixed?

I am also having this problem when importing a vrf.
It wants to recreate.

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.

**Comment by jhtut** [comment]
@nkatarmal-crest Thanks for fixing.  I've tested with terraform v0.13 on ACI 4.2.1 for Tenant, VRF, BD and working fine to import.

Jus that it's trying to add annotation which flagged "~ update in-place".  I believe you can close this one now.

**Comment by jhtut** [comment]
@nkatarmal-crest  Testing more import and noticed that aci_epg_to_contract doesn't support import.  Anyhow, I tried and received this error "Error: Contract Type: Value must be from [provider, consumer]".  

Any plan to support importing for aci_epg_to_contract?
