### ISSUE TITLE
Terreaform Parallelism problem

### ISSUE THREAD

**Issue by kozhabergenova** [CiscoDevNet/terraform-provider-aci#802]
### Terraform Version
terraform -v
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.0

### APIC Version
Application Policy Infrastructure Controller
Version: 4.2(4i)

###Issue
As my code growth, I faced an issue with duration of the "terraform plan", approximately 3 and a half minutes. And this is only for two DCs APIC. So, I considered the using of parallelism flag. But, I encountered a bug, I guess. Anyway, is there any possibility to decrease plan duration?
### Expected Behavior

terraform plan -parallelism=50

No changes. Your infrastructure matches the configuration.

### Actual Behavior
terraform plan -parallelism=50
1st try
Plan: 292 to add, 0 to change, 0 to destroy.
2nd try
Plan: 270 to add, 0 to change, 0 to destroy.
and etc

**Comment by lhercot** [comment]
Please upgrade to latest ACI Terraform provider (v2.0.1) which include a retry mechanism to improve how many API calls are applied. By increasing the parallelism, you might hit issues with APIC not able to reply fast enough.

If you start to see issues of time, you should start to look at splitting your config across multiple plans / workspaces.

**Comment by lhercot** [comment]
@kozhabergenova Could you let us know if this is still an issue?

**Comment by kozhabergenova** [comment]
@lhercot Hi! I upgraded to the latest version and it reduced the plan time little bit
About splitting the config across multiple plans, unfortunately, I have a lot of resources that reused in my code, so I can't "target" only one module or certain resources at a time
Anyway, thanks for your reply!

**Comment by lhercot** [comment]
@kozhabergenova, 

I am closing this issue as this issue is dependent on your plan structure.

But would you be able to run the following script https://github.com/ciscoecosystem/tf-state-resource-stats against your state file and post the result here?

This will give us an idea on how many resources of each type you are using and allow us to better understand how we could improve this issue.
