### ISSUE TITLE
Apply a VPC Interface Policy Group - relation_infra_rs_acc_bndl_grp_to_aggr_if 

### ISSUE THREAD

**Issue by JBaptisme33** [CiscoDevNet/terraform-provider-aci#81]
### Description

How to MAP attribute relation_infra_rs_acc_bndl_grp_to_aggr_if  (class aci_pcvpc_interface_policy_group) to Class pcAggrIf ?

It seem not possible to dynamicly provide relation between a VPC Policy Group and applied PC/VPC interfaces via the correlty definied Acces_Port_Selector ?

> resource "aci_access_port_selector" "VPC_Leaves_Access_Port_selector" {
>   for_each                       = var.Leaves_Pairs
>   leaf_interface_profile_dn      = aci_leaf_interface_profile.VPC_Leaves_Profile_ifselector[each.key].id
>   name                           = "${each.key}_Access_Port_range"
>   access_port_selector_type      = "range"
>   relation_infra_rs_acc_base_grp = aci_pcvpc_interface_policy_group.VPC_LACP_active.id
> }

>   aci_pcvpc_interface_policy_group.VPC_LACP_active will be updated in-place
>   ~ resource "aci_pcvpc_interface_policy_group" "VPC_LACP_active" {
>         id                                        = "uni/infra/funcprof/accbundle-VPC_LACP_Active"
>         lag_t                                     = "node"
>         name                                      = "VPC_LACP_Active"
>       ~ relation_infra_rs_acc_bndl_grp_to_aggr_if = [
>           - "topology/pod-1/node-101/sys/aggr-[po9]",
>           - "topology/pod-1/node-102/sys/aggr-[po9]",
>         ]
>         relation_infra_rs_att_ent_p               = "uni/infra/attentp-phys_AttEntityP"
>         relation_infra_rs_lacp_pol                = "uni/infra/lacplagp-LACP_Active"
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.

Which attribute apply to relation_infra_rs_acc_bndl_grp_to_aggr_if ? 
When looking for pcAggrIf class in Explorer, (when policy group was manually applied), I don't find which objet can make the relation between applied PO on leaf and Policy Group

### New or Affected Resource(s) + ACI Class(es):
TF 0.12.28
ACI 0.3.2

Thanks for all

**Comment by nkatarmal-crest** [comment]
CC: @vfiftyfive  Can you please assist here?

**Comment by vfiftyfive** [comment]
Hi @JBaptisme33 ,

If I understand correctly, you want to create a VPC Policy Group and attach interfaces. Here's a snippet on how to do it. You'll notice that here I'm using an existing Policy Group, but creating the object is trivial.

```hcl
data "aci_leaf_interface_profile" "vpc_acc_port_p" {
  name = "Prof_VPC_BM_k8s_master"
}

resource "aci_access_port_selector" "vpc_acc_port_s" {
  leaf_interface_profile_dn = data.aci_leaf_interface_profile.vpc_acc_port_p.id
  name                      = "interfaces"
  access_port_selector_type = "range"
  relation_infra_rs_acc_base_grp = data.aci_pcvpc_interface_policy_group.vpc_polgrp.id
}

resource "aci_access_port_block" "vpc_acc_port_b" {
  access_port_selector_dn = aci_access_port_selector.vpc_acc_port_s.id
  name= var.block_name
  from_port = "10"
  to_port = "10"
}

  data "aci_pcvpc_interface_policy_group" "vpc_polgrp" {
  name = "PolGrp_VPC_BM_k8s_master"
}
```

Nic

**Comment by nkatarmal-crest** [comment]
@vfiftyfive can we close this one?

**Comment by euphdk** [comment]
I don't think relation_infra_rs_acc_bndl_grp_to_aggr_if should be available as an option the aci_pcvpc_interface_policy_group/aci_leaf_access_bundle_policy_group?

The relation is created on the aci_access_port_selector as @vfiftyfive mentions, and relation_infra_rs_acc_bndl_grp_to_aggr_if refers to an interface which is internally named in ACI. Hope it makes sense?

**Comment by euphdk** [comment]
Tried the following patch, and it seems to remove the problem.

I'm not proficient in either Terraform code or the provider code and is stille learning the ins and outs of ACI. So I don't know if this creates any other problems.

```
diff --git a/aci/resource_aci_infraaccbndlgrp.go b/aci/resource_aci_infraaccbndlgrp.go
index 91dabdd..2e4c6a5 100644
--- a/aci/resource_aci_infraaccbndlgrp.go
+++ b/aci/resource_aci_infraaccbndlgrp.go
@@ -60,6 +60,7 @@ func resourceAciPCVPCInterfacePolicyGroup() *schema.Resource {
                                Type:     schema.TypeSet,
                                Elem:     &schema.Schema{Type: schema.TypeString},
                                Optional: true,
+                               Computed: true,
                                Set:      schema.HashString,
                        },
                        "relation_infra_rs_stormctrl_if_pol": &schema.Schema{
```
