### ISSUE TITLE
Inconsistent and confusing approach to "relation_fv_" type attributes - clarification needed

### ISSUE THREAD

**Issue by mike-guy** [CiscoDevNet/terraform-provider-aci#811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform version
Terraform v1.1.4
on windows_amd64

terraform {
  required_providers {
    aci = {
      source  = "CiscoDevNet/aci"
      version = "2.0.0"
    }
  }
}

### APIC version and APIC Platform

Application Policy Infrastructure Controller
Version: 5.2(1g)

Cisco dCloud lab - Cisco ACI 5.2 with VMware Lab v1

### Affected Resource(s)

aci_application_epg

### Issue

When importing an existing ACI app EPG, undocumented attributes are imported, namely "relation_fv_rs_path_att". This looks to be any static path mappings associated with the EPG. Configuring the code to use this undocumented attribute works, however a similiar approach with domain mappings does not work.

#### Example state after import

```
module.tsw_tenant0_application.aci_application_epg.app_epg["tsw0AP0_tsw0ctx0BD0epg0"]:
resource "aci_application_epg" "app_epg" {
    application_profile_dn       = "uni/tn-TSW_Tenant0/ap-tsw0AP0"
    flood_on_encap               = "disabled"
    fwd_ctrl                     = "none"
    has_mcast_source             = "no"
    id                           = "uni/tn-TSW_Tenant0/ap-tsw0AP0/epg-tsw0ctx0BD0epg0"
    is_attr_based_epg            = "no"
    match_t                      = "AtleastOne"
    name                         = "tsw0ctx0BD0epg0"
    pc_enf_pref                  = "unenforced"
    pref_gr_memb                 = "exclude"
    prio                         = "unspecified"
    relation_fv_rs_bd            = "uni/tn-TSW_Tenant0/BD-tswctx0BD0"
    relation_fv_rs_cons          = []
    relation_fv_rs_cons_if       = []
    relation_fv_rs_cust_qos_pol  = "uni/tn-common/qoscustom-default"
    relation_fv_rs_fc_path_att   = []
    relation_fv_rs_intra_epg     = []
    relation_fv_rs_node_att      = []
    relation_fv_rs_path_att      = [
        "topology/pod-1/paths-101/pathep-[eth1/14]",
        "topology/pod-1/paths-102/pathep-[eth1/13]",
    ]
    relation_fv_rs_prot_by       = []
    relation_fv_rs_prov          = [
        "uni/tn-TSW_Tenant0/brc-tsw0ctrct0",
        "uni/tn-TSW_Tenant0/brc-tsw0ctrct2",
    ]
    relation_fv_rs_prov_def      = []
    relation_fv_rs_sec_inherited = []
    shutdown                     = "no"
}
```

On a related note, there is no equivalent for domain mappings (phys/vmm etc.). I've seen mentions of "relation_fv_rs_dom_att" floating around on the Internet, but this does not work...

```hcl
tf plan
╷
│ Error: Unsupported argument
│
│   on ..\terraform-aci-application\main.tf line 169, in resource "aci_application_epg" "app_epg":
│  169:   relation_fv_rs_dom_att = each.value.domain_path_tdns
│
│ An argument named "relation_fv_rs_dom_att" is not expected here.
╵
```

### Clarification/Changes needed

1. Are these relation_fv_rs... attributes being phased out with a view of utilising the "aci_epg_to_static_path" and "aci_epg_to_domain" resources accordingly - or will they remain?
2. If the intention is that these relation_fv_rs attributes are going to stay, then there is an issue with the import statement importing undocumented attributes. 
3. If the intention is that these relation_fv_rs attributes are going to stay, then there is an issue with "relation_fv_rs_path_att" being supported and "relation_fv_rs_dom_att" not being supported.

**Comment by lhercot** [comment]
relation_fv_rs_path_att is not usable in the way it exists. aci_epg_to_static_path has been the way to configure it for a while now.
We will use this issue to properly deprecate relation_fv_rs_path_att attribute in aci_application_epg.

**Comment by mike-guy** [comment]
Perfect thank you for the clarification. I'll ignore the imported attributes with a lifecycle block for the time being.

**Comment by mike-guy** [comment]
Could I just ask - is this approach (moving away from the "relation_" attributes to resources) - something that is being adopted across the board? I see similar with other resources where it appears the relation_ attribute is redundant, so good just to understand the longer-term intention.

**Comment by lhercot** [comment]
No not really.
In this case the relation is not complete. The relation need additional parameters to actually work (vlan-id, ...). That is why we are going to deprecate it and we might re-introduce a similar capability with a block later but this is not a priority right now as we already have a separate resource to cover the gap.

Yes,  we have resources which have relations attributes and we have also a separate resource specifically for that relation.
There is mainly 2 reasons for that:
* First, it is due to the way Terraform "own" a resource object and will destroy it when you do `terraform destroy`. This might not work for customers that want to use an existing EPG but manipulate the path attachement independently. In this case a dedicated resource is needed.
* Secondly, the definition of the relations in the parent resource allow us to impose that only those relationship exists which we cannot do in the separate resource.

Hope this clarifies the situation.

**Comment by mike-guy** [comment]
Appreciate you're quick feedback - thank you very much. These relationship attributes have always left me a little confused, but from your response I gather they are staying.

Where a resource exists as well as a relatioship attribute, is it expected that BOTH are configured for it to be properly managed? Take EPG contracts as an example...

* Under aci_application_epg you have "relation_fv_rs_cons" and "relation_fv_rs_prov" which specify provider/consumer relationships
* You also have a separate resource called "aci_epg_to_contract" that appears to do the same thing (at face value anyway)

In this instance, if I JUST use relation_fv_rs_cons/relation_fv_rs_prov all appears to work as expected. Should I be looking to use the aci_epg_to_contract resource type as well? It doesn't appear to provide much additional hence I'm a little confused.

**Comment by lhercot** [comment]
No, you should use one OR the other. Using both will make the resources fight each other in certain cases.

**Comment by lhercot** [comment]
We have added a deprecation message to the attribute and will remove the deprecated attributes in the next major release.

**Comment by aiesam** [comment]
> We have added a deprecation message to the attribute and will remove the deprecated attributes in the next major release.

In 2.15.0, the problem still exists due to the presence of this attribute (relation_fv_rs_path_att). Once imported and we try to remove the entry from resource file, it deletes the resource from the APIC. My question is why is this deprecated field still part of the attributes being imported if is was deprecated in 2.2.0?
