### ISSUE TITLE
resource "aci_epg_to_contract" for exported contracts missing contract_type = "consumer contract interface" as option

### ISSUE THREAD

**Issue by DimmySa** [CiscoDevNet/terraform-provider-aci#812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version 1.15

### APIC version and APIC Platform

* Version: 5.2(3e) on premise

### Affected Resource(s)

* resource aci_epg_to_contract
* contract_type  = "provider" or "consumer"

### Terraform Configuration Files

```hcl
resource "aci_epg_to_contract" "example" {
  application_epg_dn = aci_application_epg.demo.id
  contract_dn        = aci_contract.demo_contract.id
  contract_type      = "provider"
  annotation         = "terraform"
  match_t            = "AtleastOne"
  prior              = "unspecified"
}
```

### Debug Output

there are no error messages.

Hereunder is the output from the resources.

```hcl

the exported contract CON_EPG-2004_PVD_EPG-701:

contract-output = {
  "annotation" = ""
  "description" = ""
  "id" = "uni/tn-STAGE1/cif-CON_EPG-2004_PVD_EPG-701"
  "name" = "CON_EPG-2004_PVD_EPG-701"
  "name_alias" = ""
  "tenant_dn" = "uni/tn-STAGE1"
}

the bind with VLAN-801-EPG:

epg-output = {
  "annotation" = "orchestrator:terraform"
  "application_epg_dn" = "uni/tn-STAGE1/ap-STAGE1-APP/epg-VLAN-801-EPG"
  "contract_dn" = "uni/tn-STAGE1/cif-CON_EPG-2004_PVD_EPG-701"
  "contract_type" = "consumer"
  "description" = tostring(null)
  "id" = "uni/tn-STAGE1/ap-STAGE1-APP/epg-VLAN-801-EPG/rscons-CON_EPG-2004_PVD_EPG-701"
  "match_t" = tostring(null)
  "prio" = "unspecified"
}

```

### Expected Behavior

A contract that is exported to another Tenant should be then be bound with EPGs with the option "consumer contract interface".
The current provider does not give this option apart from "consumer" or "provider"

![image](https://user-images.githubusercontent.com/32894428/156154606-144b3413-b53a-45ff-9804-e759e5ff70a4.png)

### Actual Behavior

The option given for contract_type = "provider" Or "consumer", doesn't have any effect on the exported contract

**Comment by lhercot** [comment]
We have added an aci_epg_to_contract_interface resource that will be available in the next release.
