### ISSUE TITLE
Resources to manage Spine Switch Profiles and Interfaces

### ISSUE THREAD

**Issue by aj-cruz** [CiscoDevNet/terraform-provider-aci#87]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resources to manage Spine Switch profiles and Spine Switch interfaces.

### New or Affected Resource(s) + ACI Class(es):

aci_spine_port_policy_group + infraSpAccPortGrp
aci_spine_interface_profile + infraSpAccPortP
aci_spine_port_selector + infraRsSpAccPortP
aci_spine_profile + infraSpineP + infraSpineS

### APIC version and APIC Platform

V 4.2(3q) and on-prem (simulator).

**Comment by nkatarmal-crest** [comment]
@aj-cruz Thank you for opening this issue. We will add the required resources shortly.

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.
