### ISSUE TITLE
Creation of a new contract and new contract relationship under application epg is not diffed correctly during TF plan and apply

### ISSUE THREAD

**Issue by aleksandr-kushch** [CiscoDevNet/terraform-provider-aci#875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Verified this issue, and it is present in the following terraform provider versions: 0.7.0, 2.1.0, 2.2.0

### APIC version and APIC Platform

Version: 4.2(5d) on premise

### Affected Resource(s)

aci_application_epg

### Terraform Configuration Files

1. aci_application_epg.tf.json

  ```
"EPG_CF_TEST_1-APP_TEST-TN_TEST": {
    "name": "EPG_CF_TEST_1",
    "application_profile_dn": "uni/tn-TN_TEST/ap-APP_TEST",
    "description": "",
    "relation_fv_rs_prov": [
        "${aci_contract.CON_TEST_2_2_0-TN_TEST.id}",
    ],
    "relation_fv_rs_cons": [
    ],
    "relation_fv_rs_bd": "uni/tn-TN_TEST/BD-BD_TEST"
},
  ```

2. aci_contract.tf.json

  ```
"CON_TEST_2_2_0-TN_TEST": {
    "name": "CON_TEST_2_2_0",
    "description": "",
    "tenant_dn": "uni/tn-TN_TEST"
},
  ```

3. aci_contract_subject.tf.json

  ```
"SBJ_CON_TEST_2_2_0-CON_CON_TEST_2_2_0-TN_TEST": {
    "name": "SBJ_CON_TEST_2_2_0",
    "description": "",
    "contract_dn": "${aci_contract.CON_TEST_2_2_0-TN_TEST.id}",
    "relation_vz_rs_subj_filt_att": [
        "uni/tn-common/flt-icmp",
        "uni/tn-common/flt-default"
    ]
},
  ```

### Debug Output

https://gist.github.com/aleksandr-kushch/be091e3c40bcd356d0f55991ce7c30c4

### Panic Output

Not Applicable

### Expected Behavior

During TF plan or apply, when a new contract is created and this contract is also consumed or provided under the existing AEPG, the Terraform provider must display the new contract relationship addition under aci_application_epg resource.

### Actual Behavior

During plan or apply, when a new contract is created and this contract is also consumed or provided under the existing AEPG, TF does not display the new contract relationship under existing application EPG. Instead it outputs 'unchanged attributes hidden' without explicitly highlighting the new contract that is being added.

### Steps to Reproduce

1. Use TF Provider version 0.7.0. 2.1.0 or the latest 2.2.2
2. Add new contract to aci_contract.tf.json
3. Consume or provide this new contract under aci_application_epg resource under either relation_fv_rs_prov or relation_fv_rs_cons list.
4. Run terraform plan or terraform apply
5. Observe either terraform plan or terraform apply output, the new contract that was added to aci_contract.tf.json, is not being explicitly displayed as an addition under relation_fv_rs_prov or relation_fv_rs_cons.

**Comment by akinross** [comment]
Hi @aleksandr-kushch,

I'm currently investigating your issue but I am not fully sure what you mean exactly. Would you be able to have a short call to briefly discuss and show the issues that you are facing?

Kind regards,
Akini

**Comment by aleksandr-kushch** [comment]
> Hi @aleksandr-kushch,
> 
> I'm currently investigating your issue but I am not fully sure what you mean exactly. Would you be able to have a short call to briefly discuss and show the issues that you are facing?
> 
> Kind regards, Akini

Hi Akini,

Thank you for looking into this.

Sure we can have a call. I have dropped you an e-mail from my work e-mail address to have the call arranged.

Kind regards,

Aleks

**Comment by akinross** [comment]
One line summary of what we discussed: during execution ( in your case contract id but holds true for any computed attribute value ) the id is not known prior to apply, and thus that is will not reflect in your output. this is expected terraform behaviour.
