### ISSUE TITLE
aci_contract resource issue

### ISSUE THREAD

**Issue by kozhabergenova** [CiscoDevNet/terraform-provider-aci#897]
### Terraform Version
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v2.3.0

### APIC Version
Application Policy Infrastructure Controller
Version: 4.2(4i)

### Affected Resource(s)
resource "aci_contract"

### Terraform Configuration Files - Module for Contract Creation
locals {

subject  = { for subj in var.subjects : subj.subject_name => subj }

port_entries  = transpose({ for k, v in local.subject : k => v.dest_ports })

}

data "aci_tenant" "common" {
  name = "common"
}

resource "aci_contract" "contract" {
  tenant_dn    = data.aci_tenant.common.id
  name           = "${var.contract_name}_ct"
  scope          = var.scope
}

resource "aci_contract_subject" "subject" {
 for_each                              = local.subject
 contract_dn                        = aci_contract.contract.id
 name                                   = each.key
 relation_vz_rs_subj_filt_att = [aci_filter.filter[each.key].id]
 rev_flt_ports                        = "no"
}

resource "aci_filter" "filter" {
 for_each        = local.subject
 tenant_dn     = data.aci_tenant.common.id
 name            = "${each.value.filter_name}_flt"
} 

resource "aci_filter_entry" "filter_entry" {
 for_each      = local.port_entries
 filter_dn       = aci_filter.filter[each.value[0]].id
 ether_t         = "ip"
 prot              = local.subject[each.value[0]].protocol
 d_from_port = element(split("-", each.key), 0)
 d_to_port     = element(split("-", each.key), 1)
 stateful         = "yes"
}

resource "aci_epg_to_contract" "consumer" {
   for_each                      = toset(var.epg_from)
   application_epg_dn    = each.key
   contract_dn                = aci_contract.contract.id
   contract_type             = "consumer"
}

resource "aci_epg_to_contract" "provider" {
   for_each                      = toset(var.epg_to)
   application_epg_dn.   = each.key
   contract_dn                = aci_contract.contract.id
   contract_type             = "provider"
}

### Debug Output

$ terraform plan (Partial)
.........

   module.dc_contracts.module.prodng_to_proddb.aci_contract.contract will be updated in-place
  ~ resource "aci_contract" "contract" {
      + filter_entry_ids = (known after apply)
      + filter_ids       = (known after apply)
        id               = "uni/tn-common/brc-prodng_to_proddb_ct"
        name             = "prodng_to_proddb_ct"
        # (5 unchanged attributes hidden)
    }
   module.dc_test_contracts.module.testprodng_to_testproddb.aci_contract.contract will be updated in-place
  ~ resource "aci_contract" "contract" {
      + filter_entry_ids = (known after apply)
      + filter_ids       = (known after apply)
        id               = "uni/tn-common/brc-testprodng_to_testproddb_ct"
        name             = "testprodng_to_testproddb_ct"
        # (5 unchanged attributes hidden)
    }
Plan: 0 to add, 36 to change, 0 to destroy.

### Expected Behavior
No changes. Your infrastructure matches the configuration.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

Nothing is changed, so it's not clear why terraform wants to add "filter_entry_ids" and "filter_ids" arguments, which don't even described in [documentation](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/contract)

We hit this issue after upgrading from 2.0.1 to 2.3.0

**Comment by PacketChad** [comment]
Same issue when importing a contract.  Isolated down to a single resource to verify the behavior.

Terraform version: 1.2.2
Provider Version: 2.3.0
ACI Version: 5.2(2e)

  # aci_contract.foocontract will be updated in-place
  ~ resource "aci_contract" "foocontract" {
      + filter_entry_ids = (known after apply)
      + filter_ids       = (known after apply)
        id               = "uni/tn-ETSL/brc-foocontract"
        name             = "foocontract"
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by jamesbtate** [comment]
I am also hitting this problem. We have hundreds of contracts and the plan/apply output is very cluttered now. ACI 4.2(7q) and provider 2.3.0. The problem does not seem to occur with contracts created via Terraform after the upgrade to 2.3.0.

I tried upgrading to 2.4.0 but the problem persists.

**Comment by kozhabergenova** [comment]
> khkhh

**Comment by kozhabergenova** [comment]
> We have hundreds of contracts and the plan/apply output is very cluttered now.
I use [lifecycle meta-argument](https://www.terraform.io/language/meta-arguments/lifecycle)(of course, until the bug fix) to eliminate the excess output:
```
resource "aci_contract" "contract" {
  tenant_dn   = data.aci_tenant.common.id
  name        = "${var.contract_name}_ct"
  scope       = var.scope
  lifecycle {
    ignore_changes = [
      filter_entry_ids,
      filter_ids,
    ]
  }
}
```

**Comment by jamesbtate** [comment]
@kozhabergenova thanks for the suggestion, that did clear up the output for us.

**Comment by akinross** [comment]
@kozhabergenova filter_ids and filter_entry_ids are computed attributes that are used to ease a dn lookup of filter and their entries (this is also why it is not documented). The issue was happening due to differences to a statefile when no filter and or filter entry was/is provided. 

Prior to 2.3.0 this would result in a null value in the statefile for filter_id and filter_entry_id, from 2.3.0 onward this would result in an empty list. When no filter was provided the null was however not transformed to an empty list, due to a bug in the read function, thus resulting in changed attribute output (cosmetic change since it is not impacting any APIC config).

**Comment by kozhabergenova** [comment]
@akinross I get it, thanks
> cosmetic change since it is not impacting any APIC config
still very inconvenient =)

**Comment by akinross** [comment]
@kozhabergenova you are welcome, hope it solves your inconvenience soon.
