### ISSUE TITLE
aci_fabric_wide_settings resource completion

### ISSUE THREAD

**Issue by robvand** [CiscoDevNet/terraform-provider-aci#923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s) + ACI Class(es):

* aci_fabric_wide_settings and infraSetPol class.

Would like to see domainValidation and reallocateGipo added.

### APIC version and APIC Platform

* V 5.2

### Potential Terraform Configuration

```hcl
resource "aci_fabric_wide_settings" "example" {
  domainValidation = "yes" # no|yes
  reallocateGipo = "yes" # no|yes
}
```

### References

* #0000

**Comment by lhercot** [comment]
Check if other attributes are missing and add all missing attributes from the infraSetPol class.
