### ISSUE TITLE
MAC attribute in aci_destination_of_redirected_traffic resource should be optional

### ISSUE THREAD

**Issue by ttrabatt** [CiscoDevNet/terraform-provider-aci#942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

ACI supports addition of IP destinations for the L4-L7 policies redirect without need of specify the MAC address for each destination, while provider resource still make it mandatory attribute making orchestration cumbersome.
This will be needed for both aci_service_redirect_policy  while managing primary  policies and backup policies as per issue #941 related to managing backup policies as well  (issue #941 has been just submitted)

### New or Affected Resource(s) + ACI Class(es):

aci_destination_of_redirected_traffic.fv-vnsRedirectDest

### APIC version and APIC Platform

APIC 5.2.6e

Terraform v1.2.6
on darwin_arm64

provider registry.terraform.io/ciscodevnet/aci v2.5.2
provider registry.terraform.io/hashicorp/null v3.1.1
provider registry.terraform.io/hashicorp/vsphere v2.2.0

### Potential Terraform Configuration

```hcl
resource "aci_destination_of_redirected_traffic" "example" {
  service_redirect_policy_dn  = aci_service_redirect_policy.example.id
  ip                          = "1.2.3.4"
  mac                         = "12:25:56:98:45:74". # this should be optional because ACI feature that allow automatic discovery of MAC
  ip2                         = "10.20.30.40"
  dest_name                   = "last"
  pod_id                      = "5"
  annotation                  = "load_traffic_dest"
  description                 = "From Terraform"
  name_alias                  = "load_traffic_dest"
}
```

### References

#941

**Comment by mihiguch** [comment]
MAC address is not mandatory after APIC release 5.2 (dynamic MAC detection feature). Thinking about the compatibility with a release prior to 5.2, I think we can take the following update on the doc.
-After 5.2 release with tracking enabled, MAC address is not a mandatory configuration on APIC. Terraform configuration wise, MAC can be set to 00:00:00:00:00:00 to use dynamic MAC detection feature.
