### ISSUE TITLE
leaf_profile documentation missing reference to leaf_selector_ids

### ISSUE THREAD

**Issue by brandon-shelton** [CiscoDevNet/terraform-provider-aci#946]
The argument reference, https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/leaf_profile, doesn't list a reference to leaf_selector_ids, which can be used instead of creating the leaf selectors using object blocks within the resource.

**Comment by shrsr** [comment]
@brandon-shelton The code doesn't have the provision to create leaf selectors by passing values to leaf_selector_ids. The attribute leaf_selector_ids just gets populated with the appropriate ids that are created by leaf_selector attribute via its sub attributes and is utilized in the back-end for other functionalities. That's the reason why leaf_selector_ids is not specified in the argument reference.

Please let me know if this clarifies the issue. If you were expecting a different behaviour by the resource, please provide me with an example for the configuration.

**Comment by shrsr** [comment]
@brandon-shelton Please let us know if you have any other questions regarding this.

**Comment by lhercot** [comment]
Closing this issue as we have not heard back. Feel free to reopen or comment if still needed.
