### ISSUE TITLE
SR L3out handoff missing in ACI provider

### ISSUE THREAD

**Issue by ttrabatt** [CiscoDevNet/terraform-provider-aci#947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### All ACI releases after 5.0

* aci_5.0 onward + l3extOut (e.g.: uni/tn-infra/out-CDC-2_SRL3out) and l3extConsLbl relation in User Tenant SRL3out config

### APIC version and APIC Platform

* V ACI 5.0 onward and all APIC platforms

### Potential Terraform Configuration

```hcl
// create L3out object
resource "aci_l3_outside" "l3out" {
    tenant_dn                       = var.tenant_dn
    name                            = var.name
    description                     = var.description
    annotation                      = var.annotation
    relation_l3ext_rs_ectx          = var.vrf_dn
    relation_l3ext_rs_l3_dom_att    = var.l3dom_dn
}
.
```

The above example is for traditional L3out but we would need it specifically for SR L3out in both Infra and User tenant l3extConsLbl settings to associate the User SRL3out to the expected Infra SRL3out
[SRL3out 

### References

* #0000

**Comment by akinross** [comment]
Hi @ttrabatt, please see resource [aci_l3out_consumer_label](https://registry.terraform.io/providers/CiscoDevNet/aci/latest/docs/resources/l3out_consumer_label) for this functionality. We will track the rest of the SR MPLS functionality in the following issue: https://github.com/CiscoDevNet/terraform-provider-aci/issues/1022
