### ISSUE TITLE
Support additional dn composition

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#96]
### Description

Decompose dn into discrete resource attributes for static path.

### Syntax example
Existing Syntax:

```hcl
resource "aci_epg_to_static_path" "example" {
  application_epg_dn  = aci_application_epg.on_prem_epg.id
  tDn  = "topology/pod-1/paths-101/pathep-[eth1/5]"
  encap  = 100
}
```

support following resource and syntax to reference the path:

```hcl
data "aci_fabric_path_ep" "example"{
  pod_id = "1"
  leaf_id = "101"
  port_id = "eth1/5"
}
```
We must be able to accommodate any type of port.

Nic

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.
