### ISSUE TITLE
Add details on how to escape character for APIC login in the documentation

### ISSUE THREAD

**Issue by vfiftyfive** [CiscoDevNet/terraform-provider-aci#97]
### Description
Add details on how to escape character for APIC login in the documentation. Example of login + domain usage with escape character:

```hcl
provider "aci" {
  username = "apic:${var.login_domain}\\\\${var.username}"
  # private_key = var.aci_private_key
  # cert_name   = var.aci_cert_name
  password = var.password
  url      = var.apic_url
  insecure = true
}
```
Nic

**Comment by nkatarmal-crest** [comment]
This issue has been fixed in the version 0.5.0 of the provider. Please try that and let me know if we can close this issue or not.
